const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
const scripts=[...fs.readFileSync('dist/index.html','utf8').matchAll(/<script src="([^"]+)"/g)].map(x=>x[1]).filter(x=>x!=='app.js'&&!x.endsWith('-ui.js')&&x!=='game-renderer.js');
function game(){const c=vm.createContext({Intl,console});for(const f of scripts)vm.runInContext(fs.readFileSync('dist/'+f,'utf8'),c,{filename:f});return s=>vm.runInContext(s,c);}
let passed=0;function test(name,fn){const r=game();fn(r);r('validateSave(JSON.parse(JSON.stringify(state)))');passed++;console.log('PASS: '+name);}
// Prefunded regression fixture. The actual founder preparation, hires and supply are paid.
const company='state=fresh();state.cash=20000000;startOpening6("cafe",{location:"letna",design:"starter",options:{kind:"legacy",space:"starter"}});signCoffeeAgreement6("local","letna","blend-1",{enabled:true,target:25,budget:20000,reserve:1});for(let i=0;i<7;i++)nextWeek();';
const review='var q=acquisitionReviewQuote9("daily",1),p=startAcquisitionReview9("daily",1,q);';
const ready=review+'nextWeek();nextWeek();';
const buy='var ask=acquisitionSnapshot9("daily").asking,o=acquisitionOfferQuote9(p.id,ask);negotiateAcquisition9(p.id,ask,o);var close=acquisitionCloseQuote9(p.id),deal=closeAcquisition9(p.id,close);';
test('Founder and legacy firms migrate with an empty register and no money, stock or history changes',r=>{r('var old=JSON.parse(JSON.stringify(state));delete old.acquisitions9;var before=JSON.stringify(old),v=validateSave(old);delete v.acquisitions9;');assert(r('JSON.stringify(v)===before&&JSON.stringify(old)===before'));r('var before=JSON.stringify(state),q=acquisitionReviewQuote9("daily",1);');assert(r('JSON.stringify(state)===before&&q.fee===13000'));});
test('Review has an exact paid fee, takes two actual weeks, and cannot create historic rival stock',r=>{r(company+'var before=JSON.stringify(state),q=acquisitionReviewQuote9("daily",1);');assert(r('JSON.stringify(state)===before'));r('var cash=state.cash;var p=startAcquisitionReview9("daily",1,q),a=acquisitionAssets9("daily"),frozen=JSON.stringify(a.branches);');assert(r('cash-state.cash===q.fee&&a.branches.every(b=>b.lots.length===0&&b.people.length>0)&&p.status==="active"'));assert.throws(()=>r('startAcquisitionReview9("daily",1,q)'));r('nextWeek();');assert(r('p.status==="active"&&a.branches.some(b=>b.lots.length>0)'));r('nextWeek();var archive=JSON.stringify(p.snapshot);');assert(r('p.status==="ready"&&p.snapshot.week===p.due&&p.scope.every(id=>p.snapshot.branches.find(b=>b.id===id).history.length===2)&&p.snapshot.branches.filter(b=>!p.scope.includes(b.id)).every(b=>b.history.length<=1)'));r('nextWeek();');assert(r('JSON.stringify(p.snapshot)===archive'));});
test('Physical rival coffee preserves grams, FIFO profit, working capital and AI reserve decisions',r=>{r(company+ready+'var rival=state.rivals.find(r=>r.id==="daily"),a=acquisitionAssets9("daily"),h=rival.operations5.history.at(-1),before=JSON.stringify(state);for(const b of rival.operations5.branches)rivalOperating5(rival,b);');assert(r('JSON.stringify(state)===before'));assert(r('a.branches.every(b=>b.totals.bought-b.totals.used-b.totals.wasted===b.lots.reduce((n,l)=>n+l.grams,0))'));assert(r('h.branches.every(b=>b.inventory9.used===b.served*18)&&Math.abs(h.cashChange-(h.profit-h.investment+h.depreciation-h.principal+h.inventory9.cogs-h.inventory9.purchase+h.inventory9.waste))<=1'));assert(r('h.inventory9.purchase>0&&h.inventory9.cogs>0'));});
test('Stale fees, depleted reserves and quarterly limits never partially start a review',r=>{r(company+'var q=acquisitionReviewQuote9("daily",1);state.cash--;var before=JSON.stringify(state);');assert.throws(()=>r('startAcquisitionReview9("daily",1,q)'),/změnily/);assert(r('JSON.stringify(state)===before'));r('state.cash=13000;var q=acquisitionReviewQuote9("daily",1),before=JSON.stringify(state);');assert(r('!q.safe'));assert.throws(()=>r('startAcquisitionReview9("daily",1,q)'));assert(r('JSON.stringify(state)===before'));r(company+'var plan=planDefaultData6();plan.budgets.expansion=0;setCompanyPlan6(plan);var before=JSON.stringify(state);');assert.throws(()=>r('acquisitionReviewQuote9("daily",1)'));assert(r('JSON.stringify(state)===before'));});
test('Negotiation charges once per real week, returns a counteroffer and expires against changed seller assets',r=>{r(company+ready+'var q=acquisitionOfferQuote9(p.id,0),cash=state.cash,o=negotiateAcquisition9(p.id,0,q);');assert(r('!o.accepted&&o.minimum>0&&cash-state.cash===1500'));assert.throws(()=>r('acquisitionOfferQuote9(p.id,o.minimum)'));r('nextWeek();var ask=acquisitionSnapshot9("daily").asking,q=acquisitionOfferQuote9(p.id,ask);negotiateAcquisition9(p.id,ask,q);var before=JSON.stringify(state),close=acquisitionCloseQuote9(p.id);');assert(r('JSON.stringify(state)===before&&close.safe'));r('nextWeek();var before=JSON.stringify(state);');assert.throws(()=>r('closeAcquisition9(p.id,close)'),/platnou/);assert(r('JSON.stringify(state)===before'));});
test('Complete acquisition transfers actual identities, worn equipment, leases, debt and paid stock exactly once',r=>{r(company+ready+'var rival=state.rivals.find(r=>r.id==="daily");rival.debt=260000;rival.competition6.loanAmount=260000;rival.competition6.loanRemaining=260000;var sheet=acquisitionSnapshot9("daily"),pids=sheet.branches.flatMap(b=>b.people.map(p=>p.pid)),grams=sheet.branches.reduce((n,b)=>n+b.lots.reduce((n,l)=>n+l.grams,0),0),cash=state.cash;'+buy);assert(r('cash-state.cash===1500+deal.price-deal.cash&&state.debt===sheet.debt&&state.economy6.loans.some(l=>l.remaining===sheet.debt)'));assert(r('deal.branches.every(id=>{const b=sheet.branches.find(b=>b.id===id),s=state.stores.find(s=>s.id===id);return JSON.stringify(s.equipment)===JSON.stringify(b.equipment)&&s.lease.rent===b.lease.rent&&s.lease.due===b.lease.due&&JSON.stringify(s.crew.employees.map(p=>p.pid))===JSON.stringify(b.people.map(p=>p.pid));})'));assert(r('state.batches.filter(b=>b.acquisition9).reduce((n,b)=>n+b.kg*1000,0)===grams&&acquisitionAssets9("daily").branches.length===0'));r('var before=JSON.stringify(state);');assert.throws(()=>r('closeAcquisition9(p.id,close)'));assert.throws(()=>r('acquireRival("daily")'));assert(r('JSON.stringify(state)===before'));r('nextWeek();');assert(r('pids.every(pid=>peopleAll6().some(x=>x.person.pid===pid))'));});
test('The acquisition preflights inherited commitments, storage and stale buyer state before any transfer',r=>{r(company+ready+'var ask=acquisitionSnapshot9("daily").asking,q=acquisitionOfferQuote9(p.id,ask);negotiateAcquisition9(p.id,ask,q);var close=acquisitionCloseQuote9(p.id);state.cash--;var before=JSON.stringify(state);');assert.throws(()=>r('closeAcquisition9(p.id,close)'),/změnily/);assert(r('JSON.stringify(state)===before'));r('state.warehouses.forEach(w=>w.capacity=1);var fill=warehouseCapacity("Praha")-cityStock("Praha");state.cash-=fill*500;state.batches.push({id:"storage-boundary",blend:"blend-1",zone:"Praha",kg:fill,cost:500,quality:70,roastedWeek:state.week,profile:{primary:"brazil",secondary:"colombia",share:75,roast:3}});var before=JSON.stringify(state);');assert.throws(()=>r('acquisitionCloseQuote9(p.id)'),/místo/);assert(r('JSON.stringify(state)===before'));});
test('Integration pays real service and team training, retains stock, and records two actual transition weeks',r=>{r(company+ready+buy+'var data={design:null,blend:deal.blend,repair:true,train:true,reserve:1},before=JSON.stringify(state),q=acquisitionIntegrationQuote9(deal.id,data);');assert(r('JSON.stringify(state)===before&&q.total>q.fee'));r('var cash=state.cash,lots=JSON.stringify(state.batches),pids=deal.snapshot.branches.flatMap(b=>b.people.map(p=>p.pid)),i=startAcquisitionIntegration9(deal.id,data,q);');assert(r('cash-state.cash===q.total&&JSON.stringify(state.batches)===lots&&deal.branches.every(id=>Object.values(state.stores.find(s=>s.id===id).equipment).every(e=>e.condition===100))'));assert.throws(()=>r('startAcquisitionIntegration9(deal.id,data,q)'));r('nextWeek();nextWeek();');assert(r('i.status==="completed"&&i.rows.length===2&&i.rows.every(row=>row.branches.every(b=>b.available))&&pids.every(pid=>peopleAll6().some(x=>x.person.pid===pid))'));});
test('Malformed physical stock, imported identities, timelines, prices and integration outcomes are rejected without mutation',r=>{r(company+ready+buy+'var data={design:null,blend:deal.blend,repair:false,train:false,reserve:1},q=acquisitionIntegrationQuote9(deal.id,data);startAcquisitionIntegration9(deal.id,data,q);nextWeek();var valid=JSON.parse(JSON.stringify(state)),live=JSON.stringify(state);');for(const change of ['x.acquisitions9.deals[0].price++','x.acquisitions9.reviews[0].fee=0','x.acquisitions9.reviews[0].offers[0].accepted=false','x.acquisitions9.deals[0].snapshot.branches[0].lots[0].grams++','x.acquisitions9.deals[0].integration.rows[0].branches[0].available="yes"','x.acquisitions9.deals[0].integration.until++','x.batches.find(b=>b.acquisition9).cost++']){r('var x=JSON.parse(JSON.stringify(valid));'+change+';var input=JSON.stringify(x);');assert.throws(()=>r('validateSave(x)'));assert(r('JSON.stringify(state)===live&&JSON.stringify(x)===input'));}});
test('District demand is applied before physical purchases and consumption through real seasonal weeks',r=>{r(company+'for(let i=0;i<10;i++)nextWeek();'+review+'for(let i=0;i<26;i++){nextWeek();validateSave(JSON.parse(JSON.stringify(state)));for(const rival of state.rivals)for(const h of rival.operations5.history)for(const b of h.branches)if(b.inventory9&&b.inventory9.used!==b.served*18)throw Error("Physical cups differ from final district demand");}');assert(r('state.week===44&&state.acquisitions9.rivals[0].history.length===26'));});
test('A paid integration accepts actual fitout buyback credits without corrupting its saved result',r=>{r(company+ready+buy+'for(const id of deal.branches)for(const key of ["machine","grinder","bar","coldbrew","oven"])buyEquipmentModel5(id,key,"premium");var data={design:studioStarterDesign6(),blend:deal.blend,repair:false,train:false,reserve:1},q=acquisitionIntegrationQuote9(deal.id,data),cash=state.cash;startAcquisitionIntegration9(deal.id,data,q);');assert(r('q.total<q.fee&&Math.abs(cash-state.cash-q.total)<.01'));r('nextWeek();nextWeek();');assert(r('deal.integration.status==="completed"'));});
test('Actual seller insolvency writes off registered assets and releases the same named people once',r=>{r(company+ready+'var rival=state.rivals.find(r=>r.id==="daily"),ids=acquisitionAssets9("daily").branches.flatMap(b=>b.people.map(p=>p.pid));rival.cash=1;nextWeek();var h=rival.operations5.history.at(-1);');assert(r('rival.bankrupt&&rival.stores.length===0&&acquisitionAssets9("daily").branches.length===0&&h.disposal9.cost>0'));assert(r('ids.every(id=>state.baristaCandidates.filter(p=>p.pid===id).length===1)&&Math.abs(h.cashChange-(h.profit-h.investment+h.depreciation-h.principal+h.inventory9.cogs-h.inventory9.purchase+h.inventory9.waste+h.disposal9.cost))<=1'));r('nextWeek()');assert(r('ids.every(id=>state.baristaCandidates.filter(p=>p.pid===id).length===1)'));});
console.log('PASS:',passed,'actual paid acquisition review, physical rival stock, exact transfer and integration cases');
