const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');const c=vm.createContext({Intl,console});for(const f of ['engine','tycoon','empire','operations','reports','supply','crew','craft','studio','business','guests','branding','property','rivals','seasons','procurement','management','bakery'])vm.runInContext(fs.readFileSync('dist/'+f+'.js','utf8'),c);const r=s=>vm.runInContext(s,c),snap=()=>r('JSON.stringify(state)'),near=(a,b)=>assert(Math.abs(a-b)<.03,`${a} != ${b}`);let passed=0;
function test(name,fn){r('state=fresh();bakeryTurn5=null');fn();r('validateSave(JSON.parse(JSON.stringify(state)))');passed++;console.log('PASS:',name);}
function own(){r('openStore("letna");state.cash=6000000;hireCandidate("letna",state.talents[0].pid);buyEquipment("letna","oven");buyEquipment("letna","kitchen");state.stores[0].menu.pastry.enabled=true;state.stores[0].menu.sandwich.enabled=true;state.stores[0].auto.price=false');}
function plan(source='external',extra=''){r(`setFoodPlan5('letna',{...defaultFood5(),enabled:true,source:${source==='external'?'"external"':source},reserve:1,budget:100000,${extra}})`);}
function bakery(){own();r('var b=buyBakery5("atelier","Praha");setBakery5(b.id,{staff:3,shifts:1,budget:100000,reserve:1,auto:true,maintenance:false})');plan('b.id');}
test('founder is neutral with no bakery and five recipes',()=>{assert.equal(r('state.cash'),650000);assert.equal(r('state.stores.length'),0);assert.equal(r('state.bakery5.bakeries.length'),0);assert.equal(r('state.bakery5.recipes.length'),5);const s=snap();assert.throws(()=>r('nextWeek()'));assert.equal(snap(),s);});
test('old v5 save receives neutral metadata without new spend',()=>{own();r('var v=JSON.parse(JSON.stringify(state)),cash=v.cash;delete v.bakery5;delete v.stores[0].food5;v=validateSave(v)');near(r('v.cash'),r('cash'));assert(!r('v.stores[0].food5.enabled'));});
test('legacy food remains available before opting into physical stocks',()=>{own();r('nextWeek()');assert(r('state.stores[0].lastItems.find(i=>i.id==="pastry").count>0'));assert.equal(r('state.bakery5.history[0].revenue'),0);});
test('external fresh lots are purchased, sold and recorded daily',()=>{own();plan();r('nextWeek()');assert(r('state.stores[0].food5.last.sold>0'));assert(r('state.bakery5.history[0].purchases>0'));assert.equal(r('state.stores[0].food5.last.days.length'),6);assert(r('state.stores[0].food5.last.lost>0'));});
test('empty budget creates lost food demand and zero food revenue, cost and phantom menu sales',()=>{own();plan('external','budget:0');r('nextWeek()');assert.equal(r('state.stores[0].food5.last.revenue'),0);assert.equal(r('state.stores[0].food5.last.cost'),0);assert.equal(r('state.stores[0].lastItems.find(i=>i.id==="pastry").count'),0);assert(r('state.stores[0].food5.last.lost>0'));});
test('food purchases respect the weekly cap and fixed-cost reserve',()=>{own();plan('external','budget:500');r('nextWeek()');assert(r('state.bakery5.history[0].purchases<=500'));r('state=fresh()');own();plan();r('state.cash=weeklyFixed()/2;nextWeek()');assert.equal(r('state.bakery5.history[0].purchases'),0);});
test('missing cafe equipment prevents ordering and selling food',()=>{own();plan();r('delete state.stores[0].equipment.oven;delete state.stores[0].equipment.kitchen;nextWeek()');assert.equal(r('state.stores[0].food5.last.sold'),0);assert.equal(r('state.bakery5.history[0].purchases'),0);});
test('no actual coffee service means no food sales, despite delivered food',()=>{own();plan();r('state.batches=[];state.roasters[0].auto=false;nextWeek()');assert.equal(r('state.stores[0].last.served'),0);assert.equal(r('state.stores[0].food5.last.sold'),0);assert(r('state.stores[0].food5.last.wasted>0'));});
test('bakery purchase is exact, requires an existing owned city and has ongoing costs',()=>{own();r('var cash=state.cash,fixed=weeklyFixed();var b=buyBakery5("atelier","Praha")');near(r('state.cash'),r('cash-260000'));near(r('weeklyFixed()-fixed'),24000);const s=snap();assert.throws(()=>r('buyBakery5("atelier","Brno")'));assert.equal(snap(),s);});
test('minority founder needs board mandate and uses its exact investment',()=>{own();r('state.founderShare=25;state.expansionBudget=0');const s=snap();assert.throws(()=>r('buyBakery5("atelier","Praha")'));assert.equal(snap(),s);r('state.expansionBudget=260000;buyBakery5("atelier","Praha")');assert.equal(r('state.expansionBudget'),0);});
test('owned daily manufacture consumes raw lots and delivers physical food once',()=>{bakery();r('nextWeek()');assert(r('b.last.produced>0&&b.last.delivered>0&&b.last.sold>0'));near(r('b.last.revenue'),r('state.stores[0].food5.last.revenue'));near(r('b.last.cogs'),r('state.stores[0].food5.last.cost'));near(r('b.last.profit'),r('b.last.revenue-b.last.cogs-b.last.operating-b.last.waste'));});
test('capacity, labour and shifts constrain actual production',()=>{bakery();r('setBakery5(b.id,{staff:1,shifts:1,budget:200000,reserve:1,auto:true,maintenance:false});state.stores[0].food5.plan.pastry.qty=500;state.stores[0].food5.plan.sandwich.qty=500;nextWeek()');assert(r('b.last.work<=b.last.capacity+.01'));assert(r('b.last.produced<6000'));});
test('no automatic raw buying requires physical ingredients, and zero stock produces nothing',()=>{bakery();r('b.auto=false;nextWeek()');assert.equal(r('b.last.produced'),0);assert.equal(r('state.stores[0].food5.last.sold'),0);near(r('b.last.operating'),24000);});
test('manual raw purchase prepays stock, increases inventory value and carries real expiry',()=>{bakery();r('var cash=state.cash,value=companyValue();buyFoodRaw5(b.id,"butter",10)');near(r('cash-state.cash'),1800);near(r('companyValue()'),r('value'));assert.equal(r('b.raw[0].expires-b.raw[0].arrived'),10);});
test('raw FIFO consumption uses earliest expiry and cost, with no negative inventory',()=>{bakery();r('b.auto=false;state.stores[0].food5.plan.sandwich.qty=0;state.stores[0].food5.plan.pastry.qty=5;for(const k of ["flour","butter","sugar","dairy"])buyFoodRaw5(b.id,k,10);b.raw.find(l=>l.ingredient==="flour").kg=.1;buyFoodRaw5(b.id,"flour",10);nextWeek()');assert(r('b.last.produced>0'));assert(r('b.raw.every(l=>l.kg>=0)'));assert.equal(r('b.raw.filter(l=>l.ingredient==="flour").length'),1);});
test('perishable raw stock expires in the same ledger as the company result',()=>{bakery();r('b.auto=false;state.stores[0].food5.plan.pastry.qty=0;state.stores[0].food5.plan.sandwich.qty=0;buyFoodRaw5(b.id,"vegetables",10);nextWeek()');near(r('b.last.waste'),850);near(r('state.bakery5.history[0].waste'),850);assert(r('state.history[0].spoil>=850'));assert.equal(r('b.raw.length'),0);});
test('food is not paid twice when consumed; cash oracle reconciles a funded simple turn',()=>{own();plan();r('state.policy3.autoCrises=false;var before=state.cash;var h=nextWeek(),f=state.bakery5.history.at(-1)');assert(Math.abs(r('state.cash-(before+h.revenue-h.expenses-h.interest-h.productionSpend-f.purchases+f.consumed)'))<2);});
test('internal manufacturing does not add duplicate revenue and food cash COGS reconcile',()=>{bakery();r('state.policy3.autoCrises=false;var before=state.cash;var h=nextWeek(),f=state.bakery5.history.at(-1)');assert(Math.abs(r('state.cash-(before+h.revenue-h.expenses-h.interest-h.productionSpend-f.purchases+f.consumed)'))<2);near(r('h.revenue'),r('state.stores[0].last.revenue+h.wholesale+h.online+h.franchise'));});
test('daily timelines match actual coffee and food revenue and sold counts',()=>{bakery();r('nextWeek()');assert.equal(r('round(state.stores[0].daily.last.days.reduce((n,d)=>n+d.revenue,0))'),r('state.stores[0].last.retailSales'));assert.equal(r('state.stores[0].daily.last.days.reduce((n,d)=>n+d.served,0)'),r('state.stores[0].last.served'));assert.equal(r('state.stores[0].lastItems.filter(i=>MENU[i.id].food).reduce((n,i)=>n+i.count,0)'),r('b.last.sold'));});
test('price and recipe quality affect food interest without state changes in queries',()=>{own();r('var s=state.stores[0],rec=foodRecipe5("food-croissant"),normal=foodRate5(s,"pastry",rec);s.menu.pastry.price=300;var high=foodRate5(s,"pastry",rec)');assert(r('high<normal'));const s=snap();r('foodRecipe5("food-brownie");foodStock5(state.stores[0])');assert.equal(snap(),s);});
test('rich recipes require more ingredients and work, with more quality',()=>{r('var a=foodRecipe5("food-brownie");saveFoodRecipe5("food-brownie",{name:"Moje brownie",base:"brownie",richness:140});var z=foodRecipe5("food-brownie")');assert(r('z.unitCost>a.unitCost&&z.work>a.work&&z.quality>a.quality'));assert.equal(r('z.version'),2);});
test('new recipes and edits preserve immutable delivered lot snapshots',()=>{own();plan('external','plan:{pastry:{recipe:"food-brownie",qty:50},sandwich:{recipe:"food-sandwich",qty:0}}');r('nextWeek();var oldLots=JSON.stringify(state.stores[0].food5.lots);saveFoodRecipe5("food-brownie",{name:"Nové brownie",base:"brownie",richness:140})');assert.equal(r('JSON.stringify(state.stores[0].food5.lots)'),r('oldLots'));assert(r('state.stores[0].food5.lots.length>0'));});
test('owned recipe category cannot invalidate active cafe plans',()=>{own();const s=snap();assert.throws(()=>r('saveFoodRecipe5("food-croissant",{name:"X",base:"sandwich",richness:100})'));assert.equal(snap(),s);});
test('cross-city delivery takes a day and cannot ship one-day food',()=>{bakery();r('state.stores.push(makeStore("brno"));var s=state.stores.at(-1);buyEquipment(s.id,"oven");s.menu.pastry.enabled=true;setFoodPlan5(s.id,{...defaultFood5(),enabled:true,source:b.id,reserve:1});nextWeek()');assert.equal(r('s.food5.last.sold'),0);r('s.food5.plan.pastry.recipe="food-brownie";nextWeek()');assert.equal(r('s.food5.last.days[0].sold'),0);assert(r('s.food5.last.days.slice(1).some(d=>d.sold>0)'));assert(r('s.food5.lots.every(l=>l.arrival-l.made===1)'));});
test('manager recruitment, wage and product skills belong to the bakery and careers',()=>{bakery();r('var cash=state.cash,cap=bakeryCapacity5(b),fixed=weeklyFixed();hireCandidate(b.id,state.talents[0].pid,"bakery");var salary=b.manager.salary');near(r('cash-state.cash'),12000);near(r('weeklyFixed()-fixed'),r('salary'));assert(r('bakeryCapacity5(b)>cap'));r('nextWeek()');assert(r('b.manager.tenure>=1'));assert(r('state.performance5[0].records.some(x=>x.kind==="people"&&x.id===b.manager.pid&&x.scope.includes("pekárny"))'));});
test('staff recruitment charges only additions and invalid changes preserve state',()=>{bakery();r('var cash=state.cash;setBakery5(b.id,{staff:4,shifts:2,budget:100000,reserve:1,auto:true,maintenance:false})');near(r('cash-state.cash'),8000);const s=snap();assert.throws(()=>r('setBakery5(b.id,{staff:0,shifts:2,budget:100000,reserve:1,auto:true,maintenance:false})'));assert.equal(snap(),s);});
test('manual service prepays once and records a single real company expense',()=>{bakery();r('b.condition=50;var cash=state.cash;serviceBakery5(b.id);nextWeek()');assert(r('b.condition>99'));assert(r('state.history[0].detail.crises>=10400'));near(r('b.last.operating'),24000);});
test('automatic maintenance respects the same reserve and budget, without double payment',()=>{bakery();r('b.condition=60;b.maintenance=true;state.stores[0].food5.plan.pastry.qty=0;state.stores[0].food5.plan.sandwich.qty=0;state.policy3.autoCrises=false;var before=state.cash,h=nextWeek(),f=state.bakery5.history.at(-1)');assert(r('b.condition===100'));near(r('b.last.operating'),34400);assert(Math.abs(r('state.cash-(before+h.revenue-h.expenses-h.interest-h.productionSpend-f.purchases+f.consumed+10400)'))<2);});
test('read-only forecast restores company and random state and matches actual future',()=>{bakery();const s=snap();r('var f=bakeryForecast5(4)');assert.equal(snap(),s);r('var profit=0;for(let i=0;i<4;i++)profit+=nextWeek().profit');near(r('f.cash'),r('state.cash'));near(r('f.profit'),r('profit'));assert.equal(r('bakeryTurn5'),null);});
test('reports and board goals record final food-inclusive ledger without later mutation',()=>{bakery();r('nextWeek()');near(r('state.management5.history[0].values.profit'),r('state.history[0].profit'));near(r('performanceReport5("firms",1).rows.find(x=>x.id==="player").values.profit'),r('state.history[0].profit'));near(r('performanceReport5("bakeries",1).rows[0].values.profit'),r('b.last.profit'));near(r('performanceReport5("food",1).rows[0].values.revenue'),r('state.stores[0].food5.last.revenue'));const s=snap();r('performanceReport5("food",4);performanceReport5("bakeries",13)');assert.equal(snap(),s);});
test('invalid source, category, quantities and recipes are atomic rejections',()=>{bakery();for(const code of ['setFoodPlan5("letna",{...defaultFood5(),enabled:true,source:"missing"})','setFoodPlan5("letna",{...defaultFood5(),enabled:true,plan:{pastry:{recipe:"food-sandwich",qty:5},sandwich:{recipe:"food-sandwich",qty:5}}})','buyFoodRaw5(b.id,"butter",-3)','saveFoodRecipe5(null,{name:" ",base:"brownie",richness:100})']){const s=snap();assert.throws(()=>r(code));assert.equal(snap(),s);}});
test('public setters cannot overwrite lot history or entity identity via extra fields',()=>{bakery();r('var id=b.id;setBakery5(b.id,{staff:3,shifts:1,budget:100000,reserve:1,auto:true,maintenance:false,id:"bad"});setFoodPlan5("letna",{...defaultFood5(),enabled:true,source:b.id,lots:[{bad:1}]})');assert.equal(r('b.id'),r('id'));assert.equal(r('state.stores[0].food5.lots.length'),0);});
test('malformed imports reject forged lots, totals, duplicate identities and recipes',()=>{bakery();r('state.stores[0].food5.plan.pastry={recipe:"food-brownie",qty:500};nextWeek();hireCandidate(b.id,state.talents[0].pid,"bakery")');for(const code of ['v.bakery5.recipes[0].richness=NaN','v.stores[0].food5.plan.pastry.recipe="missing"','v.stores[0].food5.last.sold++','v.bakery5.bakeries[0].last.profit++','v.bakery5.bakeries[0].manager.pid=v.stores[0].manager.pid','v.stores[0].food5.lots[0].cost=-1','v.stores[0].food5.lots[0].expires=v.stores[0].food5.lots[0].made']){r('var v=JSON.parse(JSON.stringify(state))');r(code);assert.throws(()=>r('validateSave(v)'));}});
test('zero orders do not manufacture phantom goods and still pay the bakery team',()=>{bakery();r('state.stores[0].food5.plan.pastry.qty=0;state.stores[0].food5.plan.sandwich.qty=0;nextWeek()');assert.equal(r('b.last.produced'),0);assert.equal(r('b.last.profit'),-24000);});
test('50 physical bakery weeks retain bounded lots, history, finite ledgers and valid saves',()=>{bakery();r('state.cash=15000000;state.stores[0].food5.plan.pastry={recipe:"food-brownie",qty:100};state.stores[0].food5.plan.sandwich.qty=70');for(let i=0;i<50;i++){r('nextWeek();validateSave(JSON.parse(JSON.stringify(state)))');assert(r('Number.isFinite(state.cash)&&b.raw.length<=200&&state.stores[0].food5.lots.length<=200'));}assert.equal(r('b.history.length'),26);assert.equal(r('state.bakery5.history.length'),26);assert.equal(r('state.stores[0].food5.history.length'),26);});
test('111 managed cafes and eight managed bakeries/roasters retain all report rows within bounds',()=>{r('state.cash=250000000;state.stores=LOCATIONS.map(l=>makeStore(l.id));state.studio5.opening=false;state.rivals.forEach(r=>{r.bankrupt=true;r.stores=[]});for(const s of state.stores){hire(s.id,0);buyEquipment(s.id,"oven");s.menu.pastry.enabled=true;setFoodPlan5(s.id,{...defaultFood5(),enabled:true,reserve:1});}while(state.roasters.length<8)buyRoaster("artisan","Výroba "+state.roasters.length);for(const ro of state.roasters)hire(ro.id,0,"roaster");for(let i=0;i<8;i++){const b=buyBakery5("atelier",CITIES[i].name);hire(b.id,0,"bakery");}for(let i=0;i<8;i++){const b=state.bakery5.bakeries[i];for(const s of state.stores.filter(s=>loc(s.id).city===b.city))s.food5.source=b.id;}nextWeek()');assert.equal(r('performanceReport5("food",1).rows.length'),111);assert.equal(r('performanceReport5("bakeries",1).rows.length'),8);assert(r('state.performance5[0].records.length<=800&&state.performance5[0].records.length>600'));});
test('60 actual founder weeks with external fresh food survive without added capital',()=>{r('openStore("letna");hireCandidate("letna","candidate-0");buyEquipment("letna","oven");state.stores[0].menu.pastry.enabled=true;setFoodPlan5("letna",{...defaultFood5(),enabled:true,budget:8000,reserve:2,plan:{pastry:{recipe:"food-croissant",qty:35},sandwich:{recipe:"food-sandwich",qty:0}}})');for(let i=0;i<60;i++){r('if(state.roasters[0].condition<65&&state.cash>weeklyFixed()*3+18000)maintainRoaster("roaster-1");nextWeek();validateSave(JSON.parse(JSON.stringify(state)))');assert(!r('state.over'));}assert(r('state.stores[0].food5.history.every(h=>h.sold>0)'));});
console.log(`${passed} bakery scenarios passed.`);
