const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
const c=vm.createContext({Intl,console});for(const f of ['engine','tycoon','empire','operations','reports','supply','crew','craft','studio','business','guests','branding'])vm.runInContext(fs.readFileSync('dist/'+f+'.js','utf8'),c);const r=s=>vm.runInContext(s,c),snap=()=>r('JSON.stringify(state)'),near=(a,b)=>assert(Math.abs(a-b)<.02,`${a} != ${b}`);let passed=0;
function own(){r('openStore("letna");state.cash=5000000;hireCandidate("letna","candidate-0")')}
function identity(position='original'){r(`var data={...brandingIdentityData5(state.brands[0]),position:${JSON.stringify(position)}};commitBrandIdentity5("brand-1",data)`)}
function campaign(){r('var dataC={brand:"brand-1",target:"community",channel:"local",city:"Praha",weekly:3000,weeks:4};var campaign=startBrandCampaign5(dataC)')}
function test(name,fn){r('state=fresh()');fn();r('validateSave(JSON.parse(JSON.stringify(state)))');passed++;console.log('PASS:',name)}
test('new founder keeps 650k and no invented identity, campaigns or brand history',()=>{assert.equal(r('state.cash'),650000);assert.equal(r('state.stores.length'),0);assert.equal(r('state.brands[0].identity5.enabled'),false);assert.equal(r('state.branding5.history.length'),0);const s=snap();assert.throws(()=>r('nextWeek()'));assert.equal(snap(),s);});
test('identity quote is pure and includes only owned signage plus design and concept',()=>{own();r('state.reputation=70;openStore("vinohrady","brand-1","blend-1",true);var d={...brandingIdentityData5(state.brands[0]),concept:"specialty"}');const s=snap(),q=r('brandIdentityQuote5("brand-1",d)');assert.equal(snap(),s);assert.equal(q.stores.length,1);assert.equal(q.signs,1500);assert.equal(q.design,2500);assert.equal(q.concept,r('round(CONCEPTS.specialty.cost*.5)'));});
test('identity commits exact cash once and unchanged draft is free',()=>{own();const cash=r('state.cash');identity();near(r('state.cash'),cash-4000);assert.equal(r('state.pendingExpense3'),4000);r('commitBrandIdentity5("brand-1",brandingIdentityData5(state.brands[0]))');near(r('state.cash'),cash-4000);});
test('stale quote and invalid identity reject without partial edits',()=>{own();r('var d=brandingIdentityData5(state.brands[0]),q=brandIdentityQuote5("brand-1",d);state.cash-=1');const s=snap();assert.throws(()=>r('commitBrandIdentity5("brand-1",d,q)'));assert.equal(snap(),s);assert.throws(()=>r('commitBrandIdentity5("brand-1",{...d,color:"invalid"})'));assert.equal(snap(),s);});
test('visual changes leave demand, price and coffee promise neutral',()=>{own();identity();assert.equal(r('brandingGuestFactors5(state.stores[0],"office").demand'),1);assert.equal(r('brandingGuestFactors5(state.stores[0],"office").price'),1);assert.equal(r('brandingExpectation5(state.stores[0],"specialty",35,30)'),0);});
test('premium and quick positioning use different price expectations and actual promises',()=>{own();identity('premium');assert.equal(r('brandingGuestFactors5(state.stores[0],"specialty").price'),1.08);assert(r('brandingExpectation5(state.stores[0],"specialty",55,2)>0'));assert.equal(r('brandingExpectation5(state.stores[0],"specialty",90,2)'),0);r('commitBrandIdentity5("brand-1",{...brandingIdentityData5(state.brands[0]),position:"quick"})');assert(r('brandingExpectation5(state.stores[0],"office",80,20)>0'));});
test('unfulfilled promise reaches real customer experience without changing physical coffee',()=>{own();identity('premium');r('state.batches=[{blend:"blend-1",kg:200,quality:35,cost:300,zone:"Praha",roastedWeek:state.week}];state.roasters.forEach(r=>r.auto=false);nextWeek()');assert(r('state.stores[0].guests5.last.groups.every(g=>g.quality===35)'));assert(r('state.stores[0].guests5.last.groups.find(g=>g.id==="specialty").brandPenalty===8'));});
test('campaign setup is paid once and weekly charges end after four funded turns',()=>{own();identity();const cash=r('state.cash');campaign();near(r('state.cash'),cash-1200);r('for(let i=0;i<4;i++)nextWeek()');assert.equal(r('campaign.status'),'done');assert.equal(r('campaign.spent'),12000);assert.equal(r('campaign.remaining'),0);r('nextWeek()');assert.equal(r('state.branding5.last.brands[0].campaignCost'),0);});
test('campaign reserve blocks spending, demand boost and duration consumption',()=>{own();identity();campaign();r('state.cash=weeklyFixed()*2;var savedCash=state.cash;brandingTurn5={campaigns:[],expenses:[],products:[]};runBrandCampaigns5();var boost=brandingGuestFactors5(state.stores[0],"community");brandingTurn5=null');near(r('state.cash'),r('savedCash'));assert.equal(r('campaign.remaining'),4);assert.equal(r('campaign.spent'),0);assert.equal(r('boost.demand'),1);assert(r('campaign.last.reason.includes("rezervu")'));r('campaign.last=null');});
test('funded campaign only attracts its target and its city',()=>{own();identity();r('openStore("karlin");openStore("vinohrady");state.reputation=70;state.rivals.forEach(r=>r.stores=[]);openStore("brnostred");brandingTurn5={campaigns:[{brand:"brand-1",target:"community",city:"Praha",boost:.1}],expenses:[],products:[]};var a=brandingGuestFactors5(state.stores[0],"community"),b=brandingGuestFactors5(state.stores[0],"office"),d=brandingGuestFactors5(state.stores[3],"community");brandingTurn5=null');assert.equal(r('a.demand'),1.1);assert.equal(r('b.demand'),1);assert.equal(r('d.demand'),1);});
test('held campaign resumes when the reserve permits actual payment',()=>{own();identity();campaign();r('state.cash=weeklyFixed()*2;nextWeek()');assert.equal(r('campaign.spent'),0);assert.equal(r('campaign.remaining'),4);r('state.cash=5000000;nextWeek()');assert.equal(r('campaign.spent'),3000);assert.equal(r('campaign.remaining'),3);});
test('pause and cancel prevent future weekly expense',()=>{own();identity();campaign();r('setBrandCampaignStatus5(campaign.id,"paused");nextWeek()');assert.equal(r('campaign.spent'),0);r('setBrandCampaignStatus5(campaign.id,"active");nextWeek();setBrandCampaignStatus5(campaign.id,"cancelled");nextWeek()');assert.equal(r('campaign.spent'),3000);assert.equal(r('campaign.status'),'cancelled');});
test('a fifth active or paused campaign is rejected atomically',()=>{own();identity();r('var d={brand:"brand-1",target:"community",channel:"local",city:"all",weekly:3000,weeks:4};for(let i=0;i<4;i++)startBrandCampaign5(d)');const s=snap();assert.throws(()=>r('startBrandCampaign5(d)'));assert.equal(snap(),s);});
test('campaign cannot start for a brand with no target-city store',()=>{own();identity();const s=snap();assert.throws(()=>r('startBrandCampaign5({brand:"brand-1",target:"student",channel:"social",city:"Brno",weekly:3000,weeks:4})'));assert.equal(snap(),s);});
test('awareness derives from actual paid guest delivery and decays without campaigns',()=>{own();identity();campaign();r('nextWeek();var awareness=state.brands[0].identity5.awareness.community');assert(r('awareness>0'));assert.equal(r('state.brands[0].identity5.awareness.office'),0);r('setBrandCampaignStatus5(campaign.id,"paused");nextWeek()');near(r('state.brands[0].identity5.awareness.community'),r('awareness*.98'));});
test('two forecast variants preserve the entire game and match actual campaign execution',()=>{own();identity();r('var d={brand:"brand-1",target:"community",channel:"local",city:"Praha",weekly:3000,weeks:4}');const s=snap(),f=r('previewBrandCampaign5(d,4)');assert.equal(snap(),s);const again=r('previewBrandCampaign5(d,4)');assert.equal(JSON.stringify(f),JSON.stringify(again));r('startBrandCampaign5(d);for(let i=0;i<4;i++)nextWeek()');near(r('state.cash'),f.campaign.series.at(-1).cash);assert.equal(r('state.branding5.last.brands[0].served'),f.campaign.series.at(-1).served);});
test('baseline forecast matches actual firm without the new campaign',()=>{own();identity();r('var d={brand:"brand-1",target:"community",channel:"local",city:"Praha",weekly:3000,weeks:4}');const f=r('previewBrandCampaign5(d,4)');r('for(let i=0;i<4;i++)nextWeek()');near(r('state.cash'),f.baseline.series.at(-1).cash);});
test('label design does not change physical stock, costs or recipe and same design is free',()=>{own();const stock=r('JSON.stringify(state.batches)'),recipe=r('JSON.stringify(recipe(state.blends[0]))'),cash=r('state.cash');r('var d={brand:"brand-1",name:"Vlastní edice",style:"kraft",story:"Naše káva",packaging:"eco"};commitCoffeeLabel5("blend-1",d);commitCoffeeLabel5("blend-1",d)');near(r('state.cash'),cash-1500);assert.equal(r('JSON.stringify(state.batches)'),stock);assert.equal(r('JSON.stringify(recipe(state.blends[0]))'),recipe);assert.equal(r('brandingPrintCost5(state.blends[0])'),4);});
test('e-shop product report accounts for actual coffee, printing, packing and handling',()=>{own();r('buyOffice("studio");setDepartment("it",1);state.projects.eshop.done=true;commitCoffeeLabel5("blend-1",{brand:"brand-1",name:"Signature",style:"dark",story:"",packaging:"eco"});nextWeek()');assert(r('state.branding5.last.products[0].kg>0'));near(r('state.branding5.last.products[0].packing'),r('state.branding5.last.products[0].kg*36'));assert.equal(r('round(state.branding5.last.products[0].revenue)'),r('state.history.at(-1).online'));near(r('state.branding5.last.products[0].contribution'),r('state.branding5.last.products[0].revenue-state.branding5.last.products[0].coffee-state.branding5.last.products[0].packing-state.branding5.last.products[0].handling'));});
test('printing cost is based on delivered B2B kilograms and offer includes it',()=>{own();r('buyOffice("studio");setDepartment("sales",1);state.reputation=90;commitCoffeeLabel5("blend-1",{brand:"brand-1",name:"Firma",style:"cream",story:"",packaging:"classic"});var d={blend:"blend-1",kg:10,price:500,weeks:12,terms:2},q=businessOffer5("hub",d),p=negotiateBusiness5("hub",d);acceptBusiness5(p.id);nextWeek()');assert.equal(r('q.printing'),4);near(r('q.margin'),r('q.counter*(1-clamp((q.minQuality-q.quality)*.012,0,.25))-q.unit-q.shipping-4'));near(r('state.business5.last.deliveries[0].shipping'),r('state.business5.last.deliveries[0].delivered*19'));});
test('brand report uses franchise royalties rather than inventing franchise turnover',()=>{own();r('state.reputation=70;openStore("vinohrady","brand-1","blend-1",true);nextWeek()');near(r('state.branding5.last.brands[0].revenue'),r('state.stores.reduce((n,s)=>n+s.last.revenue,0)'));assert.equal(r('performanceReport5("brands",1).rows.length'),1);assert.equal(r('performanceReport5("products",1).rows.length'),1);});
test('historical product label stays frozen after later rebranding and label change',()=>{own();r('nextWeek();var archived=JSON.stringify(state.branding5.history[0]);commitBrandIdentity5("brand-1",{...brandingIdentityData5(state.brands[0]),name:"Nové jméno"});commitCoffeeLabel5("blend-1",{brand:"brand-1",name:"Nová etiketa",style:"dark",story:"Nový příběh",packaging:"premium"});nextWeek()');assert.equal(r('JSON.stringify(state.branding5.history[0])'),r('archived'));});
test('paid rebranding preserves customer cohorts and refuses stale quote',()=>{own();r('nextWeek();var b=createBrand("Druhá","express","#264b3b"),guests=JSON.stringify(state.stores[0].guests5),cash=state.cash,q=brandingRebrandQuote5("letna",b.id);rebrandStore5("letna",b.id,q)');near(r('state.cash'),r('cash-8000'));assert.equal(r('JSON.stringify(state.stores[0].guests5)'),r('guests'));const s=snap();assert.throws(()=>r('rebrandStore5("letna",b.id,q)'));assert.equal(snap(),s);});
test('legacy 05.7 save migrates unchanged money with empty branding history',()=>{own();r('nextWeek();var v=JSON.parse(JSON.stringify(state)),cash=v.cash;delete v.branding5;v.brands.forEach(b=>delete b.identity5);v.blends.forEach(b=>delete b.label5);v.performance5.forEach(h=>h.records=h.records.filter(r=>!["brands","products"].includes(r.kind)));v=validateSave(v)');near(r('v.cash'),r('cash'));assert.equal(r('v.branding5.history.length'),0);assert.equal(r('v.brands[0].identity5.enabled'),false);});
test('malformed identities, labels, campaigns and historical financial identities are rejected',()=>{own();identity();campaign();r('nextWeek()');for(const mutation of ['v.brands[0].identity5.awareness.community=101','v.brands[0].identity5.monogram="<"','v.blends[0].label5.brand="missing"','v.branding5.campaigns[0].spent+=1','v.branding5.campaigns[0].remaining=-1','v.branding5.history[0].products[0].contribution+=10','v.branding5.last.brands[0].served=v.branding5.last.brands[0].arrivals+1','v.stores[0].guests5.last.groups[0].brandPenalty=99'])assert.throws(()=>r(`var v=JSON.parse(JSON.stringify(state));${mutation};validateSave(v)`));});
test('repeated paid identity edits aggregate expenses into bounded per-brand entries',()=>{own();for(let i=0;i<105;i++)r(`commitBrandIdentity5("brand-1",{...brandingIdentityData5(state.brands[0]),tagline:"Návrh ${i}"})`);assert.equal(r('state.branding5.pending.length'),1);assert.equal(r('state.branding5.pending[0].cost'),105*4000);});
test('60 founder weeks with opted-in local branding remain saveable without injected money',()=>{r('openStore("letna");hireCandidate("letna","candidate-0")');identity('local');r('commitCoffeeLabel5("blend-1",{brand:"brand-1",name:"Sousedská",style:"kraft",story:"",packaging:"classic"});startBrandCampaign5({brand:"brand-1",target:"community",channel:"local",city:"Praha",weekly:1500,weeks:4})');for(let i=0;i<60;i++){r('if(state.roasters[0].condition<65&&state.cash>weeklyFixed()*3+18000)maintainRoaster("roaster-1");nextWeek();validateSave(JSON.parse(JSON.stringify(state)))');assert(!r('state.over'));}assert.equal(r('state.branding5.history.length'),26);assert(r('state.cash>100000'));});
test('weekly ledger separates identity and campaigns without double-counted profit or cash',()=>{own();identity();campaign();r('var cash=state.cash,h=nextWeek(),row=state.branding5.last.brands[0]');assert.equal(r('h.detail.brandIdentity'),5200);assert.equal(r('h.detail.brandCampaigns'),3000);near(r('row.sharedCost'),5200);near(r('row.profit'),r('state.stores[0].last.profit-5200-3000'));assert.equal(r('h.profit'),r('round(h.revenue-h.expenses-h.cogs-h.interest-h.spoil)'));assert.equal(r('h.cashChange'),r('round(state.cash-cash)'));});
test('empty stock cannot produce custom-labelled e-shop sales',()=>{own();r('buyOffice("studio");setDepartment("it",1);state.projects.eshop.done=true;commitCoffeeLabel5("blend-1",{brand:"brand-1",name:"Bez zásoby",style:"dark",story:"",packaging:"premium"});state.batches=[];state.roasters.forEach(r=>r.auto=false);nextWeek()');assert.equal(r('state.branding5.last.products[0].kg'),0);assert.equal(r('state.branding5.last.products[0].packing'),0);assert.equal(r('state.branding5.last.products[0].revenue'),0);});
test('maximum 111-cafe network retains all branding and guest report records in a valid save',()=>{r('state.cash=200000000;state.stores=LOCATIONS.map(l=>makeStore(l.id));state.studio5.opening=false;state.rivals.forEach(r=>{r.bankrupt=true;r.stores=[]});for(const s of state.stores)hire(s.id,0);while(state.roasters.length<8)buyRoaster("artisan","Výroba "+state.roasters.length);for(const q of state.roasters)hire(q.id,0,"roaster");nextWeek()');assert.equal(r('performanceReport5("guests",1).rows.length'),111);assert.equal(r('performanceReport5("brands",1).rows.length'),1);assert(r('state.performance5.at(-1).records.length>350&&state.performance5.at(-1).records.length<=600'));});
console.log(`${passed} branding scenarios passed.`);
