const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
const c=vm.createContext({Intl,console});for(const f of ['engine','tycoon','empire','operations','reports','supply','crew','craft','studio','business'])vm.runInContext(fs.readFileSync('dist/'+f+'.js','utf8'),c);
const r=s=>vm.runInContext(s,c),snap=()=>r('JSON.stringify(state)'),near=(a,b)=>assert(Math.abs(a-b)<.02,`${a} != ${b}`);let passed=0;
function own(){r('openStore("karlin");state.cash=4000000;buyOffice("studio");setDepartment("sales",3);state.reputation=90;state.roasters[0].shifts=2;state.roasters[0].staff=4')}
function sign(terms=0,client='hub',kg=10){r(`var offer=negotiateBusiness5('${client}',{blend:'blend-1',kg:${kg},price:500,weeks:12,terms:${terms}});var signed=acceptBusiness5(offer.id)`)}
function test(name,fn){r('state=fresh()');fn();r('validateSave(JSON.parse(JSON.stringify(state)))');passed++;console.log('PASS:',name)}
test('fresh business has ten fictional clients and disabled automatic signing',()=>{assert.equal(r('state.business5.accounts.length'),10);assert(!r('state.business5.policy.enabled'));const s=snap();assert.throws(()=>r('nextWeek()'));assert.equal(snap(),s);});
test('unfunded or unopened negotiations are atomic',()=>{const s=snap();assert.throws(()=>sign());assert.equal(snap(),s);own();r('state.cash=1000');const t=snap();assert.throws(()=>sign());assert.equal(snap(),t);});
test('offer quote is pure and stale quotes cannot spend money',()=>{own();const s=snap();r('var data={blend:"blend-1",kg:10,price:1200,weeks:26,terms:4};var quote=businessOffer5("hub",data)');assert.equal(snap(),s);assert(r('quote.counter<1200'));r('state.reputation=80');const t=snap();assert.throws(()=>r('negotiateBusiness5("hub",data,quote)'));assert.equal(snap(),t);});
test('negotiation charges once and gives an explicit counteroffer',()=>{own();const cash=r('state.cash');r('var p=negotiateBusiness5("hub",{blend:"blend-1",kg:10,price:1200,weeks:12,terms:0})');near(r('state.cash'),cash-1500);assert(r('p.price<p.asked'));const s=snap();assert.throws(()=>r('negotiateBusiness5("hub",p)'));assert.equal(snap(),s);});
test('signing costs 5000, uses one slot and preserves agreed terms',()=>{own();const cash=r('state.cash');sign(2);near(r('state.cash'),cash-6500);assert.equal(r('state.contracts.length'),1);assert.equal(r('signed.business5.terms'),2);assert.equal(r('businessSlots5()'),2);const s=snap();assert.throws(()=>r('acceptBusiness5(offer.id)'));assert.equal(snap(),s);});
test('signing rejects a stale cash or capacity confirmation',()=>{own();r('var p=negotiateBusiness5("hub",{blend:"blend-1",kg:10,price:500,weeks:12,terms:0});var q=businessAcceptance5(p.id);state.cash-=1');const s=snap();assert.throws(()=>r('acceptBusiness5(p.id,q)'));assert.equal(snap(),s);});
test('expired offers cannot sign and disappear after a turn',()=>{own();r('var p=negotiateBusiness5("hub",{blend:"blend-1",kg:10,price:500,weeks:12,terms:0});for(let i=0;i<3;i++)nextWeek()');assert.throws(()=>r('acceptBusiness5(p.id)'));r('nextWeek()');assert.equal(r('state.business5.proposals.length'),0);});
test('actual deliveries charge stock cost, freight and quality discount',()=>{own();sign();r('nextWeek();var d=state.business5.last.deliveries[0]');near(r('d.delivered'),10);near(r('d.shipping'),150);near(r('d.contribution'),r('d.revenue-d.coffee-d.shipping-d.penalty'));near(r('state.contracts[0].last.contribution'),r('d.contribution'));assert.equal(r('performanceReport5("trade",1).rows.length'),1);});
test('deferred revenue is identical to cash contracts and outstanding invoices explain cash gap',()=>{own();sign(2);const start=snap();r('nextWeek()');const deferred=r('JSON.stringify({cash:state.cash,profit:state.history.at(-1).profit,invoice:state.business5.invoices[0]})');r(`state=JSON.parse(${JSON.stringify(start)});state.contracts[0].business5.terms=0;nextWeek()`);const d=JSON.parse(deferred);near(r('state.history.at(-1).profit'),d.profit);near(r('state.cash')-d.cash,d.invoice.amount);r(`state=JSON.parse(${JSON.stringify(start)});nextWeek();nextWeek();nextWeek()`);assert.equal(r('state.business5.payments.length'),1);assert.equal(r('state.business5.payments[0].paid'),3);near(r('state.business5.last.collected'),d.invoice.amount);});
test('four-week credit invoices survive seller cancellation and collect exactly once',()=>{own();sign(4);r('nextWeek();var amount=state.business5.invoices[0].amount;cancelBusiness5(signed.id);for(let i=0;i<5;i++)nextWeek()');assert.equal(r('state.business5.invoices.length'),0);assert.equal(r('state.business5.payments.length'),1);near(r('state.business5.payments[0].amount'),r('amount'));assert.equal(r('state.business5.payments[0].paid'),5);});
test('contract previews reproduce actual simulation and restore all state',()=>{own();r('var p=negotiateBusiness5("hub",{blend:"blend-1",kg:10,price:500,weeks:12,terms:2})');const before=snap();const f=r('previewBusiness5(p.id,4)');assert.equal(snap(),before);r('acceptBusiness5(p.id);for(let i=0;i<4;i++)nextWeek()');near(r('state.cash'),f.series.at(-1).cash);near(r('state.history.at(-1).profit'),f.series.at(-1).profit);});
test('preview exceptions restore state without signing',()=>{own();const before=snap();assert.throws(()=>r('previewBusiness5("missing",4)'));assert.equal(snap(),before);});
test('three short deliveries lose a client and produce the true missing-volume penalties',()=>{own();sign();r('state.batches=[];state.roasters.forEach(r=>r.auto=false);for(let i=0;i<3;i++)nextWeek()');assert.equal(r('state.contracts.length'),0);assert.equal(r('businessAccount5("hub").status'),'lost');near(r('businessAccount5("hub").history[0].penalty'),750);assert.equal(r('businessAccount5("hub").history[0].delivered'),0);});
test('poor quality reduces realised revenue at most 25 percent',()=>{own();sign(0,'central',25);r('state.batches=[{blend:"blend-1",kg:200,quality:50,cost:300,zone:"Praha",roastedWeek:state.week}];state.roasters.forEach(r=>r.auto=false);nextWeek();var d=state.business5.last.deliveries[0]');near(r('d.discount'),.25);near(r('d.revenue'),9375);});
test('multiple clients consume shared stock in order and cannot sell phantom coffee',()=>{own();sign();sign(0,'bistro',8);r('state.batches=[{blend:"blend-1",kg:15,quality:75,cost:300,zone:"Praha",roastedWeek:state.week}];state.roasters.forEach(r=>r.auto=false);nextWeek()');assert(r('state.business5.last.deliveries.reduce((a,d)=>a+d.delivered,0)<=15.001'));assert(r('state.business5.last.deliveries[1].delivered<8'));});
test('renewal adds time without duplicating customer or stock demand',()=>{own();sign();r('for(let i=0;i<9;i++)nextWeek();var q=businessRenewalQuote5(signed.id)');assert.equal(r('q.remaining'),3);r('renewBusiness5(signed.id,q)');assert.equal(r('state.contracts.length'),1);assert.equal(r('signed.remaining'),15);});
test('renewal and cancellation stale confirmations remain atomic',()=>{own();sign();r('var q=businessCancelQuote5(signed.id);signed.remaining-=1');const before=snap();assert.throws(()=>r('cancelBusiness5(signed.id,q)'));assert.equal(snap(),before);});
test('director prepares at most one proposal and does not sign without permission',()=>{own();r('hireExecutive5("sales",state.talents[0].pid);state.organization.policies.sales.enabled=true;state.organization.policies.sales.budget=100000;setBusinessPolicy5({enabled:true,autoSign:false,minMargin:0,maxKg:10,maxTerms:0});nextWeek()');assert.equal(r('state.business5.proposals.length'),1);assert.equal(r('state.contracts.length'),0);assert.equal(r('state.organization.reports.find(r=>r.role==="sales").cost'),1500);});
test('director signs under both mandates, budget and capacity and records actual fees',()=>{own();r('hireExecutive5("sales",state.talents[0].pid);state.organization.policies.sales.enabled=true;state.organization.policies.sales.budget=100000;setBusinessPolicy5({enabled:true,autoSign:true,minMargin:0,maxKg:10,maxTerms:0});nextWeek()');assert.equal(r('state.contracts.length'),1);assert.equal(r('state.business5.proposals.length'),0);assert.equal(r('state.organization.reports.find(r=>r.role==="sales").cost'),6500);assert(r('state.business5.last.deliveries.length>0'));});
test('director cannot overspend its budget or ignore the main mandate',()=>{own();r('hireExecutive5("sales",state.talents[0].pid);setBusinessPolicy5({enabled:true,autoSign:true,minMargin:0,maxKg:10,maxTerms:0});nextWeek()');assert.equal(r('state.contracts.length'),0);r('state.organization.policies.sales.enabled=true;state.organization.policies.sales.budget=1000;nextWeek()');assert.equal(r('state.contracts.length'),0);assert.equal(r('state.business5.proposals.length'),0);});
test('older version-five saves acquire empty B2B evidence without cash changes',()=>{own();const cash=r('state.cash');r('var old=JSON.parse(JSON.stringify(state));delete old.business5;var migrated=validateSave(old)');assert.equal(r('migrated.cash'),cash);assert.equal(r('migrated.business5.accounts.length'),10);});
test('bad invoice, payment, customer and contract metadata are rejected',()=>{own();sign(2);r('nextWeek()');for(const mutation of ['v.business5.invoices[0].amount=-1','v.business5.invoices[0].due+=1','v.business5.invoices[0].paid=3','v.business5.accounts[0].relationship=101','v.contracts[0].business5.shipping=0','v.business5.accounts[0].contract=null','v.business5.accounts[0].history[0].client="bistro"','v.business5.policy.maxTerms=3'])assert.throws(()=>r(`var v=JSON.parse(JSON.stringify(state));${mutation};validateSave(v)`));});
test('legacy wholesale contracts keep their economics and receive trade reports',()=>{own();r('state.contracts=[{id:"legacy-contract",name:"Legacy",blend:"blend-1",kg:10,price:500,remaining:12,fulfilled:0,last:null}];nextWeek()');assert.equal(r('state.business5.invoices.length'),0);near(r('state.business5.last.deliveries[0].shipping'),0);assert.equal(r('performanceReport5("trade",1).rows.length'),1);});
test('international fulfilment pays the stated freight on actual kilograms',()=>{own();sign(0,'brooklyn-b2b',60);r('nextWeek();var d=state.business5.last.deliveries[0]');near(r('d.shipping'),r('d.delivered*42'));});
test('100 weeks of repeated actual contracts preserve capped histories, physical invoices and save integrity',()=>{own();r('state.cash=10000000');for(let i=0;i<100;i++){r('if(!businessAccount5("hub").contract&&businessAccount5("hub").negotiated!==state.week&&state.cash>50000&&businessSlots5()){var p=negotiateBusiness5("hub",{blend:"blend-1",kg:10,price:500,weeks:12,terms:4});acceptBusiness5(p.id)}if(state.roasters[0].condition<70)maintainRoaster("roaster-1");nextWeek();validateSave(JSON.parse(JSON.stringify(state)))');assert(!r('state.over'));assert(r('state.business5.invoices.every(i=>i.due>=state.week)'));}assert(r('state.business5.accounts[0].history.length<=26'));assert.equal(r('state.week'),101);});
console.log(`${passed} business scenarios passed.`);
