const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
const scripts=[...fs.readFileSync('dist/index.html','utf8').matchAll(/<script src="([^"]+)"/g)].map(x=>x[1]).filter(x=>x!=='app.js'&&!x.endsWith('-ui.js')&&x!=='game-renderer.js');
const c=vm.createContext({Intl,console});for(const f of scripts)vm.runInContext(fs.readFileSync('dist/'+f,'utf8'),c,{filename:f});const r=s=>vm.runInContext(s,c);
r('state=fresh();startOpening6("cafe",{location:"letna",design:"starter",options:{kind:"legacy",space:"starter"}});signCoffeeAgreement6("local","letna","blend-1",{enabled:true,target:25,budget:20000,reserve:1});for(let i=0;i<7;i++)nextWeek();var s=state.stores[0],before=JSON.stringify(state),audit=floorRoutes9(s.floor,s.seats),blocked=new Set(floorInfo5(s.floor,s.seats).blocked);');
assert(r('JSON.stringify(state)===before&&audit.seats===s.seats&&audit.flow===floorInfo5(s.floor,s.seats).flow'));
r('for(const path of [audit.guest,...audit.legs.map(l=>l.path),...audit.tables.map(t=>t.path)]){if(!path.length||path.some(p=>blocked.has(p.x+","+p.y)))throw Error("walkability");for(let i=1;i<path.length;i++)if(Math.abs(path[i].x-path[i-1].x)+Math.abs(path[i].y-path[i-1].y)!==1)throw Error("non adjacent");}');
console.log('PASS: layout audit is pure and every customer, work and table route uses adjacent unoccupied cells');
r('var d=storeDesign5(s);d.equipment.oven="standard";var variants=[];for(let y=0;y<6;y++)for(let x=0;x<8;x++){var z=cloneStudio5(d);z.floor.items.push({id:"display",kind:"display",x,y});try{var i=designInfo5(z);variants.push({z,info:i});}catch{}}variants.sort((a,b)=>a.info.work-b.info.work);var near=variants[0],far=variants.at(-1),bad=cloneStudio5(near.z);delete bad.equipment.oven;');
assert(r('variants.length>1&&near.info.work<far.info.work&&near.info.flow>far.info.flow'));
assert.throws(()=>r('designInfo5(bad)'),/Vitrína/);
r('var nearStore=cloneStudio5(s),farStore=cloneStudio5(s);nearStore.floor=near.z.floor;farStore.floor=far.z.floor;var nearService=simulateService5(nearStore,{demand:6000,capacity:2000}),farService=simulateService5(farStore,{demand:6000,capacity:2000});');assert(r('nearService.potential>farService.potential'));
console.log('PASS: priced food display needs real oven technology; its position changes real queue capacity');
r('var stable=JSON.stringify(state),q=worldDesignQuote6(s.id,near.z);');assert(r('JSON.stringify(state)===stable&&q.purchases>=FURNITURE5.display.cost'));
r('state.cash=3000000;q=worldDesignQuote6(s.id,near.z);var cash=state.cash;worldApplyDesign6(s.id,near.z,q);saveDesign5("Vitrína a malé stolky",storeDesign5(s));');assert(r('state.cash===cash-q.cost&&s.floor.items.some(i=>i.kind==="display")&&state.studio5.designs.at(-1).design.equipment.oven'));
r('var corrupted=JSON.parse(JSON.stringify(state));delete corrupted.stores[0].equipment.oven;');assert.throws(()=>r('validateSave(corrupted)'));
r('validateSave(JSON.parse(JSON.stringify(state)));var stable=JSON.stringify(state),q=worldDesignQuote6(s.id,far.z);state.cash-=1;var changed=JSON.stringify(state);');assert.throws(()=>r('worldApplyDesign6(s.id,far.z,q)'),/změnily/);assert(r('JSON.stringify(state)===changed'));
console.log('PASS: display rebuild pays exact quote, is reusable in a saved design, imports correctly and rejects stale payment');
r('nextWeek();var saved=JSON.stringify(state);for(let d=0;d<6;d++)for(let t=0;t<72;t++)worldCafeSnapshot6(s.id,d,t);');assert(r('JSON.stringify(state)===saved'));
console.log('PASS: all 432 recorded cafe snapshots preserve company and recorded accounting');
r('s.food5.last={week:s.daily.last.week,days:Array.from({length:6},(_,day)=>({day,lost:20}))};var saved=JSON.stringify(state),sum=0;for(let t=0;t<72;t++)sum+=worldCafeSnapshot6(s.id,0,t).slot.foodMissing9;');assert(r('sum===20&&JSON.stringify(state)===saved'));
console.log('PASS: food shortage visualization allocates actual daily requests once and never invents coffee loss or revenue');
