const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
function game(){const c=vm.createContext({Intl,console});for(const f of ['engine','tycoon'])vm.runInContext(fs.readFileSync('dist/'+f+'.js','utf8'),c);return s=>vm.runInContext(s,c)}
function inspect(r){assert(r('Number.isFinite(state.cash)'));assert(r('state.batches.every(b=>b.kg>=0&&Number.isFinite(b.cost))'));assert(r('state.green.every(b=>b.kg>=0&&Number.isFinite(b.cost))'));assert(r('validateSave(JSON.parse(JSON.stringify(state))).version')===3);}
const r=game();r('state=fresh();hireCandidate("karlin","candidate-0");openStore("letna");hireCandidate("letna","candidate-1");openStore("vinohrady");hireCandidate("vinohrady","candidate-2");hireCandidate("roaster-1","candidate-3","roaster");');
for(let i=0;i<160;i++){
 if(r('state.roasters.length<10&&state.cash>weeklyFixed()*7+320000&&state.roasters.reduce((a,q)=>a+roasterCapacity(q)*.84,0)<Object.values(productionNeeds()).reduce((a,n)=>a+n,0)*1.5'))r('buyRoaster("artisan","Výroba "+state.week)');
 r('for(const q of state.roasters)if(q.condition<65&&state.cash>weeklyFixed()*3+18000)maintainRoaster(q.id)');
 if(r('state.cash>weeklyFixed()*7+450000&&state.stores.length<16')){const id=r('LOCATIONS.filter(l=>unlocked(l.city)&&!owned(l.id)&&!occupant(l.id)&&!state.auctions.some(a=>!a.closed&&a.location===l.id)&&l.setup<state.cash-weeklyFixed()*7).sort((a,b)=>a.setup-b.setup)[0]?.id');if(id)r(`openStore(${JSON.stringify(id)});hire(${JSON.stringify(id)},0)`);else{const rival=r('state.rivals.filter(q=>!q.bankrupt&&rivalValuation(q)<state.cash-weeklyFixed()*7).sort((a,b)=>rivalValuation(a)-rivalValuation(b))[0]?.id');if(rival)r(`acquireRival(${JSON.stringify(rival)})`)}}
 if(r('!state.offices.length&&state.cash>weeklyFixed()*7+600000'))r('buyOffice("studio");setDepartment("hr",1);setDepartment("product",2);researchBlend("blend-1");researchBlend("blend-1")');
 const h=r('nextWeek()');assert(Number.isFinite(h.profit));assert(!r('state.over'),'Natural campaign bankruptcy at '+r('state.week'));if(i%10===0)inspect(r);
}
inspect(r);assert(r('state.scenarioWon'),'Sandbox campaign should reach its international goal.');console.log('PASS: 160-week v3 campaign '+r('JSON.stringify({week:state.week,cash:Math.round(state.cash),stores:state.stores.length,cities:new Set(state.stores.map(s=>loc(s.id).city)).size,reputation:state.reputation,scenarioWon:state.scenarioWon,crises:state.incidentHistory.length,careers:staffAssignments().length})'));
const f=game();f('state=fresh("family","relaxed");hireCandidate("letna","candidate-0")');for(let i=0;i<120;i++){if(f('state.cash>weeklyFixed()*2+250000&&state.stores.length<3')){const id=f('LOCATIONS.filter(l=>unlocked(l.city)&&!owned(l.id)&&!occupant(l.id)&&!state.auctions.some(a=>!a.closed&&a.location===l.id)).sort((a,b)=>a.setup-b.setup)[0]?.id');if(id)f(`openStore(${JSON.stringify(id)});hire(${JSON.stringify(id)},0)`)}if(f('state.roasters[0].condition<65&&state.cash>weeklyFixed()*3+18000'))f('maintainRoaster("roaster-1")');if(f('!state.offices.length&&state.cash>weeklyFixed()*7+500000'))f('buyOffice("studio");setDepartment("product",1);researchBlend("blend-1");researchBlend("blend-1");researchBlend("blend-1")');if(f('state.roasters.length<2&&state.cash>weeklyFixed()*6+400000'))f('buyRoaster("artisan","Rodinná výroba")');if(f('state.stores.length>=2&&state.roasters[0].shifts===1'))f('state.roasters[0].shifts=2;state.roasters[0].staff=4');if(f('state.roasters[0].condition<65&&state.cash>weeklyFixed()*1.5+18000'))f('maintainRoaster("roaster-1")');f('nextWeek()');assert(!f('state.over'),'Family campaign bankrupt '+f('JSON.stringify({week:state.week,cash:state.cash,stores:state.stores.map(s=>({id:s.id,last:s.last,staff:s.staff,price:s.price})),history:state.history.slice(-4),logs:state.logs.slice(0,10)})'));}inspect(f);assert(f('state.scenarioWon'));console.log('PASS: family campaign reaches three profitable cafes and reputation '+f('state.reputation'));
const z=game();z('state=fresh("rescue","normal");for(const s of state.stores){s.staff=Math.ceil(loc(s.id).traffic/400);s.wage=6500;s.marketing=1500;hire(s.id,0)}');for(let i=0;i<110;i++){if(z('state.roasters[0].condition<65&&state.cash>weeklyFixed()*3+18000'))z('maintainRoaster("roaster-1")');if(z('state.debt&&state.cash>weeklyFixed()*6+100000'))z('repay()');z('nextWeek()');assert(!z('state.over'),'Rescue campaign bankrupt');}inspect(z);assert(z('state.scenarioWon'));console.log('PASS: rescue campaign produces four profitable weeks and reduces debt to '+z('state.debt'));
const p=game();p('state=fresh("premium","normal");hireCandidate("vinohrady","candidate-0");openStore("letna");hireCandidate("letna","candidate-1")');for(let i=0;i<140;i++){if(p('state.cash>weeklyFixed()*3+330000&&state.stores.length<6')){const id=p('LOCATIONS.filter(l=>unlocked(l.city)&&!owned(l.id)&&!occupant(l.id)&&!state.auctions.some(a=>!a.closed&&a.location===l.id)&&l.setup<state.cash-weeklyFixed()*7).sort((a,b)=>Number(state.stores.some(s=>loc(s.id).city===a.city))-Number(state.stores.some(s=>loc(s.id).city===b.city))||a.setup-b.setup)[0]?.id');if(id)p(`openStore(${JSON.stringify(id)});hire(${JSON.stringify(id)},0)`)}if(p('!state.offices.length&&state.cash>weeklyFixed()*6+500000'))p('buyOffice("studio");setDepartment("product",2);researchBlend("blend-1");researchBlend("blend-1")');if(p('state.roasters.length<4&&state.cash>weeklyFixed()*6+400000&&state.roasters.reduce((a,q)=>a+roasterCapacity(q)*.84,0)<Object.values(productionNeeds()).reduce((a,n)=>a+n,0)*1.5'))p('buyRoaster("artisan","Výběrová výroba")');p('for(const q of state.roasters)if(q.condition<65&&state.cash>weeklyFixed()*3+18000)maintainRoaster(q.id)');if(p('state.stores.length>=3&&state.roasters[0].shifts===1'))p('state.roasters[0].shifts=2;state.roasters[0].staff=4');p('nextWeek()');assert(!p('state.over'),'Premium campaign bankrupt');}inspect(p);assert(p('state.scenarioWon'));console.log('PASS: premium campaign reaches six cafes, three cities and reputation '+p('state.reputation'));
