const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');const c=vm.createContext({Intl,console});for(const f of [...require('./established-fixture.cjs').html().matchAll(/<script src="([^"]+)"/g)].map(x=>x[1]).filter(x=>x!=='app.js'&&!x.endsWith('-ui.js')))vm.runInContext(fs.readFileSync('dist/'+f,'utf8'),c);const r=s=>vm.runInContext(s,c),snap=()=>r('JSON.stringify(state)');let passed=0;function test(name,fn){r('state=fresh()');fn();r('validateSave(JSON.parse(JSON.stringify(state)))');passed++;console.log('PASS:',name);}function own(){r('openStore("letna");state.cash=20000000');}function funded(){own();r('leaseOffice6("hq");setDepartment("sales",2);setDepartment("finance",1);state.reputation=90');}
test('empty founder has no invented recap and cannot advance without a cafe',()=>{assert.equal(r('weeklyDigest6()'),null);const s=snap();assert.throws(()=>r('nextWeek()'));assert.equal(snap(),s);});
test('recap uses the final after-tax cash, profit, debt and actual cups',()=>{own();r('var h=nextWeek(),d=weeklyDigest6()');for(const k of ['week','profit','revenue','cash','cashChange','cups'])assert.equal(r('d.'+k),r('h.'+k));assert.equal(r('d.debt'),r('state.debt'));const s=snap();r('weeklyDigest6();weeklyDigest6(999);for(const x of d.items)digestPending6(x)');assert.equal(snap(),s);});
test('historic text and values survive later changes to prices, names and mandates',()=>{own();r('nextWeek();var old=JSON.stringify(weeklyDigest6());state.brands[0].name="Pozdější značka";updateMenu("letna","espresso",{enabled:true,price:150});nextWeek()');assert.equal(r('JSON.stringify(weeklyDigest6(1))'),r('old'));});
test('real poaching is prominent, remains actionable and repeats until answered',()=>{own();r('hireCandidate("letna","candidate-0");state.policy3.autoRetention=false;for(let i=0;i<8;i++)nextWeek();var o=state.offers[0],item=weeklyDigest6().items.find(x=>x.key==="poach-"+o.id)');assert(r('item.pending&&item.severity===2&&item.view==="people"&&item.due===o.due'));assert(r('digestPending6(item)'));r('nextWeek()');assert(r('weeklyDigest6().items.some(x=>x.key===item.key)'));});
test('resolved people decisions are inactive in history and not silently re-applied',()=>{own();r('hireCandidate("letna","candidate-0");state.policy3.autoRetention=false;for(let i=0;i<8;i++)nextWeek();var o=state.offers[0],item=weeklyDigest6().items.find(x=>x.key==="poach-"+o.id);resolveOffer(o.id,"match");var cash=state.cash,seen=state.digest6.seen;acknowledgeDigest6(8)');assert(!r('digestPending6(item)'));assert.equal(r('state.cash'),r('cash'));assert.equal(r('state.digest6.seen'),8);r('nextWeek()');assert(!r('weeklyDigest6().items.some(x=>x.key===item.key)'));});
test('B2B proposals show price, deadline and link without signing or paying',()=>{funded();r('var p=negotiateBusiness5("hub",{blend:"blend-1",kg:10,price:500,weeks:12,terms:2});nextWeek();var item=weeklyDigest6().items.find(x=>x.key==="b2b-"+p.id)');assert(r('item.pending&&item.view==="business"&&item.due===p.due'));assert.equal(r('state.contracts.length'),0);const s=snap();r('weeklyDigest6();digestPending6(item)');assert.equal(snap(),s);});
test('signed customer and supplier contracts and upcoming invoices share the same recap',()=>{funded();r('var p=negotiateBusiness5("hub",{blend:"blend-1",kg:10,price:500,weeks:12,terms:2});var c=acceptBusiness5(p.id);var supplier=signProcurement5({supplier:"harbor",origin:"brazil",kg:20,terms:2,reserve:1,weeks:12});setProcurementStatus5(supplier.id,"paused");nextWeek()');assert(r('weeklyDigest6().items.some(x=>x.key==="signed-"+c.id)'));assert(r('weeklyDigest6().items.some(x=>x.key==="supplier-signed-"+supplier.id)'));assert(r('weeklyDigest6().items.some(x=>x.key.startsWith("receivable-"))'));});
test('contract renewal warnings and ended contracts reflect real remaining duration',()=>{funded();r('var p=negotiateBusiness5("hub",{blend:"blend-1",kg:10,price:500,weeks:12,terms:0});var c=acceptBusiness5(p.id);c.remaining=2;nextWeek()');assert(r('weeklyDigest6().items.some(x=>x.key==="renew-"+c.id&&x.pending)'));r('nextWeek()');assert(r('weeklyDigest6().items.some(x=>x.key==="ended-"+c.id)'));assert(!r('state.contracts.some(x=>x.id===c.id)'));});
test('supplier maturities and lease expirations refer to actual live obligations',()=>{funded();r('var o=buyProcurement5({supplier:"harbor",origin:"brazil",kg:20,terms:2,reserve:1});for(let i=0;i<4&&!state.procurement5.payables.length;i++)nextWeek();var bill=state.procurement5.payables[0]');assert(r('weeklyDigest6().items.some(x=>x.key==="payable-"+bill.id&&x.due===bill.due)'));r('state.stores[0].lease.due=state.week+2;nextWeek()');assert(r('weeklyDigest6().items.some(x=>x.key==="lease-letna"&&x.view==="property")'));});
test('generated personal stories and manager plans are visible until their own decision',()=>{own();r('hireCandidate("letna","candidate-0");state.empire.autoPlans=false;for(let i=0;i<24;i++){nextWeek();for(const o of [...state.offers])resolveOffer(o.id,"match")}');assert(r('weeklyDigest6().items.some(x=>x.key.startsWith("story-")&&x.pending)'));assert(r('state.digest6.history.some(h=>h.items.some(x=>x.key.startsWith("plan-")&&x.pending))'));});
test('competition expansion is based on a new actual address, not repeated invented news',()=>{own();r('for(let i=0;i<30;i++)nextWeek()');assert(r('state.digest6.history.some(h=>h.items.some(x=>x.key.startsWith("expansion-")))'));const s=snap();r('weeklyDigest6();weeklyDigest6();');assert.equal(snap(),s);});
test('bankrupt company keeps a valid last summary with zero remaining reserve',()=>{own();r('state.cash=1;for(const m of Object.values(state.stores[0].menu))m.enabled=false;nextWeek()');assert(r('state.over&&weeklyDigest6().over'));assert.equal(r('weeklyDigest6().reserve'),0);});
test('actual forecast restores recap archive, seen state and every financial field',()=>{own();r('nextWeek();acknowledgeDigest6(1)');const s=snap();r('bakeryForecast5(4);supplyForecast5(4,1)');assert.equal(snap(),s);});
test('archive retains exactly thirteen weeks and real save round trips',()=>{own();r('for(let i=0;i<40;i++)nextWeek();acknowledgeDigest6(40)');assert.equal(r('state.digest6.history.length'),13);assert.equal(r('state.digest6.history[0].week'),28);assert.equal(r('state.digest6.seen'),40);});
test('migration leaves original cash, state and past events unchanged without fabricated recaps',()=>{own();r('nextWeek();var v=JSON.parse(JSON.stringify(state)),cash=v.cash;delete v.digest6;var restored=validateSave(v)');assert.equal(r('restored.cash'),r('cash'));assert.equal(r('restored.digest6.history.length'),0);assert.equal(r('restored.digest6.seen'),r('restored.week-1'));});
test('malformed dates, categories, links and duplicate items reject before import',()=>{own();r('nextWeek()');for(const code of ['v.digest6.seen=v.week','v.digest6.history[0].week=v.week','v.digest6.history[0].items[0].view="javascript:bad"','v.digest6.history[0].items[0].category="bad"','v.digest6.history[0].items.push(v.digest6.history[0].items[0])']){r('var v=JSON.parse(JSON.stringify(state))');r(code);assert.throws(()=>r('validateSave(v)'));}const s=snap();assert.throws(()=>r('acknowledgeDigest6(999)'));assert.equal(snap(),s);});
test('maximum cafe network retains every operating exception without breaking archive validation',()=>{r('state.cash=800000000;for(const rival of state.rivals){rival.stores=[];rival.operations5.branches=[];}state.stores=LOCATIONS.map(l=>makeStore(l.id));state.studio5.opening=false;for(let i=0;i<3;i++)nextWeek()');assert.equal(r('state.stores.length'),111);assert(r('weeklyDigest6().items.length>100'));assert(r('weeklyDigest6().items.length<2000'));});
console.log(`${passed} weekly digest scenarios passed.`);
