const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');const c=vm.createContext({Intl,console});for(const f of [...fs.readFileSync('dist/index.html','utf8').matchAll(/<script src="([^"]+)"/g)].map(x=>x[1]).filter(x=>x!=='app.js'&&!x.endsWith('-ui.js')))vm.runInContext(fs.readFileSync('dist/'+f,'utf8'),c);const r=s=>vm.runInContext(s,c),snap=()=>r('JSON.stringify(state)'),near=(a,b,t=.01)=>assert(Math.abs(a-b)<t,`${a} != ${b}`);let passed=0;function test(name,fn){r('state=fresh()');fn();r('validateSave(JSON.parse(JSON.stringify(state)))');passed++;console.log('PASS:',name);}function own(){r('openStore("letna");state.cash=20000000');}function project(type='offices'){r('state.districts6.projects=[{id:"district-0-0",location:"letna",type:"'+type+'",announced:1,start:6,finish:6+DISTRICT_PROJECTS6["'+type+'"].weeks,applied:false}]');}
test('founder has no selected/owned address but already knows announced plans in every city',()=>{assert.equal(r('state.stores.length'),0);assert.equal(r('state.districts6.locations.length'),111);assert.equal(r('state.districts6.projects.length'),18);assert(r('state.districts6.projects.every(p=>p.announced===1&&p.start===6)'));});
test('surroundings and future context reads leave all state and randomness untouched',()=>{const s=snap();r('for(const l of LOCATIONS){districtContext6(l.id);districtContext6(l.id,15);marketResearchQuote6(l.id,"basic")}');assert.equal(snap(),s);assert(r('districtContext6("letna").mix.reduce((n,x)=>n+x,0)> .9999'));});
test('unopened company can buy immutable nine-variant research without opening or changing concept',()=>{const cash=r('state.cash'),b=r('state.brands[0].concept');r('var q=marketResearchQuote6("letna","basic"),report=runMarketResearch6("letna","basic",q)');assert.equal(r('state.cash'),cash-1500);assert.equal(r('state.pendingExpense3'),1500);assert.equal(r('state.stores.length'),0);assert.equal(r('state.brands[0].concept'),b);assert.equal(r('report.estimates.length'),9);assert.equal(r('new Set(report.estimates.map(e=>e.concept)).size'),3);assert(r('report.estimates.every(e=>e.low<=e.demand&&e.high>=e.demand&&e.profitLow<=e.profit&&e.profitHigh>=e.profit)'));const s=snap();r('districtContext6("letna");performanceReport5("stores")');assert.equal(snap(),s);});
test('same week paid report is cached with no reroll or repeat charge; advanced report is narrower',()=>{r('var basic=runMarketResearch6("letna","basic"),cash=state.cash,copy=JSON.stringify(basic),again=runMarketResearch6("letna","basic"),pro=runMarketResearch6("letna","professional")');assert.equal(r('basic.id'),r('again.id'));assert.equal(r('JSON.stringify(basic)'),r('copy'));assert.equal(r('cash-state.cash'),6500);assert(r('pro.estimates[0].high-pro.estimates[0].low < basic.estimates[0].high-basic.estimates[0].low'));});
test('cancelable quote, insufficient funds and stale confirmations never charge or mutate',()=>{r('var q=marketResearchQuote6("letna","basic");state.cash++');const s=snap();assert.throws(()=>r('runMarketResearch6("letna","basic",q)'));assert.equal(snap(),s);r('state.cash=100');const t=snap();assert.throws(()=>r('runMarketResearch6("letna","basic")'));assert.equal(snap(),t);});
test('survey uses paid local roster, queue and demand model and restores the live state',()=>{own();const s=snap();r('var a=surveyOperating6("letna","community",1),b=surveyOperating6("letna","express",1.1)');assert.equal(snap(),s);assert(r('a.weeklyFixed>40000&&a.served<=a.demand&&a.quality>0'));assert.notEqual(r('a.price'),r('b.price'));assert.notEqual(r('a.demand'),r('b.demand'));});
test('announced roadworks reduce real demand in their actual weeks and recover without permanent benefit',()=>{own();project('roadwork');r('state.week=6;var active=demandForStore(state.stores[0],1).demand,ctx=districtContext6("letna");state.districts6.projects=[];var clean=demandForStore(state.stores[0],1).demand');assert(r('active<clean&&ctx.foot===.84'));project('roadwork');r('state.week=10;updateDistricts6()');assert.equal(r('districtContext6("letna").foot'),1);assert(r('state.districts6.projects[0].applied'));r('delete state.stores[0].daily.pending');});
test('finished offices change guest mix and new rents exactly once; existing fixed rent survives',()=>{own();project();r('var mix=districtMix6("letna"),rent=propertyMarket5("letna").rent,contract=state.stores[0].lease.rent;state.week=9;updateDistricts6();var after=JSON.stringify(districtState6("letna"));updateDistricts6()');assert.equal(r('JSON.stringify(districtState6("letna"))'),r('after'));assert(r('districtMix6("letna")[0]>mix[0]'));assert.equal(r('districtState6("letna").foot'),1.06);assert(r('propertyMarket5("letna").rent>rent'));assert.equal(r('state.stores[0].lease.rent'),r('contract'));r('districtLeaseAdjustment6(state.stores[0])');near(r('state.stores[0].lease.rent'),r('Math.round(contract*1.04)'));});
test('completed negative project can reduce demand and rent without making negative cohorts',()=>{own();project('vacancy');r('state.week=7;updateDistricts6()');near(r('districtContext6("letna").foot'),.935);near(r('districtContext6("letna").rent'),.96);assert(r('districtMix6("letna").every(x=>x>0)'));});
test('rival near works has actual lost sales, net VAT and balanced payroll cost ledger',()=>{own();r('var rival=state.rivals[0],branch=rival.operations5.branches[0],baseline=rivalOperating5(rival,branch);state.districts6.projects=[{id:"district-0-0",location:branch.id,type:"roadwork",announced:1,start:6,finish:10,applied:false}];state.week=6;var q=rivalOperating5(rival,branch)');assert(r('q.traffic<baseline.traffic'));near(r('q.gross6-q.vat6'),r('q.revenue'));near(r('q.revenue-q.cost'),r('q.profit'));near(r('q.wages+q.rent+q.coffee+q.overhead'),r('q.cost'));});
test('actual construction, completion and seasonal snapshots persist across changing districts',()=>{own();project();r('var report=runMarketResearch6("letna","basic"),snapshot=JSON.stringify(report);for(let i=0;i<30;i++)nextWeek()');assert.equal(r('JSON.stringify(report)'),r('snapshot'));assert.equal(r('state.districts6.history.length'),26);assert(r('state.seasons5.history.every(h=>h.stores[0].mix6.length===5)'));assert(r('state.districts6.projects.some(p=>p.applied)'));assert(r('state.digest6.history.some(h=>h.items.some(i=>i.view==="city"))'));});
test('older saves migrate neutrally and all prior seasonal records still validate',()=>{own();r('for(let i=0;i<4;i++)nextWeek();var v=JSON.parse(JSON.stringify(state)),cash=v.cash;delete v.districts6;for(const h of v.seasons5.history)for(const s of h.stores){delete s.mix6;const l=loc(s.id),cfg=citySeason5(l.city,h.week);s.factor=GUEST_MIX5[l.segment].reduce((n,w,i)=>n+w*cfg.factors[GUEST_KEYS5[i]],0)}var restored=validateSave(v)');assert.equal(r('restored.cash'),r('cash'));assert.equal(r('restored.districts6.since'),5);assert(r('restored.districts6.locations.every(l=>l.foot===1&&l.rent===1)'));assert.equal(r('restored.districts6.reports.length'),0);});
test('corrupt plans, reports, guest mix, financial ranges and lease indices are rejected',()=>{r('runMarketResearch6("letna","basic")');for(const code of ['v.districts6.locations[0].foot=50','v.districts6.projects[0].finish++','v.districts6.reports[0].fee=0','v.districts6.reports[0].context.mix[0]=5','v.districts6.reports[0].estimates[0].profitLow=1e12']){r('var v=JSON.parse(JSON.stringify(state))');r(code);assert.throws(()=>r('validateSave(v)'));}});
test('rival district rent is held until renewal and new branch quotes use current surroundings',()=>{own();r('var rival=state.rivals[0],branch=rival.operations5.branches[0],initial=rivalOperating5(rival,branch).rent;districtState6(branch.id).rent=1.04;var held=rivalOperating5(rival,branch).rent,proposal=rivalBranch5(rival,branch.id),freshRent=rivalOperating5(rival,proposal).rent;branch.districtLease6.until=state.week;nextWeek()');assert.equal(r('held'),r('initial'));assert(r('freshRent>initial'));assert.equal(r('branch.districtLease6.index'),1.04);});
test('past surrounding queries cannot silently substitute current permanent changes',()=>{own();r('for(let i=0;i<5;i++)nextWeek()');const s=snap();assert.throws(()=>r('districtContext6("letna",1)'));assert.equal(snap(),s);});
test('quarterly announcements and applied effects remain bounded through three years',()=>{own();r('for(let i=0;i<156;i++)nextWeek()');assert(r('state.districts6.projects.length<=72'));assert(r('state.districts6.history.length===26'));assert(r('state.districts6.locations.every(l=>l.foot>=.85&&l.foot<=1.18&&l.rent>=.85&&l.rent<=1.18)'));});
console.log(passed+' district and research scenarios passed.');
