const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
const scripts=[...fs.readFileSync('dist/index.html','utf8').matchAll(/<script src="([^"]+)"/g)].map(x=>x[1]).filter(x=>x!=='app.js'&&!x.endsWith('-ui.js')&&x!=='game-renderer.js');
function game(){const c=vm.createContext({Intl,console});for(const f of scripts)vm.runInContext(fs.readFileSync('dist/'+f,'utf8'),c,{filename:f});return s=>vm.runInContext(s,c);}
const paid='state=fresh();startOpening6("cafe",{location:"letna",design:"starter",options:{kind:"legacy",space:"starter"}});signCoffeeAgreement6("local","letna","blend-1",{enabled:true,target:25,budget:20000,reserve:1});for(let i=0;i<7;i++)nextWeek();var s=state.stores[0];';
let passed=0;function test(name,fn){const r=game();r(paid);fn(r);r('validateSave(JSON.parse(JSON.stringify(state)))');console.log('PASS: '+name);passed++;}
test('Actual Standard founder can quote and pay for more room without losing its café',r=>{r('var before=JSON.stringify(state),team=JSON.stringify(s.crew),floor=JSON.stringify(s.floor),menu=JSON.stringify(s.menu),q=propertyExpansionQuote18("letna","compact"),cash=state.cash,capital=s.capital6,oldRent=s.lease.rent,due=s.lease.due;');assert(r('q.safe&&q.cost>0&&q.after>0&&q.limit===24&&JSON.stringify(state)===before'));r('expandProperty18("letna","compact",q);');assert(r('state.cash===cash-q.cost&&s.capital6===capital+q.fitout&&s.seats===16&&JSON.stringify(s.floor)===floor&&JSON.stringify(s.crew)===team&&JSON.stringify(s.menu)===menu&&s.lease.due===due&&s.lease.rent>oldRent'));});
test('New ceiling permits actual paid furniture, while the old ceiling rejects it',r=>{r('var d=storeDesign5(s);d.floor.items.push({id:"expansion-table",kind:"table2",x:6,y:4});var before=JSON.stringify(state);');assert.throws(()=>r('designQuote5("letna",d)'),/nejvýše 16/);assert(r('JSON.stringify(state)===before'));r('expandProperty18("letna","compact");var q=worldDesignQuote6("letna",d),cash=state.cash;worldApplyDesign6("letna",d,q);');assert(r('s.seats===18&&state.cash===cash-q.cost&&s.floor.items.some(i=>i.id==="expansion-table")'));});
test('Sequential expansion and direct expansion charge the same capital and final rent',r=>{r('state.cash=10000000;var baseline=JSON.parse(JSON.stringify(state)),cash=state.cash;expandProperty18("letna","compact");expandProperty18("letna","standard");expandProperty18("letna","flagship");var sequential=cash-state.cash,rent=s.lease.rent,capital=s.capital6;state=JSON.parse(JSON.stringify(baseline));s=state.stores[0];expandProperty18("letna","flagship");');assert(r('state.stores[0].premises5.space==="flagship"&&cash-state.cash===sequential&&Math.abs(s.lease.rent-rent)<=1&&s.capital6===capital&&propertyExpansionSpaces18("letna").length===0'));});
test('Insufficient cash, stale quote and repeated payment fail atomically',r=>{r('var q=propertyExpansionQuote18("letna","compact");state.cash--;var before=JSON.stringify(state);');assert.throws(()=>r('expandProperty18("letna","compact",q)'),/změnily/);assert(r('JSON.stringify(state)===before'));r('state.cash=1;before=JSON.stringify(state);');assert.throws(()=>r('expandProperty18("letna","compact")'),/Chybí/);assert(r('JSON.stringify(state)===before'));r('state.cash=1000000;q=propertyExpansionQuote18("letna","compact");expandProperty18("letna","compact",q);before=JSON.stringify(state);');assert.throws(()=>r('expandProperty18("letna","compact",q)'));assert(r('JSON.stringify(state)===before'));});
test('Rented expansion tops up held deposit once and preserves signed lease maturity',r=>{r('signPropertyLease5("letna","secure");var deposit=s.premises5.deposit,due=s.lease.due,signed=s.premises5.signed,pending=state.pendingExpense3,cash=state.cash,q=propertyExpansionQuote18("letna","compact");expandProperty18("letna","compact",q);');assert(r('state.cash===cash-q.cost&&s.premises5.deposit===deposit+q.topup&&s.premises5.deposit===s.lease.rent*4&&s.lease.due===due&&s.premises5.signed===signed&&state.pendingExpense3===pending'));r('state.cash=10000000;var rent=s.lease.rent;nextWeek();');assert(r('state.property5.last.rows[0].rent===rent&&state.economy6.assets.find(a=>a.id==="fitout-letna").cost===s.capital6'));});
test('Owning an expanded building books construction and fitout separately, preserves depreciation',r=>{r('state.cash=10000000;buyProperty5("letna");nextWeek();var a=propertyAsset5("letna"),book=a.book,economic=state.economy6.assets.find(x=>x.id===a.id),accum=economic.accum,pending=state.pendingExpense3,history=JSON.stringify(state.property5.history),q=propertyExpansionQuote18("letna","standard"),cash=state.cash;expandProperty18("letna","standard",q);');assert(r('q.building>0&&q.rent===0&&q.topup===0&&state.cash===cash-q.cost&&a.book===book+q.building&&a.upkeep===q.upkeep&&economic.cost===a.book*.5&&economic.accum===accum&&JSON.stringify(state.property5.history)===history&&state.pendingExpense3===pending'));r('nextWeek();');assert(r('state.property5.last.rows[0].rent===0&&state.property5.last.rows[0].upkeep===q.upkeep&&economic.accum>accum'));});
test('Quarterly expansion budgets and minority board mandates block before any mutation',r=>{r('state.founderShare=49;state.expansionBudget=0;var before=JSON.stringify(state);');assert.throws(()=>r('expandProperty18("letna","compact")'),/mandát/);assert(r('JSON.stringify(state)===before'));r('state.expansionBudget=1000000;var q=propertyExpansionQuote18("letna","compact"),mandate=state.expansionBudget;expandProperty18("letna","compact",q);');assert(r('state.expansionBudget===mandate-q.cost'));r('state.founderShare=100;var plan=planDefaultData6();plan.budgets.expansion=1;setCompanyPlan6(plan);before=JSON.stringify(state);');assert.throws(()=>r('expandProperty18("letna","standard")'),/čtvrtletní/);assert(r('JSON.stringify(state)===before'));r('plan.budgets.expansion=1000000;setCompanyPlan6(plan);var q=propertyExpansionQuote18("letna","standard");expandProperty18("letna","standard",q);');assert(r('state.planning6.current.spent.expansion===q.cost&&state.planning6.current.events.at(-1).amount===q.cost'));});
test('Invalid targets, old legacy room, franchise and temporary venue never receive a free upgrade',r=>{for(const key of ['starter','existing','fake'])assert.throws(()=>r('expandProperty18("letna",'+JSON.stringify(key)+')'));r('var p=s.premises5;s.premises5={...p,enabled:false,space:"existing"};var before=JSON.stringify(state);');assert.throws(()=>r('expandProperty18("letna","flagship")'));assert(r('JSON.stringify(state)===before'));r('s.premises5=p;s.franchise=true;');assert.throws(()=>r('expandProperty18("letna","compact")'));r('s.franchise=false;s.temporary8="venue-test";');assert.throws(()=>r('expandProperty18("letna","compact")'));r('delete s.temporary8;');});
test('Saved expansion history rejects forged space and money without changing import or current game',r=>{r('expandProperty18("letna","compact");var saved=JSON.parse(JSON.stringify(state)),before=JSON.stringify(state);');for(const code of ['v.property5.events.at(-1).space="starter"','v.property5.events.at(-1).building=-1','v.property5.events.at(-1).cash=100','v.property5.events.at(-1).cash--','v.property5.events.at(-1).deposit++','v.property5.events.at(-1).fitout=NaN']){r('var v=JSON.parse(JSON.stringify(saved));'+code+';var input=JSON.stringify(v);');assert.throws(()=>r('validateSave(v)'));assert(r('JSON.stringify(v)===input&&JSON.stringify(state)===before'));}});
console.log('PASS: '+passed+' existing café expansion scenarios');
