const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
const files=[...fs.readFileSync('dist/index.html','utf8').matchAll(/<script src="([^"]+)"/g)].map(m=>m[1]).filter(f=>f!=='app.js'&&!f.endsWith('-ui.js')&&f!=='game-renderer.js');
function game(){const c=vm.createContext({console,Intl});for(const f of files)vm.runInContext(fs.readFileSync('dist/'+f,'utf8'),c,{filename:f});vm.runInContext('function advance12(){const h=nextWeek();for(const o of [...state.offers])if(staffAssignments().some(a=>a.person.pid===o.pid))resolveOffer(o.id,"match");return h;}',c);return s=>vm.runInContext(s,c);}
const company='state=fresh();state.cash=20000000;startOpening6("cafe",{location:"letna",design:"starter",options:{kind:"legacy",space:"starter"}});signCoffeeAgreement6("local","letna","blend-1",{enabled:true,target:25,budget:20000,reserve:1});for(let i=0;i<6;i++)advance12();hireCandidate("letna",state.talents[0].pid);var m=state.stores[0].manager;';
let passed=0;function test(name,fn){const r=game();fn(r);r('validateSave(JSON.parse(JSON.stringify(state)))');console.log('PASS: '+name);passed++;}
test('Neutral migration adds no money, personnel, goal or paid succession',r=>{r('var old=JSON.parse(JSON.stringify(state));delete old.experience12;var before=JSON.stringify(old),v=validateSave(old);delete v.experience12;');assert(r('JSON.stringify(v)===before&&JSON.stringify(old)===before'));});
test('All three existing difficulty levels change actual demand in the same paid cafe',r=>{r(company+'var before=JSON.stringify(state),values=Object.keys(DIFFICULTIES).map(level=>tnPure7(()=>{state.difficulty=level;return demandForStore(state.stores[0],1).demand;}));');assert(r('values[0]>values[1]&&values[1]>values[2]&&JSON.stringify(state)===before'));r('var q=difficultyQuote12("expert"),cash=state.cash;setDifficulty12("expert",q);');assert(r('state.difficulty==="expert"&&state.cash===cash&&state.experience12.difficultyHistory.length===1'));});
test('Changed difficulty confirmation is stale and cannot reset or partially change the company',r=>{r(company+'var q=difficultyQuote12("relaxed");state.cash--;var before=JSON.stringify(state);');assert.throws(()=>r('setDifficulty12("relaxed",q)'),/změnily/);assert(r('JSON.stringify(state)===before'));assert.throws(()=>r('difficultyQuote12("fake")'));});
test('A real manager gains an individual goal after actual experience, with a named weekly request',r=>{r(company+'m.character6.trait="craft";for(let i=0;i<4;i++)advance12();var g=m.career12.goal;');assert(r('g.focus==="product"&&g.status==="active"&&g.target>g.baseline'));assert(r('weeklyDigest6().items.some(i=>i.key==="career-goal-"+m.pid&&i.pending&&i.title.includes(m.name))'));});
test('Pure career quote and paid actual training improve the same identity and relationship',r=>{r(company+'m.character6.trait="craft";for(let i=0;i<4;i++)advance12();var before=JSON.stringify(state),q=careerActionQuote12(m.pid,"training","",1);');assert(r('JSON.stringify(state)===before&&q.cost===18000'));r('var cash=state.cash,skill=m.strength.product,relationship=m.character6.relationship;doCareerAction12(m.pid,"training","",1,q);');assert(r('cash-state.cash===18000&&m.strength.product===Math.min(99,skill+4)&&m.character6.relationship===relationship+3'));});
test('Success uses actual learned skills; missed goal stays archived with its original deadline',r=>{r(company+'m.character6.trait="craft";for(let i=0;i<4;i++)advance12();var g=m.career12.goal;for(let i=0;i<2;i++){var q=careerActionQuote12(m.pid,"training","",1);doCareerAction12(m.pid,"training","",1,q);}advance12();');assert(r('g.status==="fulfilled"&&g.actual>=g.target&&m.career12.history.length===1'));r('var frozen=JSON.stringify(g);for(let i=0;i<18;i++)advance12();');assert(r('m.career12.history.some(x=>JSON.stringify(x)===frozen)'));});
test('Very low satisfaction gives three actual weeks of notice instead of vanishing immediately',r=>{r(company+'m.satisfaction=20;advance12();var notice=m.career12.notice;');assert(r('state.stores[0].manager===m&&notice.due===notice.created+3&&weeklyDigest6().items.some(i=>i.key.startsWith("career-notice-"))'));r('advance12();advance12();');assert(r('state.stores[0].manager===m'));r('advance12();');assert(r('state.stores[0].manager===null&&state.talents.some(p=>p.pid===m.pid)&&state.experience12.departures.at(-1).pid===m.pid'));assert(r('weeklyDigest6().items.some(i=>i.key.startsWith("career-departed-"))'));});
test('A recovered relationship and actual raised satisfaction cancel the notice',r=>{r(company+'m.satisfaction=24;advance12();m.satisfaction=44;var q=careerActionQuote12(m.pid,"raise","",1),cash=state.cash;doCareerAction12(m.pid,"raise","",1,q);advance12();');assert(r('state.stores[0].manager===m&&m.career12.notice===null&&state.cash!==cash&&q.cost===0&&q.weekly>0'));});
test('Succession pays once and trains one concrete available candidate over four real weeks',r=>{r(company+'var p=state.talents[0],before=JSON.stringify(state),q=successionPlanQuote12("store","letna",p.pid,1);');assert(r('JSON.stringify(state)===before'));r('var cash=state.cash,pending=state.empire.pendingExpense,x=planSuccession12("store","letna",p.pid,1,q);');assert(r('cash-state.cash===18000&&state.empire.pendingExpense-pending===18000&&state.stores[0].manager===m'));r('for(let i=0;i<4;i++){advance12();validateSave(JSON.parse(JSON.stringify(state)));}');assert(r('x.status==="ready"&&x.samples.length===4&&p.strength[x.focus]===Math.min(99,x.before+4)&&state.stores[0].manager===m'));});
test('Explicit appointment pays actual recruitment once and retains both original people',r=>{r(company+'var p=state.talents[0],q=successionPlanQuote12("store","letna",p.pid,1),x=planSuccession12("store","letna",p.pid,1,q);for(let i=0;i<4;i++)advance12();var q=successionAppointQuote12(x.id,1),cash=state.cash,pending=state.empire.pendingExpense;appointSuccession12(x.id,1,q);');assert(r('cash-state.cash===q.cost&&q.cost===12000&&state.stores[0].manager.pid===p.pid&&state.talents.some(p=>p.pid===m.pid)&&x.status==="appointed"'));assert(r('state.empire.pendingExpense-pending===q.cost-q.booked'));assert.throws(()=>r('appointSuccession12(x.id,1,q)'));});
test('Missing mentor pauses training and an independently hired candidate cannot be duplicated',r=>{r(company+'var p=state.talents[0],q=successionPlanQuote12("store","letna",p.pid,1),x=planSuccession12("store","letna",p.pid,1,q);fire("letna");advance12();');assert(r('x.status==="preparing"&&x.samples.length===0'));r('hireCandidate("letna",p.pid);advance12();');assert(r('x.status==="unavailable"&&x.samples.length===0'));assert.throws(()=>r('successionAppointQuote12(x.id,1)'));});
test('Reserve, quarterly budget and stale confirmation preserve the candidate and cash',r=>{r(company+'var p=state.talents[0],q=successionPlanQuote12("store","letna",p.pid,1);state.cash--;var before=JSON.stringify(state);');assert.throws(()=>r('planSuccession12("store","letna",p.pid,1,q)'),/změnily/);assert(r('JSON.stringify(state)===before'));r('var plan=planDefaultData6();plan.budgets.people=0;setCompanyPlan6(plan);var before=JSON.stringify(state);');assert.throws(()=>r('successionPlanQuote12("store","letna",p.pid,1)'),/rozpočet/);assert(r('JSON.stringify(state)===before'));});
test('Current weekly digest, frozen archive and corruption checks survive 30 real weeks',r=>{r(company+'m.character6.trait="craft";for(let i=0;i<4;i++)advance12();var saved=JSON.parse(JSON.stringify(state)),live=JSON.stringify(state);');for(const mutation of ['v.difficulty="fake"','v.stores[0].manager.career12.goal.target=1000','v.stores[0].manager.career12.lastWeek=v.week+1','v.experience12.departures.push({pid:"fake",name:"X",week:v.week+1})']){r('var v=JSON.parse(JSON.stringify(saved));'+mutation+';var before=JSON.stringify(v);');assert.throws(()=>r('validateSave(v)'));assert(r('JSON.stringify(v)===before&&JSON.stringify(state)===live'));}r('var archive=JSON.stringify(weeklyDigest6());for(let i=0;i<30;i++){advance12();validateSave(JSON.parse(JSON.stringify(state)));}');assert(r('state.experience12.departures.length<=52&&state.digest6.history.length===13'));});
test('Greater ambition creates a shorter real deadline without granting skills or promotion',r=>{r(company+'m.character6.trait="craft";m.ambition=75;var strength=JSON.stringify(m.strength);for(let i=0;i<4;i++)advance12();');assert(r('m.career12.goal.weeks===8&&m.career12.goal.due-m.career12.goal.created===8&&JSON.stringify(m.strength)===strength'));});
test('Early appointment preserves only completed training and charges real recruitment',r=>{r(company+'var p=state.talents[0],q=successionPlanQuote12("store","letna",p.pid,1),x=planSuccession12("store","letna",p.pid,1,q);advance12();var skill=p.strength[x.focus],before=JSON.stringify(state),q=successionAppointQuote12(x.id,1);');assert(r('JSON.stringify(state)===before&&x.samples.length===1'));r('var cash=state.cash;appointSuccession12(x.id,1,q);');assert(r('cash-state.cash===12000&&x.status==="appointed"&&x.samples.length===1&&state.stores[0].manager.strength[x.focus]===skill&&state.talents.some(p=>p.pid===m.pid)'));r('var saved=JSON.parse(JSON.stringify(state));');for(const mutation of ['v.experience12.succession[0].fee=0','v.experience12.succession[0].samples[0].after+=8','v.experience12.succession[0].applied=v.week+1']){r('var v=JSON.parse(JSON.stringify(saved));'+mutation);assert.throws(()=>r('validateSave(v)'));}});
test('Early appointment rejects stale, quarterly and cash-reserve violations before any transfer',r=>{r(company+'var p=state.talents[0],q=successionPlanQuote12("store","letna",p.pid,1),x=planSuccession12("store","letna",p.pid,1,q),q=successionAppointQuote12(x.id,1);state.cash--;var before=JSON.stringify(state);');assert.throws(()=>r('appointSuccession12(x.id,1,q)'),/změnily/);assert(r('JSON.stringify(state)===before'));r('var plan=planDefaultData6();plan.budgets.people=0;setCompanyPlan6(plan);var before=JSON.stringify(state);');assert.throws(()=>r('successionAppointQuote12(x.id,1)'),/rozpočet/);assert(r('JSON.stringify(state)===before'));r('var plan=planDefaultData6();plan.budgets.people=2000000;setCompanyPlan6(plan);state.cash=12001;var q=successionAppointQuote12(x.id,8),before=JSON.stringify(state);');assert(r('!q.safe'));assert.throws(()=>r('appointSuccession12(x.id,8,q)'),/rezervu/);assert(r('JSON.stringify(state)===before'));});
console.log('PASS: '+passed+' real difficulty, career, notice, paid succession, accounting and archive cases.');
