const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict'),{JSDOM}=require('jsdom');
const dom=new JSDOM(fs.readFileSync('dist/index.html','utf8'),{url:'https://flow.test/',runScripts:'outside-only'}),w=dom.window,d=w.document;w.scrollTo=()=>{};w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(){this.open=false};let error;w.addEventListener('error',e=>error=e.error);for(const node of d.querySelectorAll('script[src]'))vm.runInContext(fs.readFileSync('dist/'+node.getAttribute('src'),'utf8'),dom.getInternalVMContext(),{filename:node.getAttribute('src')});const r=s=>vm.runInContext(s,dom.getInternalVMContext()),snapshot=()=>r('JSON.stringify(state)'),click=q=>{const e=d.querySelector(q);assert(e,q);assert(!e.disabled,q);e.click();assert.ifError(error)},input=(q,value)=>{const e=d.querySelector(q);assert(e,q);if(e.type==='checkbox')e.checked=value;else e.value=value;e.dispatchEvent(new w.Event('input',{bubbles:true}));assert.ifError(error)};
click('[data-game-fallback6="letna"]');click('#gameOpenAddress6');assert(d.querySelector('#modalContent').textContent.includes('Receptura kávy'));click('#uxOpenNext11');click('#openConfirm');click('#close');assert(d.querySelector('#gameCafeCrew6'));click('#gameCafeSupply6');click('#gameSupplierPreview6');click('#confirmAction');assert.equal(r('cafeCoffeeStatus6("letna","blend-1").code'),'scheduled');assert.equal(d.querySelector('#gameCafeSupply6').textContent,'Upravit dodávky');
for(let i=0;i<2;i++){click('#gameNext6');click('#gameDigest6');assert.equal(r('weeklyDigest6().items.filter(x=>x.key.startsWith("coffee-supplier-")).length'),0);click('#gameDigest6');click('#digestContinue6');}assert.equal(r('state.week'),3);assert.equal(r('state.stores.length'),0);
// A reserved person can be released before recruitment, with shifts and import kept consistent.
click('#gameCafeCrew6');assert(d.querySelector('#modalContent').textContent.includes('Tým přípravy'));assert(!/undefined|NaN/.test(d.querySelector('#modalContent').textContent));const cash=r('state.cash'),released=r('state.opening6.projects[0].people.find(x=>x.contract===1).pid'),retained=r('state.opening6.projects[0].people.find(x=>x.contract===2).pid');input('#openingTeamShift6-2',0);input('[data-opening-person6="'+released+'"]',false);click('#openingTeamSave6');assert.equal(r('state.cash'),cash);assert.equal(r('state.opening6.projects[0].people.length'),1);assert.equal(r('state.opening6.projects[0].need'),2);assert(r('state.baristaCandidates.some(p=>p.pid==='+JSON.stringify(released)+')'));assert.equal(r('validateSave(JSON.parse(JSON.stringify(state))).opening6.projects[0].need'),2);assert.equal(JSON.parse(w.localStorage.getItem('kavarna-v5')).opening6.projects[0].blueprint.shifts[2],0);
// Invalid coverage disables commit; model rejects atomically. A stale quote cannot reserve a different team.
input('#openingTeamShift6-2',1);assert(d.querySelector('#openingTeamSave6').disabled);const before=snapshot();assert.throws(()=>r('setOpeningTeam6(state.opening6.projects[0].id,{shifts:[1,1,1],pids:['+JSON.stringify(retained)+']})'));assert.equal(snapshot(),before);r('var fp=state.opening6.projects[0],fd={shifts:[1,1,0],pids:fp.people.map(p=>p.pid)},fq=openingTeamQuote6(fp.id,fd)');assert.equal(snapshot(),before);r('fq.week--');assert.throws(()=>r('setOpeningTeam6(fp.id,fd,fq)'));assert.equal(snapshot(),before);
input('[data-opening-person6="'+released+'"]',true);click('#openingTeamSave6');assert.equal(r('state.cash'),cash);assert.equal(r('fp.need'),3);assert.equal(r('fp.people.length'),2);click('#close');click('[data-game-page6="crew"]');assert(d.querySelector('#content').textContent.includes('Týmy připravovaných kaváren'));click('[data-opening-team6]');assert(d.querySelector('#openingTeamSave6'));click('#close');click('#gameBackToWorld6');click('[data-game-fallback6="letna"]');
// Historical opening links land on the exact project without payments or changing archived messages.
click('#gameDigest6');const h=r('JSON.stringify(weeklyDigest6())'),openingKey=r('weeklyDigest6().items.find(x=>x.key.startsWith("opening-")).key');assert.equal(d.querySelectorAll('[data-digest-open6="'+openingKey+'"]').length,1);click('[data-digest-open6="'+openingKey+'"]');assert(d.querySelector('#openingTeamManage6'));assert.equal(r('JSON.stringify(weeklyDigest6())'),h);assert.equal(r('state.cash'),cash);click('#close');
// Existing supplier edits never charge a second signing fee; enabling, budget blocks and recovery are reflected immediately.
r('setCoffeeAgreement6(state.bootstrap6.suppliers[0].id,{enabled:false,target:25,budget:20000,reserve:1});render()');assert.equal(r('cafeCoffeeStatus6("letna","blend-1").code'),'paused');click('#gameCafeSupply6');input('#supplierEditEnabled6',true);click('#supplierEditSave6');assert.equal(r('state.cash'),cash);assert.equal(r('cafeCoffeeStatus6("letna","blend-1").code'),'scheduled');click('#gameNext6');assert(!d.querySelector('#modal').open);click('#gameDigest6');click('#digestContinue6');assert.equal(r('state.week'),4);r('setCoffeeAgreement6(state.bootstrap6.suppliers[0].id,{enabled:true,target:25,budget:0,reserve:1});render()');assert.equal(r('cafeCoffeeStatus6("letna","blend-1").code'),'budget');click('#gameNext6');click('#gameDigest6');const key=r('weeklyDigest6().items.find(x=>x.key.startsWith("coffee-supplier-")).key'),pay=r('state.cash');click('[data-digest-open6="'+key+'"]');assert(d.querySelector('#supplierEditSave6'));input('#supplierEditBudget6',20000);click('#supplierEditSave6');assert.equal(r('state.cash'),pay);click('#gameDigest6');assert(d.querySelector('#modalContent').textContent.includes('Vyřízeno nebo už není aktuální'));click('#digestContinue6');click('#gameNext6');click('#gameDigest6');assert.equal(r('state.bootstrap6.orders.length'),1);assert.equal(r('cafeCoffeeStatus6("letna","blend-1").code'),'transit');click('#digestContinue6');const recruitment=r('fp.recruitment');assert.equal(recruitment,12000);click('#gameNext6');assert(!d.querySelector('#modal').open);click('#gameDigest6');click('#digestContinue6');assert.equal(r('state.stores.length'),1);assert.equal(r('cafeCoffeeStatus6("letna","blend-1").code'),'stock');assert.equal(r('fp.recruitment'),recruitment);assert.equal(r('state.stores[0].crew.employees.length'),2);click('#gameCafeCrew6');assert(d.querySelector('[data-barista-edit]'));assert.equal(r('crewSelected5'),'letna');assert(r('validateSave(JSON.parse(JSON.stringify(state)))'));
console.log('PASS: real 69-script founder flow at week three: editable/releasable reservations and shifts, no premature fees, pure/stale/invalid coverage, persisted/importable team, people page and city list, coffee states and exact report destinations, unique actions, supplier edit/resume without duplicate fees, budget resolution, paid delivery and hired roster once.');w.close();
