import assert from 'node:assert/strict';
import {T,buildCityScene,buildCafeScene,addressStatus,floorPoint,animateWorld,setWorldNight,setCafeActors,sceneStats,disposeWorld} from '../source/game-scene.mjs';
import {occupiedCells,walkPath,workerRoute,guestRoute,seatPositions} from '../source/game-navigation.mjs';
const floor={width:8,height:6,items:[{id:'counter',kind:'counter',x:3,y:2},{id:'espresso',kind:'espresso',x:3,y:0},{id:'grinder',kind:'grinder',x:4,y:0},{id:'pickup',kind:'pickup',x:5,y:2},{id:'sink',kind:'sink',x:5,y:0},{id:'storage',kind:'storage',x:6,y:0},...Array.from({length:6},(_,i)=>({id:'table-'+i,kind:'table',x:(i%3)*3,y:3+Math.floor(i/3)}))]};
const snapshot={city:'Praha',locations:Array.from({length:9},(_,i)=>({id:'lot-'+i,name:'Adresa '+i})),stores:[{id:'lot-0',color:'#3355aa'}],opening:[{id:'opening-1',location:'lot-1',status:'active'}],rivals:[{id:'rival-1',locations:['lot-2']}],roasters:[{id:'roaster-1',name:'Pražírna'}],bakeries:[{id:'bakery-1',name:'Pekárna'}],offices:[{id:'office-1',name:'Centrála'}],warehouses:[{id:'warehouse-1',name:'Sklad'}],vehicles:[{id:'van-1',name:'Vlastní vůz',driver:null,routeEnabled:false,lastUnits:0},{id:'van-2',name:'Zaplněná trasa',driver:'Jana',routeEnabled:true,lastUnits:100}]};
const before=JSON.stringify(snapshot),city=buildCityScene(snapshot);assert.equal(JSON.stringify(snapshot),before);assert.equal(sceneStats(city).objects.length,15);assert(sceneStats(city).meshes>80);assert(sceneStats(city).vertices>15000);assert.equal(addressStatus(snapshot,'lot-0').kind,'owned');assert.equal(addressStatus(snapshot,'lot-1').kind,'opening');assert.equal(addressStatus(snapshot,'lot-2').kind,'rival');assert.equal(addressStatus(snapshot,'lot-3').kind,'free');city.scene.updateMatrixWorld(true);
const camera=new T.PerspectiveCamera(42,1,.1,300);camera.position.set(47,39,49);camera.lookAt(0,0,4);camera.updateMatrixWorld();const ray=new T.Raycaster();for(const obj of city.objects.filter(o=>o.userData.kind==='address')){const origin=obj.position.clone().add(new T.Vector3(0,25,0));ray.set(origin,new T.Vector3(0,-1,0));const hits=ray.intersectObjects(city.objects,true);assert(hits.length);let o=hits[0].object;while(o&&!o.userData.kind)o=o.parent;assert.equal(o.userData.id,obj.userData.id,'A real roof ray must pick this address');const p=obj.userData.anchor.clone().project(camera);assert(Number.isFinite(p.x)&&Number.isFinite(p.y));}
setWorldNight(city,true);assert.equal(city.sun.intensity,.55);assert(city.p.glass.emissiveIntensity>0);assert(city.lights.every(l=>l.intensity>0));animateWorld(city,20);const parked=city.actors.find(a=>a.vehicle==='van-1'),moving=city.actors.find(a=>a.vehicle==='van-2');assert.equal(parked.mesh.position.x,parked.parking.x);const start=moving.mesh.position.clone();animateWorld(city,30);assert(!moving.mesh.position.equals(start));assert.equal(JSON.stringify(snapshot),before);
const occupied=occupiedCells(floor);for(const path of [walkPath(floor,{x:0,y:5},{x:7,y:5}),guestRoute(floor),...Array.from({length:7},(_,i)=>workerRoute(floor,i))]){assert(path.length);for(const p of path)assert(!occupied.has(p.x+','+p.y));for(let i=1;i<path.length;i++)assert(Math.abs(path[i].x-path[i-1].x)+Math.abs(path[i].y-path[i-1].y)<=1,'Every route segment follows a walkable grid edge');}assert.equal(seatPositions(floor).length,24);
const cafe=buildCafeScene({slot:{workers:2,queue:3,occupied:8,served:2},crew:[{id:'p1',name:'Jana'},{id:'p2',name:'Pavel'}]},floor);assert.equal(cafe.objects.filter(o=>o.userData.kind==='floor').length,48);assert.equal(cafe.objects.filter(o=>o.userData.kind==='furniture').length,12);assert.equal(cafe.actors.filter(a=>a.kind==='worker').length,2);assert.equal(cafe.objects.find(o=>o.userData.id==='p1').userData.title,'Jana');animateWorld(cafe,15);for(const a of cafe.actors){assert(Number.isFinite(a.mesh.position.x));if(a.seat){assert.equal(a.mesh.position.z,floorPoint(a.seat.x,a.seat.y).z+a.seat.offset);}else{const p=a.mesh.position,x=p.x/1.15+3.5,y=p.z/1.15+2.5;assert(!occupied.has(Math.round(x)+','+Math.round(y)));}}
cafe.scene.updateMatrixWorld(true);const target=cafe.objects.find(o=>o.userData.id==='espresso'),pos=target.getWorldPosition(new T.Vector3());ray.set(pos.clone().add(new T.Vector3(0,10,0)),new T.Vector3(0,-1,0));const hits=ray.intersectObjects(cafe.objects,true);let obj=hits[0].object;while(obj&&!obj.userData.kind)obj=obj.parent;assert.equal(obj.userData.id,'espresso');
const geometries=new Set();cafe.scene.traverse(o=>{if(o.geometry)geometries.add(o.geometry)});setCafeActors(cafe,{slot:{workers:0,queue:0,occupied:0,served:0},crew:[]});assert.equal(cafe.actors.length,0);assert.equal(cafe.objects.filter(o=>o.userData.kind==='worker').length,0);assert(cafe.actorPool.every(a=>!a.mesh.visible));let disposed=0;geometries.forEach(g=>g.addEventListener('dispose',()=>disposed++));disposeWorld(cafe);assert.equal(disposed,geometries.size);disposeWorld(city);
console.log('PASS: real Three geometry, address/roof and station rays, finite camera projections, day/night materials, parked/loaded real vans, 48 tiles, named crew, exact furniture seating and obstacle-respecting worker/guest routes, actor reuse/removal, disposal. GPU rendering is not covered.');
