const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');const c=vm.createContext({Intl,console});for(const f of ['engine','tycoon','empire','operations','reports','supply','crew','craft','studio','business','guests'])vm.runInContext(fs.readFileSync('dist/'+f+'.js','utf8'),c);const r=s=>vm.runInContext(s,c),snap=()=>r('JSON.stringify(state)'),near=(a,b)=>assert(Math.abs(a-b)<.02,`${a} != ${b}`);let passed=0;
function own(){r('openStore("letna");state.cash=5000000;hireCandidate("letna","candidate-0")')}
function test(name,fn){r('state=fresh()');fn();r('validateSave(JSON.parse(JSON.stringify(state)))');passed++;console.log('PASS:',name)}
function conservation(){r('for(const s of state.stores){var g=s.guests5.last;if(!g)continue;if(g.served!==s.last.served||g.arrivals!==s.last.served+s.last.lost)throw Error("visit totals");for(const a of g.groups)if(a.served+a.lostQueue+a.lostSeats+a.lostClosing+a.lostStock!==a.arrivals||a.returned>a.served)throw Error("cohort totals");if(g.regulars!==g.before+g.gained-g.departed)throw Error("customer ledger")}')}
test('founder starts without stores, reviews or invented customer history',()=>{assert.equal(r('state.cash'),650000);assert.equal(r('state.stores.length'),0);const before=snap();assert.throws(()=>r('nextWeek()'));assert.equal(snap(),before);});
test('opening starts five empty cohorts without fabricated reviews',()=>{own();assert.equal(r('state.stores[0].guests5.cohorts.length'),5);assert.equal(r('state.stores[0].guests5.reviews.length'),0);assert.equal(r('state.stores[0].guests5.cohorts.reduce((n,c)=>n+c.regulars,0)'),0);});
test('real arrivals, queue losses, physical sales and groups conserve all visits',()=>{own();r('nextWeek()');conservation();assert(r('state.stores[0].guests5.last.served>0'));assert.equal(r('performanceReport5("guests",1).rows.length'),1);});
test('first-week regular visits are zero but satisfied new guests can join',()=>{own();r('nextWeek()');assert.equal(r('state.stores[0].guests5.last.returned'),0);assert(r('state.stores[0].guests5.last.gained>0'));});
test('regular visits appear later and cannot exceed actual served visits',()=>{own();r('for(let i=0;i<8;i++)nextWeek()');conservation();assert(r('state.stores[0].guests5.last.returned>0'));assert(r('state.stores[0].guests5.last.returned<=state.stores[0].last.served'));});
test('customer demand query never edits persistent guests, money or reviews',()=>{own();const before=r('JSON.stringify(state.stores[0].guests5)'),cash=r('state.cash');r('var d={demand:1000,menu:menuSummary(state.stores[0])};guestDemand5(state.stores[0],d)');assert.equal(r('JSON.stringify(state.stores[0].guests5)'),before);assert.equal(r('state.cash'),cash);});
test('cohort pricing corrects the existing price response without charging its effect twice',()=>{own();r('var s=state.stores[0],d={demand:1000,menu:{price:loc(s.id).ideal*1.2}};guestDemand5(s,d)');assert(r('d.guests5.effect>.95'));assert(r('d.guests5.groups.find(g=>g.id==="student").value<d.guests5.groups.find(g=>g.id==="tourist").value'));});
test('community location attracts more neighbours and office location more office visitors',()=>{own();r('openStore("karlin");nextWeek()');assert(r('state.stores.find(s=>s.id==="letna").guests5.last.groups.find(g=>g.id==="community").arrivals>state.stores.find(s=>s.id==="letna").guests5.last.groups.find(g=>g.id==="office").arrivals'));assert(r('state.stores.find(s=>s.id==="karlin").guests5.last.groups.find(g=>g.id==="office").arrivals>state.stores.find(s=>s.id==="karlin").guests5.last.groups.find(g=>g.id==="community").arrivals'));conservation();});
test('students value the same price less than tourists; specialists weigh coffee most',()=>{own();r('nextWeek();var gs=state.stores[0].guests5.last.groups');assert(r('gs.find(g=>g.id==="student").scores.value<gs.find(g=>g.id==="tourist").scores.value'));assert.equal(r('GUEST_TYPES5.specialty.weights.coffee'),.5);});
test('different patience participates in queue simulation, not just report text',()=>{own();r('var s=state.stores[0];var d={demand:1200,capacity:500,menu:{hasDrinks:true,price:90}};guestDemand5(s,d);var service=simulateService5(s,d)');assert(r('service.days.flatMap(d=>d.timeline).some(p=>p.guests5.find(g=>g.id==="office").lostQueue>0)'));assert.equal(r('GUEST_TYPES5.office.patience'),2);assert.equal(r('GUEST_TYPES5.community.patience'),5);});
test('takeaway floor loses seated visitors and accounts for all of them',()=>{own();r('state.stores[0].floor.items=state.stores[0].floor.items.filter(i=>!STATIONS5[i.kind].seats);state.stores[0].seats=0;nextWeek()');conservation();assert(r('state.stores[0].guests5.last.groups.some(g=>g.lostSeats>0)'));});
test('no coffee prevents real returning visits, churns regulars and records stock complaints',()=>{own();r('nextWeek();state.batches=[];state.roasters.forEach(r=>r.auto=false);nextWeek()');conservation();assert.equal(r('state.stores[0].guests5.last.served'),0);assert.equal(r('state.stores[0].guests5.last.returned'),0);assert(r('state.stores[0].guests5.last.groups.every(g=>g.quality===null)'));assert(r('state.stores[0].guests5.reviews.filter(r=>r.week===2).every(r=>r.stars<=2)'));assert(r('state.stores[0].guests5.last.departed>0'));assert(r('state.stores[0].guests5.last.groups.some(g=>g.lostStock>0&&g.reason.includes("Káva"))'));});
test('actual bad coffee quality reaches the recorded customer experience',()=>{own();r('state.batches=[{blend:"blend-1",kg:200,quality:35,cost:300,zone:"Praha",roastedWeek:state.week}];state.roasters.forEach(r=>r.auto=false);nextWeek()');assert(r('state.stores[0].guests5.last.groups.every(g=>g.quality===35)'));conservation();});
test('reviews are representative weekly samples with capped immutable evidence',()=>{own();r('nextWeek()');assert(r('state.stores[0].guests5.reviews.length>0&&state.stores[0].guests5.reviews.length<=3'));assert(r('state.stores[0].guests5.reviews.every(r=>r.week===1&&r.stars>=1&&r.stars<=5)'));});
test('reply pays once, records expense and preserves original stars and text',()=>{own();r('nextWeek();var s=state.stores[0],review=s.guests5.reviews[0],text=review.text,stars=review.stars,cash=state.cash;replyGuest5(s.id,review.id,"reply")');near(r('state.cash'),r('cash-750'));assert.equal(r('review.text'),r('text'));assert.equal(r('review.stars'),r('stars'));assert.equal(r('review.reply.cost'),750);const before=snap();assert.throws(()=>r('replyGuest5(s.id,review.id,"reply")'));assert.equal(snap(),before);});
test('compensation cannot buy more than three future goodwill points',()=>{own();r('nextWeek();var s=state.stores[0],review=s.guests5.reviews[0];replyGuest5(s.id,review.id,"compensate");var c=s.guests5.cohorts.find(c=>c.id===review.group)');assert.equal(r('c.goodwill'),3);r('nextWeek()');assert.equal(r('c.goodwill'),0);});
test('stale or unaffordable replies reject before any mutation',()=>{own();r('nextWeek();var s=state.stores[0],review=s.guests5.reviews[0],quote=guestReplyQuote5(s.id,review.id,"reply");state.cash-=1');const before=snap();assert.throws(()=>r('replyGuest5(s.id,review.id,"reply",quote)'));assert.equal(snap(),before);r('state.cash=100');const poor=snap();assert.throws(()=>r('replyGuest5(s.id,review.id,"reply")'));assert.equal(snap(),poor);});
test('save from 05.6 migrates without money change or fictitious old reviews',()=>{own();r('nextWeek();var old=JSON.parse(JSON.stringify(state));delete old.stores[0].guests5;var cash=old.cash;old.performance5.forEach(h=>h.records=h.records.filter(r=>r.kind!=="guests"));var v=validateSave(old)');near(r('v.cash'),r('cash'));assert.equal(r('v.stores[0].guests5.reviews.length'),0);assert.equal(r('v.stores[0].guests5.history.length'),0);});
test('fresh family after a long game sets cohort birth to week one',()=>{own();r('for(let i=0;i<5;i++)nextWeek();state=fresh("family")');assert.equal(r('state.stores[0].guests5.since'),1);assert.equal(r('state.stores[0].guests5.reviews.length'),0);});
test('customer and report reads are pure and preserve archived reviews',()=>{own();r('nextWeek()');const before=snap();r('performanceReport5("guests",4);guestRating5(state.stores[0])');assert.equal(snap(),before);});
test('B2B preview includes customer reviews without leaking changes',()=>{own();r('buyOffice("studio");setDepartment("sales",1);state.reputation=80;var p=negotiateBusiness5("hub",{blend:"blend-1",kg:10,price:500,weeks:12,terms:2})');const before=snap();const f=r('previewBusiness5(p.id,4)');assert.equal(snap(),before);r('acceptBusiness5(p.id);for(let i=0;i<4;i++)nextWeek()');near(r('state.cash'),f.series.at(-1).cash);conservation();});
test('malformed guest counts, stars, replies, groups and histories fail validation',()=>{own();r('nextWeek()');for(const m of ['v.stores[0].guests5.cohorts[0].regulars=-1','v.stores[0].guests5.cohorts[0].goodwill=4','v.stores[0].guests5.reviews[0].stars=6','v.stores[0].guests5.reviews[0].reply={week:1,choice:"reply",cost:0}','v.stores[0].guests5.last.groups[0].arrivals+=1','v.stores[0].guests5.last.served+=1','v.stores[0].guests5.history[0].week=50','v.stores[0].guests5.cohorts[1].id="office"'])assert.throws(()=>r(`var v=JSON.parse(JSON.stringify(state));${m};validateSave(v)`));});
test('a full regular cohort remains capped with a balanced customer ledger',()=>{own();r('state.stores[0].guests5.cohorts.forEach(c=>c.regulars=5000);nextWeek()');conservation();assert(r('state.stores[0].guests5.cohorts.every(c=>c.regulars<=5000)'));});
test('60 weeks of real founder play stays viable without injected capital',()=>{r('openStore("letna");hireCandidate("letna","candidate-0")');for(let i=0;i<60;i++){r('if(state.roasters[0].condition<65&&state.cash>weeklyFixed()*3+18000)maintainRoaster("roaster-1");nextWeek();validateSave(JSON.parse(JSON.stringify(state)))');assert(!r('state.over'));conservation();}assert(r('state.stores[0].guests5.history.length<=26'));assert(r('state.stores[0].guests5.reviews.length<=30'));assert(r('state.cash>100000'));});
test('maximum 111-cafe network and eight roasters keep every customer report saveable',()=>{r('state.cash=200000000;state.stores=LOCATIONS.map(l=>makeStore(l.id));state.studio5.opening=false;state.rivals.forEach(r=>{r.bankrupt=true;r.stores=[]});for(const s of state.stores)hire(s.id,0);while(state.roasters.length<8)buyRoaster("artisan","Výroba "+state.roasters.length);for(const q of state.roasters)hire(q.id,0,"roaster");nextWeek()');conservation();assert(r('state.performance5.at(-1).records.length>350'));assert.equal(r('performanceReport5("guests",1).rows.length'),111);});
console.log(`${passed} guest scenarios passed.`);
