const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');const c=vm.createContext({Intl,console});for(const f of ['engine','tycoon','empire','operations','reports','supply','crew','craft','studio','business','guests','branding','property','rivals','seasons','procurement','management'])vm.runInContext(fs.readFileSync('dist/'+f+'.js','utf8'),c);const r=s=>vm.runInContext(s,c),snap=()=>r('JSON.stringify(state)'),near=(a,b)=>assert(Math.abs(a-b)<.02,`${a} != ${b}`);let passed=0;
function test(name,fn){r('state=fresh()');fn();r('validateSave(JSON.parse(JSON.stringify(state)))');passed++;console.log('PASS:',name);}
function own(){r('openStore("letna");hireCandidate("letna","candidate-0")');}
function funded(){own();r('state.cash=6000000;buyOffice("studio");setDepartment("sales",1);setDepartment("finance",1);hireExecutive5("purchasing",state.talents[0].pid)');}
function policy(extra=''){r(`setPurchasingPolicy5({...managementPolicy5(),enabled:true,budget:100000,approval:100000,reserve:1,cover:1,${extra}})`);}
test('neutral founder retains 650k, no selected cafe, no new charge and no enabled mandates',()=>{assert.equal(r('state.cash'),650000);assert.equal(r('state.organization.executives.purchasing.manager'),null);assert(!r('state.management5.policy.enabled||state.management5.boardEnabled'));const s=snap();r('managementExceptions5()');assert.equal(snap(),s);assert.throws(()=>r('nextWeek()'));assert.equal(snap(),s);});
test('old v5 save adds neutral purchasing role, records and per-store policies without charges',()=>{own();r('var cash=state.cash,v=JSON.parse(JSON.stringify(state));delete v.management5;delete v.stores[0].management5;delete v.organization.executives.purchasing;delete v.organization.policies.purchasing;v=validateSave(v)');near(r('v.cash'),r('cash'));assert.equal(r('v.management5.decisions.length'),0);assert(!r('v.stores[0].management5.enabled'));});
test('director requires an office and trade staff and preserves money on rejected hire',()=>{own();const s=snap();assert.throws(()=>r('hireExecutive5("purchasing",state.talents[0].pid)'));assert.equal(snap(),s);r('state.cash=2000000;buyOffice("studio")');const t=snap();assert.throws(()=>r('hireExecutive5("purchasing",state.talents[0].pid)'));assert.equal(snap(),t);});
test('hiring costs exactly 20k and director consumes a seat and actual weekly salary',()=>{own();r('state.cash=6000000;buyOffice("studio");setDepartment("sales",1);var cash=state.cash,fixed=weeklyFixed(),seats=usedSeats();hireExecutive5("purchasing",state.talents[0].pid);var salary=state.organization.executives.purchasing.manager.salary*1.35');near(r('state.cash'),r('cash-20000'));near(r('weeklyFixed()-fixed'),r('salary'));assert.equal(r('usedSeats()'),r('seats+1'));r('nextWeek()');near(r('state.history.at(-1).detail.directors'),r('salary'));});
test('disabled purchasing authority makes no supplier purchases',()=>{funded();r('state.green=[];nextWeek()');assert.equal(r('state.procurement5.orders.length'),0);});
test('enabled mandate without director creates an actionable exception and no purchase',()=>{own();policy();r('state.green=[];nextWeek()');assert.equal(r('state.procurement5.orders.length'),0);assert(r('managementExceptions5().some(x=>x.target==="Nákup")'));});
test('need and supplier comparisons are read-only and account for incoming shipments',()=>{funded();policy();r('state.green=[]');const s=snap();r('var a=purchasingOptions5("brazil");managementExceptions5()');assert.equal(snap(),s);r('orderBeans("brazil",2500);var b=purchasingOptions5("brazil")');assert(r('b.options.every(x=>x.needed===0)'));});
test('two automatic roasters in one city do not duplicate its coffee requirement',()=>{funded();r('var a=managementNeeds5().brazil;buyRoaster("artisan","Další","Praha");var b=managementNeeds5().brazil');near(r('a'),r('b'));});
test('manual production has no invented automatic purchase requirement',()=>{funded();r('state.roasters.forEach(r=>r.auto=false)');near(r('Object.values(managementNeeds5()).reduce((a,b)=>a+b,0)'),0);policy();r('state.green=[];nextWeek()');assert.equal(r('state.procurement5.orders.length'),0);});
test('automatic purchasing books physical shipments and whole commitment fits its weekly limit',()=>{funded();policy();r('state.green=[];nextWeek()');assert(r('state.procurement5.orders.length>0'));assert(r('state.management5.spent.total<=100000'));assert(r('state.management5.decisions.some(r=>r.kind==="purchase")'));assert(r('state.procurement5.orders.every(o=>o.received===null)'));assert(r('state.organization.reports.find(r=>r.role==="purchasing").status==="done"'));});
test('credit commitment counts full cost while cash waits until receipt and maturity',()=>{funded();policy('terms:2');r('state.green=[];nextWeek();var purchases=state.procurement5.orders');assert(r('purchases.length>0&&purchases.every(o=>o.paid===0)'));near(r('state.management5.spent.total'),r('purchases.reduce((n,o)=>n+o.cost,0)'));r('setPurchasingPolicy5({...state.management5.policy,enabled:false});for(let i=0;i<10;i++)nextWeek()');assert(r('purchases.every(o=>o.received!==null&&o.paid===o.cost)'));});
test('minimum quality rejects cheaper low-quality parties and explains blocked origins',()=>{funded();policy('quality:99');r('state.green=[];nextWeek()');assert.equal(r('state.procurement5.orders.length'),0);assert(r('managementExceptions5().some(x=>x.text.includes("Žádný nákup"))'));});
test('supplier proposals do not spend money before explicit approval',()=>{funded();policy('approval:0');r('state.green=[];nextWeek()');assert.equal(r('state.procurement5.orders.length'),0);assert(r('state.management5.proposals.some(x=>x.status==="pending")'));const s=snap();r('managementExceptions5()');assert.equal(snap(),s);});
test('end-of-turn proposals are current and approval places and pays exactly once',()=>{funded();policy('approval:0');r('state.green=[];nextWeek();var x=state.management5.proposals.find(x=>x.status==="pending"),cash=state.cash;decideManagementPurchase5(x.id,true)');near(r('state.cash'),r('cash-x.quote.cost'));assert.equal(r('x.status'),'approved');const s=snap();assert.throws(()=>r('decideManagementPurchase5(x.id,true)'));assert.equal(snap(),s);});
test('changed cash rejects stale approval atomically and refresh prepares reviewable new quote',()=>{funded();policy('approval:0');r('state.green=[];nextWeek();var x=state.management5.proposals.find(x=>x.status==="pending");state.cash-=1');const s=snap();assert.throws(()=>r('decideManagementPurchase5(x.id,true)'));assert.equal(snap(),s);r('refreshManagementProposal5(x.id);decideManagementPurchase5(x.id,true)');assert.equal(r('x.status'),'approved');});
test('changing or removing the author prevents approval while rejection is free',()=>{funded();policy('approval:0');r('state.green=[];nextWeek();var x=state.management5.proposals.find(x=>x.status==="pending");fireExecutive5("purchasing")');const s=snap();assert.throws(()=>r('decideManagementPurchase5(x.id,true)'));assert.equal(snap(),s);r('var cash=state.cash;decideManagementPurchase5(x.id,false)');near(r('state.cash'),r('cash'));});
test('policy change expires pending proposals and zero weekly budget requires approval',()=>{funded();policy('budget:0');r('state.green=[];nextWeek()');assert.equal(r('state.procurement5.orders.length'),0);assert(r('state.management5.proposals.some(x=>x.status==="pending")'));policy();assert(!r('state.management5.proposals.some(x=>x.status==="pending")'));});
test('higher organizational reserve also constrains purchasing policy',()=>{funded();policy();r('state.organization.policies.purchasing.reserve=8;state.cash=weeklyFixed()*3;state.green=[];nextWeek()');assert.equal(r('state.procurement5.orders.length'),0);});
test('existing scheduled and estate shipments prevent repeat orders for covered origins',()=>{funded();policy();r('orderBeans("brazil",2500);orderBeans("robusta",2500);nextWeek()');assert.equal(r('state.procurement5.orders.length'),0);});
test('purchase evidence later freezes actual delivery quality and date',()=>{funded();policy();r('state.green=[];nextWeek();setPurchasingPolicy5({...state.management5.policy,enabled:false});for(let i=0;i<8;i++)nextWeek();var row=state.management5.decisions.find(x=>x.kind==="purchase"),o=state.procurement5.orders.find(o=>o.id===row.target)');near(r('row.actual.quality'),r('o.quality'));near(r('row.actual.kg'),r('o.kg'));assert.equal(r('row.actual.week'),r('o.received'));const evidence=r('JSON.stringify(row)');r('for(let i=0;i<3;i++)nextWeek()');assert.equal(r('JSON.stringify(row)'),evidence);});
test('local manager comparison restores all state and active supply trace',()=>{own();r('var traceBefore={sentinel:true};supplyTrace5=traceBefore');const s=snap();r('managerEstimate5("letna",{kind:"price",value:5})');assert.equal(snap(),s);assert(r('supplyTrace5===traceBefore'));r('supplyTrace5=null');});
test('smart manager respects disabled price, marketing, staffing and protected roster',()=>{own();r('var s=state.stores[0];s.auto={price:false,marketing:false,staff:false};s.daily.auto=false;s.crew.manual=true;setSmartManager5(s.id,{enabled:true,budget:5000,reserve:3,goal:"profit"});var menu=JSON.stringify(s.menu),shifts=JSON.stringify(s.daily.shifts),roster=JSON.stringify(s.crew.roster),marketing=s.marketing;nextWeek()');assert.equal(r('JSON.stringify(s.menu)'),r('menu'));assert.equal(r('JSON.stringify(s.daily.shifts)'),r('shifts'));assert.equal(r('JSON.stringify(s.crew.roster)'),r('roster'));near(r('s.marketing'),r('marketing'));assert(!r('state.management5.decisions.find(x=>x.kind==="store").changed'));});
test('smart manager selects only an allowed profitable local variant and records observed week',()=>{funded();r('var s=state.stores[0];s.price=200;shiftMenu(s,200-s.menuAnchor);s.menuStats=menuSummary(s);s.price=Math.round(s.menuStats.price);s.menuAnchor=s.price;setSmartManager5(s.id,{enabled:true,budget:3000,reserve:2,goal:"profit"});nextWeek();var row=state.management5.decisions.find(r=>r.kind==="store")');assert(r('row.expected.profit>=row.baseline.profit-.02'));near(r('row.actual.profit'),r('s.last.profit'));assert.equal(r('row.actual.served'),r('s.last.served'));assert(r('state.supply5.last.cities.length>0'));});
test('unassigned smart cafe holds changes and raises a management exception',()=>{own();r('state.stores[0].manager=null;setSmartManager5("letna",{enabled:true,budget:5000,reserve:3,goal:"service"});nextWeek()');assert(!r('state.management5.decisions.some(r=>r.kind==="store")'));assert(r('managementExceptions5().some(a=>a.text.includes("Chytré řízení"))'));});
test('changing next targets does not rewrite past board goals or manager evidence',()=>{own();r('setSmartManager5("letna",{enabled:true,budget:5000,reserve:3,goal:"profit"});nextWeek();var before=JSON.stringify(state.management5.history[0]),decision=JSON.stringify(state.management5.decisions[0]);setBoardGoals5({profit:100000,quality:99,reserve:8,stores:20,lost:0})');assert.equal(r('JSON.stringify(state.management5.history[0])'),r('before'));assert.equal(r('JSON.stringify(state.management5.decisions[0])'),r('decision'));});
test('governance report and all exception queries are pure and expose actual goals',()=>{own();r('nextWeek()');const s=snap();r('var report=performanceReport5("governance",1);managementExceptions5()');assert.equal(snap(),s);near(r('report.rows[0].values.achieved'),r('state.management5.history.at(-1).achieved'));near(r('report.rows[0].values.profit'),r('state.history.at(-1).profit'));});
test('optional board mandate blocks risky votes with explicit reasons and preserves majority override',()=>{funded();r('nextWeek();setBoardGoals5({profit:10000000,quality:99,reserve:8,stores:3,lost:0});var before=JSON.stringify(state),p=proposal("expansion")');assert(!r('p.passed'));assert(r('p.votes.some(v=>v.reason.includes("Mandát boardu"))'));assert.equal(snap(),r('before'));r('board("expansion",true)');assert.equal(r('state.expansionBudget'),3000000);});
test('turned-off board mandate leaves the original voting model unchanged',()=>{funded();r('nextWeek();var a=JSON.stringify(MANAGEMENT_BASE5.proposal("expansion")),b=JSON.stringify(proposal("expansion"))');assert.equal(r('a'),r('b'));});
test('all seven executive reports and identities survive full current validation',()=>{funded();r('setDepartment("hr",1);setDepartment("product",1);setDepartment("it",1);openStore("karlin");openStore("vinohrady");while(state.talents.length<7)state.talents.push(person4(recruitProfile(2)));for(const role of Object.keys(ROLES5))if(!state.organization.executives[role].manager)hireExecutive5(role,state.talents[0].pid);nextWeek()');assert.equal(r('state.organization.reports.length'),7);});
test('malformed policies, goals, proposals, decision evidence and historical scores reject',()=>{funded();policy('approval:0');r('state.green=[];setSmartManager5("letna",{enabled:true,budget:5000,reserve:3,goal:"profit"});nextWeek()');for(const mutation of ['v.management5.policy.reserve=0','v.management5.policy.terms=1','v.management5.policy.quality=101','v.management5.boardEnabled="yes"','v.management5.goals.lost=2','v.stores[0].management5.goal="missing"','v.management5.proposals[0].quote.cost+=1','v.management5.proposals[0].data.supplier="constructor"','v.management5.decisions.find(x=>x.kind==="store").expected.profit="bad"','v.management5.history[0].achieved=99'])assert.throws(()=>r(`var v=JSON.parse(JSON.stringify(state));${mutation};validateSave(v)`));});
test('60 founder weeks with smart local delegation survive without injected capital',()=>{own();r('setSmartManager5("letna",{enabled:true,budget:3000,reserve:3,goal:"profit"})');for(let i=0;i<60;i++){r('if(state.roasters[0].condition<65&&state.cash>weeklyFixed()*3+18000)maintainRoaster("roaster-1");nextWeek();validateSave(JSON.parse(JSON.stringify(state)))');assert(!r('state.over'));}assert.equal(r('state.management5.history.length'),26);assert(r('state.management5.decisions.some(x=>x.kind==="store"&&x.changed)'));});
test('maximum network retains current reports and bounded manager history',()=>{r('state.cash=200000000;state.stores=LOCATIONS.map(l=>makeStore(l.id));state.studio5.opening=false;state.rivals.forEach(r=>{r.bankrupt=true;r.stores=[]});for(const s of state.stores){hire(s.id,0);s.management5.enabled=true;}while(state.roasters.length<8)buyRoaster("artisan","Výroba "+state.roasters.length);nextWeek()');assert.equal(r('performanceReport5("governance",1).rows.length'),1);assert.equal(r('performanceReport5("stores",1).rows.length'),111);assert(r('state.performance5.at(-1).records.length<=600'));assert.equal(r('state.management5.decisions.filter(x=>x.kind==="store").length'),111);});

test('mandatory estate-only ingredients do not trigger purchases of unusable vendor coffee',()=>{funded();r('buyEstate(ESTATES.find(e=>e.origin==="brazil").id);var b=state.blends[0];b.primary="brazil";b.share=100;setCoffeeSources5(b.id,{primarySource:state.estates[0].id,secondarySource:"any",fallback:false});var needs=managementNeeds5()');near(r('needs.brazil'),0);});
test('new same-origin credit shipment invalidates an approval even with unchanged cash',()=>{funded();policy('approval:0,terms:2');r('state.green=[];nextWeek();var x=state.management5.proposals.find(x=>x.status==="pending");buyProcurement5({supplier:"altitude",origin:x.data.origin,kg:200,terms:2,reserve:1})');const s=snap();assert.throws(()=>r('decideManagementPurchase5(x.id,true)'));assert.equal(snap(),s);});
test('higher mandate reserve invalidates an earlier purchase approval',()=>{funded();policy('approval:0');r('state.green=[];nextWeek();var x=state.management5.proposals.find(x=>x.status==="pending");state.organization.policies.purchasing.reserve=8');const s=snap();assert.throws(()=>r('decideManagementPurchase5(x.id,true)'));assert.equal(snap(),s);});
test('combined actual forecast includes enabled delegation without changing live evidence',()=>{funded();policy();r('state.green=[];setSmartManager5("letna",{enabled:true,budget:3000,reserve:2,goal:"profit"})');const s=snap(),forecast=r('supplyForecast5(4,1)');assert.equal(snap(),s);r('for(let i=0;i<4;i++)nextWeek()');near(r('state.cash'),forecast.finalCash);});


test('manual absolute price still reaches the physical menu with smart price authority disabled',()=>{own();r('var s=state.stores[0],old=s.menu.espresso.price;s.price+=20;s.auto.price=false;s.auto.marketing=false;s.auto.staff=false;s.daily.auto=false;setSmartManager5("letna",{enabled:true,budget:5000,reserve:3,goal:"profit"});nextWeek()');near(r('s.menu.espresso.price'),r('old+20'));});


test('raising marketing preserves the reserve for its new recurring cost',()=>{own();r('var s=state.stores[0];s.marketing=0;s.auto.price=false;s.auto.staff=false;setSmartManager5("letna",{enabled:true,budget:5000,reserve:1,goal:"service"});state.cash=weeklyFixed()+500;autoManager(s)');near(r('s.marketing'),0);});
test('local marketing cannot consume cash reserved for nearby supplier maturities',()=>{funded();r('buyProcurement5({supplier:"harbor",origin:"brazil",kg:20,terms:2,reserve:1});while(!state.procurement5.payables.length)nextWeek();var s=state.stores[0];s.marketing=0;s.auto.price=false;s.auto.staff=false;setSmartManager5("letna",{enabled:true,budget:5000,reserve:1,goal:"service"});state.cash=weeklyFixed()+1000;autoManager(s)');near(r('s.marketing'),0);});

console.log(`${passed} management scenarios passed.`);
