const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
const scripts=[...fs.readFileSync('dist/index.html','utf8').matchAll(/<script src="([^"]+)"/g)].map(m=>m[1]).filter(f=>f!=='app.js'&&!f.endsWith('-ui.js')&&f!=='game-renderer.js');
function game(){const c=vm.createContext({console,Intl});for(const file of scripts)vm.runInContext(fs.readFileSync('dist/'+file,'utf8'),c,{filename:file});vm.runInContext('function advance14(){const h=nextWeek();for(const o of [...state.offers])if(staffAssignments().some(a=>a.person.pid===o.pid))resolveOffer(o.id,"match");return h;}',c);return s=>vm.runInContext(s,c);}
const company='state=fresh();state.cash=20000000;startOpening6("cafe",{location:"letna",design:"starter",options:{kind:"legacy",space:"starter"}});signCoffeeAgreement6("local","letna","blend-1",{enabled:true,target:70,budget:40000,reserve:1});for(let i=0;i<6;i++)advance14();var second=LOCATIONS.find(l=>l.city==="Praha"&&!owned(l.id)&&!occupant(l.id)&&!openingReserved6(l.id)).id;startOpening6("cafe",{location:second,design:"starter",options:{kind:"legacy",space:"starter"}});for(let i=0;i<6;i++)advance14();var ids=state.stores.filter(s=>!s.franchise).map(s=>s.id);for(const s of state.stores){s.auto.price=false;s.auto.staff=false;s.auto.marketing=false;}';
let count=0;function test(label,fn){const r=game();fn(r);r('validateSave(JSON.parse(JSON.stringify(state)))');console.log('PASS: '+label);count++;}
test('Old saves migrate neutrally and personal pins alter no economic resources',r=>{r('var old=JSON.parse(JSON.stringify(state));delete old.network14;var text=JSON.stringify(old),v=validateSave(old);delete v.network14;');assert(r('JSON.stringify(old)===text&&JSON.stringify(v)===text'));r(company+'var cash=state.cash,assets=JSON.stringify(state.economy6),history=JSON.stringify(state.history);setNetworkPanel14({metrics:["profit","quality"],issues:["loss","seats"],pins:ids});');assert(r('state.cash===cash&&JSON.stringify(state.economy6)===assets&&JSON.stringify(state.history)===history&&networkPanel14().pins.length===2'));r('networkPin14(ids[0]);');assert(r('state.network14.pins.length===1'));});
test('Comparison uses actual archived totals, coverage and equal-period per-week trend',r=>{r(company+'var before=JSON.stringify(state),a=networkComparison14(4,"Praha","profit","asc","current"),b=performanceReport5("stores",4);');assert(r('JSON.stringify(state)===before&&a.rows.length===2&&a.rows.every(row=>row.values.profit===b.rows.find(x=>x.id===row.id).values.profit)&&a.rows[0].values.profit<=a.rows[1].values.profit'));assert(r('a.rows.every(row=>row.samples===row.points.length&&row.trend===b.rows.find(x=>x.id===row.id).trend)&&networkComparison14(1,"Brno").rows.length===0'));r('var id=ids[1];state.stores=state.stores.filter(s=>s.id!==id);var historical=networkComparison14(4,"all","name","asc","historical");');assert(r('historical.rows.some(x=>x.id===id&&!x.current&&x.samples>0)'));});
test('Shared-stock forecast is pure and does not promise the same coffee twice',r=>{r(company+'state.batches=state.batches.filter(b=>b.zone==="Praha"&&b.blend==="blend-1").slice(0,1);state.batches[0].kg=5;state.deliveryPolicy="planned";var before=JSON.stringify(state),forecast=networkForecast14();');assert(r('JSON.stringify(state)===before&&forecast.reduce((n,x)=>n+x.coffeeKg,0)<=5.000001&&forecast.some(x=>x.stockLost>0)'));});
test('Collective menu quote is pure and exact confirmation changes both real menus once',r=>{r(company+'var before=JSON.stringify(state),q=networkBulkQuote14(ids,"price",{delta:5},0,1);');assert(r('JSON.stringify(state)===before&&q.safe&&q.cost===0&&q.rows.every(x=>x.after)'));r('var cash=state.cash,prices=state.stores.map(s=>s.menu.espresso.price),record=applyNetworkBulk14(ids,"price",{delta:5},0,1,q);');assert(r('state.cash===cash&&state.stores.every((s,i)=>s.menu.espresso.price===prices[i]+5)&&record.rows.length===2&&record.rows.every(x=>x.actual===null)'));const after=r('JSON.stringify(state)');assert.throws(()=>r('applyNetworkBulk14(ids,"price",{delta:5},0,1,q)'),/změnily/);assert.equal(r('JSON.stringify(state)'),after);r('advance14();var frozen=JSON.stringify(state.network14.history[0]);');assert(r('state.network14.history[0].rows.every(x=>x.actual.week===state.week-1&&x.actual.profit===state.stores.find(s=>s.id===x.id).last.profit)'));r('advance14();');assert(r('JSON.stringify(state.network14.history[0])===frozen'));});
test('Equipment purchases include real credits and incremental maintenance in actual ledger',r=>{r(company+'var before=JSON.stringify(state),q=networkBulkQuote14(ids,"equipment",{key:"machine",model:"premium"},1000000,1);');assert(r('JSON.stringify(state)===before&&q.safe&&q.credit>0&&q.cost===q.purchases-q.credit&&q.weeklyChange>0'));r('var cash=state.cash;applyNetworkBulk14(ids,"equipment",{key:"machine",model:"premium"},1000000,1,q);');assert(r('Math.abs(cash-state.cash-q.cost)<.001&&state.stores.every(s=>s.equipment.machine.model==="premium"&&s.equipment.machine.condition===100)'));r('var q2=networkBulkQuote14(ids,"equipment",{key:"machine",model:"premium"},1000000,1);');assert(r('!q2.safe&&q2.cost===0&&q2.rows.every(x=>!x.changed)'));});
test('Limits and reserves block whole actions without partial payments',r=>{r(company+'var q=networkBulkQuote14(ids,"equipment",{key:"machine",model:"premium"},1,1),before=JSON.stringify(state);');assert(r('!q.safe'));assert.throws(()=>r('applyNetworkBulk14(ids,"equipment",{key:"machine",model:"premium"},1,1,q)'),/limit/);assert(r('JSON.stringify(state)===before'));r('state.cash=400000;var q=networkBulkQuote14(ids,"equipment",{key:"machine",model:"premium"},1000000,8),before=JSON.stringify(state);');assert(r('!q.safe'));assert.throws(()=>r('applyNetworkBulk14(ids,"equipment",{key:"machine",model:"premium"},1000000,8,q)'),/rezerva|hotovost/);assert(r('JSON.stringify(state)===before'));});
test('A later branch exhausting quarterly budget cannot partially buy earlier equipment',r=>{r(company+'var data=planDefaultData6();data.budgets.expansion=170000;setCompanyPlan6(data,planQuote6(data));var before=JSON.stringify(state),q=networkBulkQuote14(ids,"equipment",{key:"machine",model:"premium"},1000000,1);');assert(r('JSON.stringify(state)===before&&!q.safe&&q.warnings.some(x=>x.includes("Čtvrtletní"))'));assert.throws(()=>r('applyNetworkBulk14(ids,"equipment",{key:"machine",model:"premium"},1000000,1,q)'));assert(r('JSON.stringify(state)===before'));});
test('Successful collective purchase books each real charge exactly once in the quarter',r=>{r(company+'var data=planDefaultData6();data.budgets.expansion=1000000;setCompanyPlan6(data,planQuote6(data));var q=networkBulkQuote14(ids,"equipment",{key:"grinder",model:"premium"},1000000,1);applyNetworkBulk14(ids,"equipment",{key:"grinder",model:"premium"},1000000,1,q);');assert(r('Math.abs(state.planning6.current.spent.expansion-q.cost)<.001&&state.planning6.current.events.length===2'));});
test('Stale quote after workforce, stock or selection changes is rejected atomically',r=>{r(company+'var q=networkBulkQuote14(ids,"price",{delta:5},0,1);state.stores[0].crew.employees[0].skills.service++;var before=JSON.stringify(state);');assert.throws(()=>r('applyNetworkBulk14(ids,"price",{delta:5},0,1,q)'),/změnily/);assert(r('JSON.stringify(state)===before'));assert.throws(()=>r('applyNetworkBulk14([ids[0]],"price",{delta:5},0,1,q)'),/změnily/);});
test('Existing full-condition equipment is skipped while real service pays and records expense',r=>{r(company+'state.stores[0].equipment.machine.condition=100;state.stores[1].equipment.machine.condition=40;var pending=state.pendingExpense3||0,q=networkBulkQuote14(ids,"service",{key:"machine"},1000000,1),cash=state.cash;applyNetworkBulk14(ids,"service",{key:"machine"},1000000,1,q);');assert(r('q.rows.filter(x=>x.changed).length===1&&state.cash===cash-q.cost&&state.pendingExpense3===pending+q.cost&&state.stores.every(s=>s.equipment.machine.condition===100)'));});
test('Fran­chise, duplicate targets, impossible prices and missing devices cannot enter collective changes',r=>{r(company+'var before=JSON.stringify(state);');assert.throws(()=>r('networkBulkQuote14([ids[0],ids[0]],"price",{delta:5},0,1)'));assert.throws(()=>r('networkBulkQuote14(ids,"service",{key:"oven"},1000000,1)'));r('state.stores[1].menu.espresso.price=350;var before=JSON.stringify(state);');assert.throws(()=>r('networkBulkQuote14(ids,"price",{delta:5},0,1)'));assert(r('JSON.stringify(state)===before'));r('state.stores[1].menu.espresso.price=90;state.stores[1].franchise=true;');assert.throws(()=>r('networkBulkQuote14(ids,"price",{delta:5},0,1)'));r('state.stores[1].franchise=false;');});
test('Malformed preferences and history fail without mutating live company or import input',r=>{r(company+'var q=networkBulkQuote14(ids,"price",{delta:5},0,1);applyNetworkBulk14(ids,"price",{delta:5},0,1,q);var saved=JSON.parse(JSON.stringify(state)),live=JSON.stringify(state);');for(const mutation of ['v.network14.metrics=["fake"]','v.network14.pins=["fake"]','v.network14.history[0].cost=100','v.network14.history[0].rows[0].actual={week:v.week,profit:0,served:0,wait:0,stockLost:0}','v.network14.history[0].data.delta=500']){r('var v=JSON.parse(JSON.stringify(saved));'+mutation+';var before=JSON.stringify(v);');assert.throws(()=>r('validateSave(v)'));assert(r('JSON.stringify(state)===live&&JSON.stringify(v)===before'));}});
console.log('PASS: '+count+' real network comparison, pins, collective action and migration cases.');
