const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
const c=vm.createContext({Intl,console});for(const f of ['engine','tycoon','empire','operations'])vm.runInContext(fs.readFileSync('dist/'+f+'.js','utf8'),c);
const r=s=>vm.runInContext(s,c),close=(a,b,t=.1)=>assert(Math.abs(a-b)<t,`${a} ≠ ${b}`);let passed=0;
function test(name,fn){r('state=fresh()');fn();r('validateSave(JSON.parse(JSON.stringify(state)))');passed++;console.log('PASS:',name)}
function office(role,pid='candidate-0'){r('state.cash=10000000;buyOffice("studio")');if(role!=='operations')r(`setDepartment("${role}",1)`);else r('openStore("letna");openStore("vinohrady")');r(`hireExecutive5("${role}","${pid}")`)}
function mandate(role,budget=30000){r(`setMandate5("${role}",{...state.organization.policies.${role},enabled:true,budget:${budget}})`)}
test('all four historical saves migrate, including existing weekly reports',()=>{for(let v=1;v<=4;v++){const old=vm.createContext({Intl});vm.runInContext(fs.readFileSync('tests/fixtures/v'+v+'-engine.js','utf8'),old);c.fixture=JSON.parse(JSON.stringify(vm.runInContext(v>=3?'state=fresh();nextWeek();state':'fresh()',old)));const before=r('JSON.stringify(state)');const migrated=r('validateSave(fixture)');assert.equal(migrated.version,5);assert.equal(migrated.stores[0].floor.items.length,12);assert.equal(r('JSON.stringify(state)'),before);}});
test('the default plan is traversable, overlapping stations and blocked entrances reject atomically',()=>{assert(r('floorInfo5(state.stores[0].floor).seats')===24);const before=r('JSON.stringify(state)');assert.throws(()=>r('applyFloor5("karlin",{...state.stores[0].floor,items:state.stores[0].floor.items.map(i=>({...i,x:0,y:5}))})'));assert.equal(r('JSON.stringify(state)'),before);r('const obstructed=JSON.parse(JSON.stringify(state.stores[0].floor));obstructed.items.find(i=>i.id==="counter").x=0;obstructed.items.find(i=>i.id==="counter").y=5');assert.throws(()=>r('applyFloor5("karlin",obstructed)'));});
test('longer station paths change throughput; renovation charges once and preserves the previous report',()=>{const h=r('nextWeek()'),oldReport=r('JSON.stringify(state.stores[0].daily.last.floorSnapshot)'),flow=r('floorInfo5(state.stores[0].floor).flow'),cash=r('state.cash');r('const distant=JSON.parse(JSON.stringify(state.stores[0].floor));distant.items.find(i=>i.id==="espresso").x=0;applyFloor5("karlin",distant)');close(r('state.cash'),cash-25000);assert(r('floorInfo5(state.stores[0].floor).flow')<flow);assert.equal(r('JSON.stringify(state.stores[0].daily.last.floorSnapshot)'),oldReport);r('applyFloor5("karlin",distant)');close(r('state.cash'),cash-25000);});
test('daily arrivals, service and each reason for departure conserve all guests and revenues',()=>{r('nextWeek()');const report=r('state.stores[0].daily.last'),last=r('state.stores[0].last');assert.equal(report.days.length,6);assert.equal(report.served,last.served);for(const d of report.days){assert.equal(d.timeline.length,72);assert.equal(d.arrivals,d.served+d.lostQueue+d.lostSeats+d.lostClosing+d.lostStock);assert(d.timeline.every(p=>p.occupied<=report.floor.seats));}assert.equal(report.demand,report.days.reduce((a,d)=>a+d.arrivals,0));close(report.days.reduce((a,d)=>a+d.revenue,0),last.retailSales,1);assert.equal(last.lost,report.lostQueue+report.lostSeats+report.lostClosing+report.lostStock);});
test('equal wage budgets produce different queue losses when people move into the morning peak',()=>{const base=r('nextWeek().cups'),loss=r('state.stores[0].daily.last.lostQueue');r('state=fresh();setShifts5("karlin",[4,3,2])');assert.equal(r('shiftWages5(state.stores[0])'),19500);const optimized=r('nextWeek().cups');assert(optimized>base);assert(r('state.stores[0].daily.last.lostQueue')<loss);assert.equal(r('state.stores[0].last.detail.wages'),19500);});
test('extra shifts have actual wage expenses and closed shifts receive no free service',()=>{r('setShifts5("karlin",[5,4,3]);nextWeek()');assert.equal(r('state.stores[0].last.detail.wages'),26000);r('state=fresh();setShifts5("karlin",[0,0,0])');assert.equal(r('nextWeek().cups'),0);assert.equal(r('state.stores[0].last.detail.wages'),0);assert(r('state.stores[0].daily.last.days.every(d=>d.served===0)'));});
test('missing seating loses visitors who want a table and keeps takeaway sales',()=>{r('const noSeats=JSON.parse(JSON.stringify(state.stores[0].floor));noSeats.items=noSeats.items.filter(i=>i.kind!=="table");applyFloor5("karlin",noSeats);nextWeek()');assert(r('state.stores[0].daily.last.lostSeats')>0);assert(r('state.stores[0].daily.last.served')>0);assert.equal(r('state.stores[0].daily.last.floor.seats'),0);});
test('coffee inventory shortage reduces the actual daily timeline without duplicate consumption',()=>{r('state.batches[0].kg=2;state.roasters[0].auto=false;nextWeek()');assert(r('state.stores[0].daily.last.lostStock')>0);assert(r('state.stores[0].last.served')<=Math.floor(2/r('menuSummary(state.stores[0]).dose')));const rep=r('state.stores[0].daily.last');assert.equal(rep.lostStock,rep.days.reduce((a,d)=>a+d.lostStock,0));assert.equal(rep.served,rep.days.reduce((a,d)=>a+d.served,0));});
test('worn machines cause recorded rush-hour faults and lower service',()=>{r('buyEquipment("karlin","machine");state.stores[0].equipment.machine.condition=50;nextWeek()');assert(r('state.stores[0].daily.last.days.flatMap(d=>d.timeline).some(p=>p.fault)'));assert(r('state.stores[0].daily.last.days.flatMap(d=>d.timeline).filter(p=>p.fault).every(p=>p.slot>=10&&p.slot<16)'));});
test('a window requires installed equipment and only contributes after being placed',()=>{r('const withWindow=JSON.parse(JSON.stringify(state.stores[0].floor));withWindow.items.push({id:"window",kind:"window",x:7,y:1})');assert.throws(()=>r('applyFloor5("karlin",withWindow)'));r('buyEquipment("karlin","window");nextWeek()');const without=r('state.stores[0].daily.last.served');r('state=fresh();buyEquipment("karlin","window");applyFloor5("karlin",withWindow);nextWeek()');assert(r('state.stores[0].daily.last.served')>=without);});
test('manual shifts remain protected while manager automation redistributes an authorized roster',()=>{r('hireCandidate("karlin","candidate-0");setShifts5("karlin",[2,1,1]);nextWeek()');assert.equal(r('state.stores[0].daily.shifts.join(",")'),'2,1,1');assert.equal(r('state.stores[0].auto.staff'),false);r('state.stores[0].daily.auto=true;state.stores[0].auto.staff=true;nextWeek()');assert(r('state.stores[0].daily.shifts[0]')>r('state.stores[0].daily.shifts[2]'));});
test('staffing plans change real shifts for their four-week review period',()=>{r('hireCandidate("karlin","candidate-0");buyEquipment("karlin","bar");state.stores[0].staff=1;state.stores[0].daily.shifts=[1,1,1];nextWeek();state.stores[0].staff=1;state.stores[0].daily.shifts=[1,1,1];state.stores[0].last.lost=900;state.stores[0].last.reason="Tým";generatePlans4();decidePlan4(state.empire.plans[0].id,true)');assert.equal(r('state.stores[0].daily.shifts.join(",")'),'2,2,2');r('nextWeek()');assert.equal(r('state.stores[0].last.detail.wages'),13000);});
test('directors need office capacity, departmental staff and unique identities',()=>{const before=r('JSON.stringify(state)');assert.throws(()=>r('hireExecutive5("hr","candidate-0")'));assert.equal(r('JSON.stringify(state)'),before);r('buyOffice("studio")');assert.throws(()=>r('hireExecutive5("hr","candidate-0")'));r('setDepartment("hr",1);hireExecutive5("hr","candidate-0")');assert.equal(r('usedSeats()'),3);assert.equal(r('state.organization.executives.hr.manager.pid'),'candidate-0');assert(!r('state.talents.some(p=>p.pid==="candidate-0")'));assert.throws(()=>r('hireCandidate("karlin","candidate-0")'));});
test('executive wages are charged once, alongside department employees, and reconcile the books',()=>{office('hr');const expected=r('executiveCost5()'),cash=r('state.cash'),h=r('nextWeek()');assert.equal(h.detail.directors,Math.round(expected));close(h.revenue-h.expenses-h.cogs-h.interest-h.spoil,h.profit,2);close(cash+h.cashChange,h.cash,1);assert.equal(r('state.organization.reports[0].status'),'held');});
test('HR mandate respects reserve and budget and trains the actual weakest manager',()=>{office('hr');r('hireCandidate("karlin","candidate-1")');mandate('hr',11000);const skill=r('state.stores[0].manager.strength.people');r('nextWeek()');assert.equal(r('state.organization.reports[0].status'),'held');assert.equal(r('state.stores[0].manager.strength.people'),skill);mandate('hr',12000);r('nextWeek()');assert.equal(r('state.organization.reports[0].status'),'done');assert.equal(r('state.stores[0].manager.strength.people'),skill+4);assert.equal(r('state.history.at(-1).detail.development'),12000);});
test('finance director repays actual principal within a weekly limit and retains cash reserve',()=>{office('finance');mandate('finance',25000);r('state.debt=100000;runOrganization5()');assert.equal(r('state.debt'),75000);assert.equal(r('state.organization.reports[0].cost'),25000);r('state.cash=weeklyFixed()*2;runOrganization5()');assert.equal(r('state.debt'),75000);assert.equal(r('state.organization.reports[0].status'),'held');});
test('product and IT directors fund existing game systems instead of cosmetic reports',()=>{office('product');mandate('product',20000);r('nextWeek()');assert.equal(r('state.blends[0].research'),2);assert.equal(r('state.history.at(-1).detail.development'),20000);r('setDepartment("it",1);hireExecutive5("it","candidate-1")');mandate('it',8000);r('nextWeek()');assert(r('state.projects.loyalty.progress')>0);assert.equal(r('state.projects.loyalty.budget'),8000);assert.equal(r('state.history.at(-1).detail.projects'),8000);});
test('COO repairs only assigned stores, under budget and with explicit maintenance authority',()=>{office('operations');r('setOwner5("karlin","operations");buyEquipment("karlin","machine");state.stores[0].equipment.machine.condition=50');mandate('operations',7100);r('runOrganization5()');assert.equal(r('state.stores[0].equipment.machine.condition'),50);mandate('operations',7200);r('runOrganization5()');assert.equal(r('state.stores[0].equipment.machine.condition'),100);assert.equal(r('state.organization.reports[0].cost'),7200);r('state.stores[0].equipment.machine.condition=50;state.organization.policies.operations.maintenance=false;runOrganization5()');assert.equal(r('state.stores[0].equipment.machine.condition'),50);});
test('region and COO responsibility are explicit, and missing owners cannot silently automate',()=>{r('hireCandidate("karlin","candidate-0");buyOffice("studio");promotePerson(state.stores[0].manager.pid,"Praha");setOwner5("karlin","region");nextWeek()');assert(r('state.stores[0].daily.last.owner.includes("Anna")'));assert.throws(()=>r('setOwner5("karlin","operations")'));r('state.regions=[];setShifts5("karlin",[2,2,2]);state.stores[0].daily.auto=true;state.stores[0].auto.staff=true;nextWeek()');assert.equal(r('state.stores[0].daily.last.owner'),'Zakladatel');assert.equal(r('state.stores[0].daily.shifts.join(",")'),'2,2,2');});
test('sales director accepts a real partnership with a staffed sales slot',()=>{office('sales');mandate('sales');r('state.empire.partnership={id:"org-partner",rival:"north",kg:10,price:620,blend:"blend-1",due:state.week+3};nextWeek()');assert.equal(r('state.contracts.length'),1);assert(r('state.history.at(-1).wholesale')>0);assert.equal(r('state.organization.reports[0].status'),'done');});
test('firing or promoting a director releases the office seat and retains their career',()=>{office('hr');r('fireExecutive5("hr")');assert.equal(r('usedSeats()'),2);assert(r('state.talents.some(p=>p.pid==="candidate-0")'));r('hireExecutive5("hr","candidate-0");promotePerson("candidate-0","Praha")');assert.equal(r('state.organization.executives.hr.manager'),null);assert.equal(r('state.regions[0].manager.pid'),'candidate-0');});
test('daily playback is read-only, retains historical layout and validates all slots',()=>{r('nextWeek()');const before=r('JSON.stringify(state)');for(let day=0;day<6;day++)for(let slot=0;slot<72;slot++)assert.equal(r(`replayDay5("karlin",${day},${slot}).slot`),slot);assert.equal(r('JSON.stringify(state)'),before);assert.throws(()=>r('replayDay5("karlin",6,0)'));assert.throws(()=>r('replayDay5("karlin",0,72)'));});
test('forecasts include executive actions and daily queues, remain pure and match actual baseline',()=>{office('hr');r('hireCandidate("karlin","candidate-1")');mandate('hr',12000);const before=r('JSON.stringify(state)'),f=r('simulatePlan({kind:"store",target:"letna"},4)');assert.equal(r('JSON.stringify(state)'),before);r('applyPlan({kind:"store",target:"letna"});for(let i=0;i<4;i++)nextWeek()');assert.equal(r('Math.round(state.cash)'),f.results[1].cash);});
test('tampered layouts, shift schedules, duplicates and nonconserving daily reports reject without state changes',()=>{r('nextWeek()');const before=r('JSON.stringify(state)');for(const edit of ['bad.stores[0].floor.items[0].x=20','bad.stores[0].daily.shifts=[1,2,9]','delete bad.stores[0].daily.last.floor','bad.stores[0].daily.last.days[0].day=2','bad.stores[0].daily.last.shifts=[]','bad.stores[0].daily.last.lostStock+=1','bad.organization.policies.hr.budget=-1','bad.stores[0].daily.last.days[0].timeline[0].served+=1','bad.organization.executives.hr.manager=bad.talents[0]','bad.stores[0].floor.items.push({id:"evil",kind:"constructor",x:0,y:0})']){r('var bad=JSON.parse(JSON.stringify(state));'+edit);assert.throws(()=>r('validateSave(bad)'));assert.equal(r('JSON.stringify(state)'),before);}});
test('an inactive COO mandate cannot be bypassed by a local manager staffing decision',()=>{office('operations');r('hireCandidate("karlin","candidate-1");setOwner5("karlin","operations");state.stores[0].staff=1;state.stores[0].daily.shifts=[1,1,1];nextWeek()');assert.equal(r('state.stores[0].staff'),1);assert.equal(r('state.stores[0].daily.shifts.join(",")'),'1,1,1');assert.equal(r('state.stores[0].auto.staff'),true);});
console.log(`All ${passed} edice 05 simulation scenarios passed.`);
