const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
const files=[...fs.readFileSync('dist/index.html','utf8').matchAll(/<script src="([^"]+)"/g)].map(m=>m[1]).filter(f=>f!=='app.js'&&!f.endsWith('-ui.js')&&f!=='game-renderer.js');
function game(){const c=vm.createContext({console,Intl});for(const f of files)vm.runInContext(fs.readFileSync('dist/'+f,'utf8'),c,{filename:f});return s=>vm.runInContext(s,c);}
let passed=0;function test(name,fn){const r=game();fn(r);r('validateSave(JSON.parse(JSON.stringify(state)))');console.log('PASS: '+name);passed++;}
// Prefunded regression fixture. All cafes, coffee, production, auctions and entries use paid actions.
const company='state=fresh();state.cash=20000000;startOpening6("cafe",{location:"letna",design:"starter",options:{kind:"legacy",space:"starter"}});signCoffeeAgreement6("local","letna","blend-1",{enabled:true,target:25,budget:20000,reserve:1});';
const win='var o=microOffers11()[0],amount=o.minimum+30000,q=microBidQuote11(o.id,amount,1),a=bidMicro11(o.id,amount,1,q);for(let i=0;i<7;i++)nextWeek();';
const edition='var data={name:"Bensa 01",roast:1,packaging:"premium",price:1000},q=microEditionQuote11(a.id,data,1),ed=createMicroEdition11(a.id,data,1,q);';
const roaster='startOpening6("roaster",{type:"artisan",name:"Mala",city:"Praha"});for(let i=0;i<5;i++)nextWeek();var rr=state.roasters[0];rr.auto=false;';
const sample='manualRoast(rr.id,ed.blend,10);var lot=prestigeLots11(ed.blend)[0];';
const enter='var q=contestQuote11(lot.id,"filter",1),entry=enterContest11(lot.id,"filter",1,q);';
test('Neutral migration and read-only offers preserve cash, stock, IDs and existing history',r=>{r('var old=JSON.parse(JSON.stringify(state));delete old.prestige11;var before=JSON.stringify(old),v=validateSave(old);delete v.prestige11;');assert(r('JSON.stringify(v)===before&&JSON.stringify(old)===before'));r(company+'var before=JSON.stringify(state),offers=microOffers11(),q=microBidQuote11(offers[0].id,offers[0].minimum,1);');assert(r('JSON.stringify(state)===before&&offers.length===3'));assert.throws(()=>r('microBidQuote11("micro-00-0",offers[0].minimum,1)'));});
test('Escrow is a paid asset; increasing the leading bid pays only its difference',r=>{r(company+'var o=microOffers11()[0],cash=state.cash,value=companyValue(),q=microBidQuote11(o.id,o.minimum,1),a=bidMicro11(o.id,o.minimum,1,q);');assert(r('cash-state.cash===o.minimum+o.shipping&&companyValue()===value'));r('var cash=state.cash,q=microBidQuote11(o.id,o.minimum+1000,1);bidMicro11(o.id,o.minimum+1000,1,q);');assert(r('cash-state.cash===1000&&a.bids.length===2&&a.refunds.length===0'));});
test('Stale bids, insufficient reserve and quarterly limits cannot make partial payments',r=>{r(company+'var o=microOffers11()[0],q=microBidQuote11(o.id,o.minimum,1);state.cash--;var before=JSON.stringify(state);');assert.throws(()=>r('bidMicro11(o.id,o.minimum,1,q)'),/změnily/);assert(r('JSON.stringify(state)===before'));r('var q=microBidQuote11(o.id,o.minimum,8);state.cash=q.cost+q.protectedCash-1;q=microBidQuote11(o.id,o.minimum,8);var before=JSON.stringify(state);');assert(r('!q.safe'));assert.throws(()=>r('bidMicro11(o.id,o.minimum,8,q)'));assert(r('JSON.stringify(state)===before'));r(company+'var plan=planDefaultData6();plan.budgets.production=0;setCompanyPlan6(plan);var before=JSON.stringify(state);');assert.throws(()=>r('microBidQuote11(o.id,o.minimum,1)'),/rozpočet/);assert(r('JSON.stringify(state)===before'));});
test('A real rival pays escrow and returns the player deposit exactly once',r=>{r(company+'var o=microOffers11()[0],q=microBidQuote11(o.id,o.minimum,1),a=bidMicro11(o.id,o.minimum,1,q),cash=state.cash,rivalCash=Object.fromEntries(state.rivals.map(r=>[r.id,r.cash]));processMicroAuctions11();');assert(r('a.leader!=="player"&&state.cash-cash===o.minimum+o.shipping&&a.refunds.length===1&&state.rivals.find(r=>r.id===a.leader).cash===rivalCash[a.leader]-a.escrow'));r('var before=JSON.stringify(state);processMicroAuctions11();');assert(r('JSON.stringify(state)===before'));});
test('A lost finite auction cannot be bought again or create a free shipment',r=>{r(company+'var o=microOffers11()[0],q=microBidQuote11(o.id,o.minimum,1),a=bidMicro11(o.id,o.minimum,1,q);for(let i=0;i<5;i++)nextWeek();');assert(r('a.status==="lost"&&a.escrow===0&&!state.shipments.some(s=>s.id===a.id)&&microAmount11(a.id)===0'));assert.throws(()=>r('microBidQuote11(a.id,a.price+1000,1)'));});
test('Winning pays a single physical shipment; delivery conserves source and landed value',r=>{r(company+win);assert(r('a.status==="received"&&a.used===0&&microAmount11(a.id)===o.kg'));assert(r('state.green.filter(g=>g.source5?.microlot===a.id).length===1&&state.green.find(g=>g.source5?.microlot===a.id).cost===(a.price+o.shipping)/o.kg'));r('var before=JSON.stringify(state.prestige11);nextWeek();');assert(r('JSON.stringify(state.prestige11)===before&&microAmount11(a.id)===o.kg'));});
test('A full real green warehouse postpones the whole microlot until paid storage expansion',r=>{r(company+'orderBeans("brazil",200);'+win);assert(r('a.status==="transit"&&microAmount11(a.id)===0&&state.shipments.some(s=>s.id===a.id&&s.due===state.week)'));r('buyWarehouse("Praha","Zeleny sklad",1000);nextWeek();');assert(r('a.status==="received"&&microAmount11(a.id)===60'));});
test('A paid limited recipe creates no coffee and cannot change origin or admit fallback',r=>{r(company+win+'var stockBefore=JSON.stringify(state.green),cash=state.cash,pending=state.empire.pendingExpense;'+edition);assert(r('cash-state.cash===15000&&state.empire.pendingExpense-pending===15000&&JSON.stringify(state.green)===stockBefore&&!state.batches.some(l=>l.blend===ed.blend)'));assert.throws(()=>r('setCoffeeSources5(ed.blend,{primarySource:"any",secondarySource:"any",fallback:true})'));assert.throws(()=>r('updateBlend(ed.blend,{...blend(ed.blend),primary:"brazil"})'));assert.throws(()=>r('microEditionQuote11(a.id,data,1)'));});
test('Ordinary automatic coffee never steals reserved microlots, even of the same origin',r=>{r(company+win+edition+roaster+'var b=blend("blend-1");updateBlend(b.id,{...b,name:"Obycejna",primary:"ethiopia",secondary:"ethiopia",share:100,roast:1});state.stores[0].blend=b.id;rr.auto=true;var kg=microAmount11(a.id);nextWeek();');assert(r('microAmount11(a.id)===kg&&state.craft5.ledger.filter(x=>x.blend===b.id).every(x=>x.sources.every(s=>!s.source.microlot))'));});
test('Actual roasting conserves landed green cost, profile yield and immutable farm trace',r=>{r(company+win+edition+roaster+sample);assert(r('a.used===10&&microAmount11(a.id)===50&&lot.kg===8.4&&lot.craft5.authentic&&lot.craft5.sources[0].source.microlot===a.id'));assert(r('Math.abs(lot.cost*8.4-(a.price+o.shipping)/60*10-550)<.001'));r('var before=JSON.stringify(state),q=craftPreview5(rr.id,ed.blend,2,null);');assert(r('JSON.stringify(state)===before&&q.sources[0].source.id===a.id'));});
test('Finite depletion blocks replacement and keeps paid automatic production bounded',r=>{r(company+win+edition+roaster+'state.stores[0].blend=ed.blend;rr.auto=true;for(let i=0;i<12;i++)nextWeek();');assert(r('microAmount11(a.id)===0&&Math.abs(a.used-60)<.001&&state.craft5.ledger.filter(x=>x.blend===ed.blend).reduce((n,x)=>n+x.input,0)<=60.001'));const before=r('JSON.stringify(state)');assert.throws(()=>r('manualRoast(rr.id,ed.blend,1)'));assert.equal(r('JSON.stringify(state)'),before);});
test('Soutěž requires a fresh authentic commercial sample from real own production',r=>{r(company+win+edition+roaster);assert(r('prestigeLots11().length===0'));assert.throws(()=>r('contestQuote11("missing","filter",1)'));r(sample+'var before=JSON.stringify(state),q=contestQuote11(lot.id,"filter",1);');assert(r('JSON.stringify(state)===before&&q.sample.kg===.5'));r('for(let i=0;i<5;i++)nextWeek();');assert.throws(()=>r('contestQuote11(lot.id,"filter",1)'));});
test('Entry pays once, consumes precisely 500 g and books no double coffee expense',r=>{r(company+win+edition+roaster+sample+'var cash=state.cash,kg=lot.kg,pending=state.empire.pendingExpense;'+enter);assert(r('cash-state.cash===18000&&kg-lot.kg===.5&&Math.abs(state.empire.pendingExpense-pending-18000-entry.cost)<.001'));assert(r('state.craft5.ledger.find(r=>r.id===lot.id).deliveries.some(d=>d.kg===.5&&d.label.includes("Vzorek"))'));const before=r('JSON.stringify(state)');assert.throws(()=>r('enterContest11(lot.id,"filter",1,q)'));assert.equal(r('JSON.stringify(state)'),before);});
test('Frozen judging compares quality, flavor and actual sample freshness in the selected category',r=>{r(company+win+edition+roaster+sample+enter+'var frozen=JSON.stringify(entry.sample),field=JSON.stringify(entry.field);state.rivals[0].business.quality=99;for(let i=0;i<3;i++)nextWeek();');assert(r('entry.status==="completed"&&entry.judges.score===93.55&&entry.award==="silver"&&entry.rank===1&&JSON.stringify(entry.sample)===frozen&&JSON.stringify(entry.field)===field'));assert(r('contestScore11(entry.sample,"filter").taste>contestScore11(entry.sample,"espresso").taste'));r('var older={...entry.sample,age:4};');assert(r('contestScore11(older,"filter").score<entry.judges.score'));});
test('Awards affect only available authentic coffee; changes, stockout and expiry remove the bounded effect',r=>{r(company+win+edition+roaster+sample+enter+'for(let i=0;i<3;i++)nextWeek();var effect=prestigeEffect11(ed.blend,"Praha"),trust=state.trust;');assert(r('effect.demand>1&&effect.demand<=1.08&&effect.trust<=4&&prestigeEffect11(ed.blend,"Brno").demand===1'));r('var saved=JSON.parse(JSON.stringify(state.batches));state.batches=state.batches.filter(l=>l.blend!==ed.blend);');assert(r('prestigeEffect11(ed.blend,"Praha").demand===1'));r('state.batches=saved;for(const l of state.batches.filter(l=>l.blend===ed.blend))l.craft5.profile={drop:201,minutes:12,development:20};');assert(r('prestigeEffect11(ed.blend,"Praha").demand===1'));r('state.batches=saved.map(l=>JSON.parse(JSON.stringify(l)));for(const l of state.batches.filter(l=>l.blend===ed.blend))l.craft5.profile=null;');r('for(let i=0;i<30;i++)nextWeek();');assert(r('prestigeEffect11(ed.blend,"Praha").demand===1'));});
test('Weekly reports have direct auction and frozen competition result destinations',r=>{r(company+win+edition+roaster+sample+enter+'for(let i=0;i<3;i++)nextWeek();var h=weeklyDigest6(entry.finished);');assert(r('h.items.some(i=>i.key.startsWith("prestige-contest-")&&i.target===entry.id)'));});
test('Archive stays unchanged after real weeks and rejects counterfeit quantities, source, fees or medals',r=>{r(company+win+edition+roaster+sample+enter+'for(let i=0;i<3;i++)nextWeek();var frozen=JSON.stringify(entry),valid=JSON.parse(JSON.stringify(state)),live=JSON.stringify(state);');for(const mutation of ['v.prestige11.auctions[0].used++','v.green.find(g=>g.source5?.microlot).source5.name="Fake"','v.prestige11.auctions[0].price++','v.prestige11.entries[0].fee--','v.prestige11.entries[0].sample.age++','v.prestige11.entries[0].sample.craft.flavor.fruit--','v.prestige11.entries[0].award="gold"','v.prestige11.entries[0].judges.score++']){r('var v=JSON.parse(JSON.stringify(valid));'+mutation+';var before=JSON.stringify(v);');assert.throws(()=>r('validateSave(v)'));assert(r('JSON.stringify(state)===live&&JSON.stringify(v)===before'));}r('for(let i=0;i<30;i++){nextWeek();validateSave(JSON.parse(JSON.stringify(state)));}');assert(r('JSON.stringify(entry)===frozen'));});
test('Contest stale confirmation and quarterly limits preserve the sample and cash atomically',r=>{r(company+win+edition+roaster+sample+'var q=contestQuote11(lot.id,"filter",1);state.cash--;var before=JSON.stringify(state);');assert.throws(()=>r('enterContest11(lot.id,"filter",1,q)'),/změnily/);assert(r('JSON.stringify(state)===before'));r('var plan=planDefaultData6();plan.budgets.marketing=0;setCompanyPlan6(plan);var before=JSON.stringify(state);');assert.throws(()=>r('contestQuote11(lot.id,"filter",1)'),/rozpočet/);assert(r('JSON.stringify(state)===before'));});
test('Archived samples remain verifiable after the rolling production ledger expires',r=>{r(company+win+edition+roaster+sample+enter+'for(let i=0;i<3;i++)nextWeek();var frozen=JSON.stringify(entry),batch=entry.sample.batch;buyWarehouse("Praha","Archivni sklad",1000);orderBeans("brazil",500);orderBeans("colombia",250);for(let i=0;i<2;i++)nextWeek();for(let i=0;i<105;i++){manualRoast(rr.id,"blend-1",1);manualRoast(rr.id,"blend-1",1);nextWeek();validateSave(JSON.parse(JSON.stringify(state)));}');assert(r('state.craft5.ledger.length===200&&!state.craft5.ledger.some(r=>r.id===batch)&&JSON.stringify(entry)===frozen'));r('var v=JSON.parse(JSON.stringify(state));v.prestige11.entries[0].sample.craft.sources[0].source.variety="standard";');assert.throws(()=>r('validateSave(v)'));});
console.log('PASS: '+passed+' paid finite coffee auction, authentic production, physical samples, bounded prestige and archive cases.');
