const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
const c=vm.createContext({Intl,console});for(const f of ['engine','tycoon','empire','operations','reports','supply','crew','craft','studio','business','guests','branding','property','rivals','seasons','procurement'])vm.runInContext(fs.readFileSync('dist/'+f+'.js','utf8'),c);const r=s=>vm.runInContext(s,c),snap=()=>r('JSON.stringify(state)'),near=(a,b)=>assert(Math.abs(a-b)<.02,`${a} != ${b}`);let passed=0;
function test(name,fn){r('state=fresh()');fn();r('validateSave(JSON.parse(JSON.stringify(state)))');passed++;console.log('PASS:',name)}
function own(){r('openStore("letna");hireCandidate("letna","candidate-0")')}
function funded(){own();r('state.cash=6000000;buyOffice("studio");setDepartment("finance",1);state.roasters[0].auto=false')}
const order=(supplier='harbor',terms=0,kg=20)=>`{supplier:"${supplier}",origin:"brazil",kg:${kg},terms:${terms},reserve:1}`;
test('founder keeps original cash and no invented suppliers, debt or transaction history',()=>{assert.equal(r('state.cash'),650000);assert.equal(r('state.procurement5.orders.length'),0);const s=snap();assert.throws(()=>r('nextWeek()'));assert.equal(snap(),s);});
test('supplier quotes are pure and distinguish price, quality, lead time and capacity',()=>{own();const s=snap();r(`var a=procurementQuote5(${order('harbor')}),b=procurementQuote5(${order('cargo',0,40)}),z=procurementQuote5(${order('altitude')})`);assert(r('b.unit<a.unit&&z.qualityLow>a.qualityLow&&b.due>a.due'));assert.equal(snap(),s);});
test('prepaid order pays exact full landed cost once and remains outside physical stock',()=>{funded();r(`var q=procurementQuote5(${order()}),cash=state.cash,stockBefore=greenAmount("brazil");buyProcurement5(${order()},q)`);near(r('state.cash'),r('cash-q.cost'));near(r('greenAmount("brazil")'),r('stockBefore'));assert.equal(r('state.shipments.at(-1).supplierOrder5'),r('state.procurement5.orders[0].id'));});
test('prepaid cargo remains an asset in company valuation while it is on the way',()=>{funded();r(`buyProcurement5(${order()});var base=PROCUREMENT_BASE5.companyValue()`);near(r('companyValue()-base'),r('state.procurement5.orders[0].cost'));});
test('actual supplier lot arrives once with quoted landed cost and source identity',()=>{funded();r(`var o=buyProcurement5(${order()}),before=greenAmount("brazil");for(let i=0;i<5;i++)nextWeek()`);near(r('greenAmount("brazil")-before'),20);assert.equal(r('state.procurement5.events.filter(e=>e.kind==="arrival").length'),1);assert.equal(r('state.green.at(-1).cost'),r('o.unit'));assert.equal(r('state.green.at(-1).source5.name'),'Harbor Coffee Import');assert(r('state.green.at(-1).quality>=o.qualityLow&&state.green.at(-1).quality<=o.qualityHigh'));});
test('a delayed shipment moves its due date and does not enter stock early',()=>{funded();r(`var o;for(let i=0;i<8;i++)buyProcurement5(${order('cargo',0,40)});var before=greenAmount("brazil");for(let i=0;i<5;i++)nextWeek();var delayed=state.procurement5.orders.filter(o=>o.status==="delayed")`);assert(r('state.procurement5.events.some(e=>e.kind==="delay")'));assert(r('state.procurement5.orders.some(o=>o.due>o.expected)'));r('for(let i=0;i<3;i++)nextWeek()');near(r('greenAmount("brazil")-before'),320);assert.equal(r('state.procurement5.events.filter(e=>e.kind==="arrival").length'),8);});
test('weekly supplier capacity rejects oversubscription atomically',()=>{funded();r(`for(let i=0;i<3;i++)buyProcurement5(${order('harbor',0,500)})`);const s=snap();assert.throws(()=>r(`buyProcurement5(${order()})`));assert.equal(snap(),s);});
test('minimum size, nonexistent supplier, credit eligibility and insufficient reserve reject atomically',()=>{own();for(const query of [`buyProcurement5(${order('cargo',0,20)})`,`buyProcurement5(${order('missing')})`,`buyProcurement5(${order('harbor',2)})`]){const s=snap();assert.throws(()=>r(query));assert.equal(snap(),s);}r('state.cash=1');const s=snap();assert.throws(()=>r(`buyProcurement5(${order()})`));assert.equal(snap(),s);});
test('stale quotes reject after cash or marketplace changes without a partial purchase',()=>{funded();r(`var q=procurementQuote5(${order()});state.cash-=1`);const s=snap();assert.throws(()=>r(`buyProcurement5(${order()},q)`));assert.equal(snap(),s);});
test('credit creates no payment before delivery and invoice maturity is relative to receipt',()=>{funded();r(`var cash=state.cash,o=buyProcurement5(${order('harbor',2)})`);near(r('state.cash'),r('cash'));assert.equal(r('procurementPayable5()'),0);r('for(let i=0;i<4&&!state.procurement5.payables.length;i++)nextWeek();var bill=state.procurement5.payables[0]');assert.equal(r('bill.due'),r('o.received+2'));near(r('bill.amount'),r('o.cost'));assert.equal(r('bill.paid'),null);});
test('credit invoice pays once, leaves no liability and makes no second operating expense',()=>{funded();r(`var o=buyProcurement5(${order('harbor',2)});for(let i=0;i<6;i++)nextWeek();var bill=state.procurement5.payables[0]`);near(r('procurementPayable5()'),0);assert.equal(r('bill.paid'),r('bill.due'));assert.equal(r('state.procurement5.events.filter(e=>e.kind==="payment").length'),1);near(r('state.procurement5.events.find(e=>e.kind==="payment").amount'),r('o.cost'));assert(r('state.history.every(h=>h.detail.procurementFees===0)'));});
test('supplier credit limit includes commitments that have not arrived yet',()=>{funded();r(`buyProcurement5(${order('altitude',2,200)});buyProcurement5(${order('altitude',2,200)});buyProcurement5(${order('altitude',2,200)});buyProcurement5(${order('cooperative',2,500)})`);const s=snap();assert.throws(()=>r(`buyProcurement5(${order('cargo',2,1000)})`));assert.equal(snap(),s);assert(r('procurementCredit5()<=300000'));});
test('actual received credit is deducted once from firm value',()=>{funded();r(`buyProcurement5(${order('harbor',2)});for(let i=0;i<4&&!state.procurement5.payables.length;i++)nextWeek();var base=PROCUREMENT_BASE5.companyValue()`);near(r('companyValue()-base'),-r('procurementPayable5()'));});
test('overdue invoice blocks fresh credit for that supplier and survives insufficient cash',()=>{funded();r(`buyProcurement5(${order('harbor',2)});for(let i=0;i<4&&!state.procurement5.payables.length;i++)nextWeek();var bill=state.procurement5.payables[0];state.week=bill.due;state.cash=0;settleProcurement5()`);assert.equal(r('bill.paid'),null);r('state.cash=6000000');const s=snap();assert.throws(()=>r(`buyProcurement5(${order('harbor',2)})`));assert.equal(snap(),s);});
test('contract charges only its fee initially and fixes the landed unit price',()=>{funded();r(`var data={...${order('cooperative')},weeks:12},q=procurementQuote5(data,true),cash=state.cash,c=signProcurement5(data,q)`);near(r('state.cash'),r('cash-2500'));assert.equal(r('state.procurement5.orders.length'),0);near(r('c.unit'),r('q.unit'));r('nextWeek()');assert.equal(r('state.history.at(-1).detail.procurementFees'),2500);assert.equal(r('state.procurement5.orders[0].unit'),r('c.unit'));});
test('fixed contract protects purchases from later macro input inflation',()=>{funded();r(`var c=signProcurement5({...${order()},weeks:12});nextWeek();state.empire.cycle="inflation";nextWeek()`);assert(r('state.procurement5.orders.every(o=>o.unit===c.unit)'));});
test('paused contract spends nothing and does not extend its calendar duration',()=>{funded();r(`var c=signProcurement5({...${order()},weeks:12});setProcurementStatus5(c.id,"paused");for(let i=0;i<13;i++)nextWeek()`);assert.equal(r('state.procurement5.orders.length'),0);assert.equal(r('c.status'),'expired');assert.equal(r('c.end'),13);});
test('cancelled contract retains an ordered shipment and its later credit payment',()=>{funded();r(`var c=signProcurement5({...${order('harbor',2)},weeks:12});nextWeek();setProcurementStatus5(c.id,"cancelled");for(let i=0;i<6;i++)nextWeek()`);assert.equal(r('state.procurement5.orders.length'),1);assert.equal(r('state.procurement5.orders[0].status'),'received');assert(r('state.procurement5.orders[0].paid===state.procurement5.orders[0].cost'));});
test('insufficient contract reserve holds ordering without charging a fictional shipment',()=>{funded();r(`var c=signProcurement5({...${order()},weeks:12});state.cash=0;processSupply()`);assert.equal(r('state.procurement5.orders.length'),0);assert.equal(r('c.last.status'),'held');});
test('same supplier and origin cannot have duplicate active contracts',()=>{funded();r(`signProcurement5({...${order()},weeks:12})`);const s=snap();assert.throws(()=>r(`signProcurement5({...${order()},weeks:12})`));assert.equal(snap(),s);});
test('supply trace reports actual delayed arrivals only in their real receipt weeks',()=>{funded();r(`buyProcurement5(${order('cooperative')});for(let i=0;i<6;i++)nextWeek()`);assert.equal(r('state.procurement5.history.reduce((n,h)=>n+h.rows.reduce((z,row)=>z+row.received,0),0)'),20);assert.equal(r('state.procurement5.orders[0].received'),r('state.procurement5.history.find(h=>h.rows.some(row=>row.received)).week'));});
test('purchase forecast is pure and equals actual placement and four weekly turns',()=>{funded();const s=snap(),f=r(`previewProcurement5({kind:"order",data:${order('harbor',2)}},4)`);assert.equal(snap(),s);r(`buyProcurement5(${order('harbor',2)});for(let i=0;i<4;i++)nextWeek()`);near(r('state.cash'),f.changed.series.at(-1).cash);near(r('procurementPayable5()'),f.changed.series.at(-1).payables);});
test('contract forecast includes fees, real repeated orders and payments without mutation',()=>{funded();const s=snap(),f=r(`previewProcurement5({kind:"contract",data:{...${order()},weeks:12}},8)`);assert.equal(snap(),s);r(`signProcurement5({...${order()},weeks:12});for(let i=0;i<8;i++)nextWeek()`);near(r('state.cash'),f.changed.series.at(-1).cash);assert(r('state.procurement5.orders.length>=8'));});
test('reports retain physical quality, deliveries and payments and are read-only',()=>{funded();r(`buyProcurement5(${order()});for(let i=0;i<4;i++)nextWeek()`);const s=snap();r('performanceReport5("suppliers",4)');assert.equal(snap(),s);near(r('performanceReport5("suppliers",4).rows.find(r=>r.id==="harbor").values.received'),20);});
test('legacy spot purchase remains unchanged and old save migrates with empty procurement',()=>{own();r('var cash=state.cash,unit=getBeanCost("brazil");orderBeans("brazil",10);var v=JSON.parse(JSON.stringify(state));delete v.procurement5;v=validateSave(v)');near(r('state.cash'),r('cash-10*unit'));assert.equal(r('v.procurement5.orders.length'),0);assert.equal(r('state.shipments.at(-1).due'),2);});
test('malformed units, unpaid invoices, shipment links, statuses and histories reject',()=>{funded();r(`buyProcurement5(${order('harbor',2)});for(let i=0;i<4&&!state.procurement5.payables.length;i++)nextWeek()`);for(const mutation of ['v.procurement5.orders[0].cost+=1','v.procurement5.orders[0].paid=-1','v.procurement5.payables[0].amount+=1','v.procurement5.payables[0].due+=1','v.procurement5.payables.push({...v.procurement5.payables[0],id:"duplicate"})','v.procurement5.orders[0].status="missing"','v.procurement5.history[0].rows[0].paid="bad"'])assert.throws(()=>r(`var v=JSON.parse(JSON.stringify(state));${mutation};validateSave(v)`));});

test('delivery crisis updates the real purchase and survives save and actual receipt',()=>{funded();r(`var o=buyProcurement5(${order('cooperative')});var randomBefore=random3;random3=()=>.99;generateIncident();random3=randomBefore;var delayedDue=state.shipments[0].due;validateSave(JSON.parse(JSON.stringify(state)));for(let i=0;i<8;i++)nextWeek()`);assert(r('o.due>=delayedDue'));assert.equal(r('o.status'),'received');assert.equal(r('state.procurement5.events.filter(e=>e.kind==="arrival").length'),1);});
test('paid express crisis delivers once before the original date with receipt-relative credit',()=>{funded();r(`var o=buyProcurement5(${order('cargo',2,40)});state.incidents.push({id:uid('incident'),type:'delivery',kind:'shipment',target:o.id,title:'Test přepravy',details:'Test',created:state.week,due:state.week+2});var cash=state.cash;resolveIncident(state.incidents[0].id,'express');validateSave(JSON.parse(JSON.stringify(state)));nextWeek()`);near(r('cash-state.history.at(-1).detail.crises'),r('cash-18000'));assert.equal(r('o.received'),1);assert.equal(r('state.procurement5.payables[0].due'),3);assert.equal(r('state.procurement5.events.filter(e=>e.kind==="arrival").length'),1);r('for(let i=0;i<5;i++)nextWeek()');assert.equal(r('state.procurement5.events.filter(e=>e.kind==="arrival").length'),1);});
test('supplier cost and actual quality enter the physical roasted batch provenance',()=>{funded();r(`var o=buyProcurement5(${order('altitude')});state.green=[];for(let i=0;i<5;i++)nextWeek();state.blends[0].primary='brazil';state.blends[0].share=100;manualRoast(state.roasters[0].id,state.blends[0].id,10);var trace=state.craft5.ledger.at(-1)`);assert.equal(r('trace.sources.length'),1);near(r('trace.sources[0].unit'),r('o.unit'));near(r('trace.sources[0].quality'),r('o.quality'));near(r('trace.sources[0].kg'),10);assert.equal(r('trace.sources[0].source.name'),'Altitude Selection');near(r('trace.unit*trace.output'),r('10*o.unit+trace.processing'));});
test('automatic settlement is included in actual weekly cash movement',()=>{funded();r(`var o=buyProcurement5(${order('harbor',2)});while(!state.procurement5.payables.length)nextWeek();while(state.week<state.procurement5.payables[0].due)nextWeek();var cash=state.cash,h=nextWeek()`);near(r('h.cashChange'),r('Math.round(state.cash-cash)'));near(r('h.detail.procurementPayments'),r('o.cost'));});
test('active contract books twelve calendar orders then expires without another charge',()=>{funded();r(`var c=signProcurement5({...${order()},weeks:12});for(let i=0;i<16;i++){nextWeek();validateSave(JSON.parse(JSON.stringify(state)))}`);assert.equal(r('state.procurement5.orders.filter(o=>o.contract===c.id).length'),12);assert.equal(r('c.status'),'expired');});
test('sixty founder weeks with supplier purchases preserve solvency without added capital',()=>{own();r(`buyProcurement5(${order('harbor',0,5)});for(let i=0;i<60;i++){if(i%12===6)buyProcurement5(${order('harbor',0,5)});nextWeek();validateSave(JSON.parse(JSON.stringify(state)));if(state.over)throw Error('Founder failed')}`);assert.equal(r('state.week'),61);assert(r('state.cash>0'));assert.equal(r('state.procurement5.orders.length'),6);});

console.log(`${passed} procurement scenarios passed.`);
