const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
const files=[...fs.readFileSync('dist/index.html','utf8').matchAll(/<script src="([^"]+)"/g)].map(x=>x[1]).filter(f=>f!=='app.js'&&!f.endsWith('-ui.js')&&f!=='game-renderer.js');
function game(){const c=vm.createContext({Intl,console});for(const f of files)vm.runInContext(fs.readFileSync('dist/'+f,'utf8'),c,{filename:f});return s=>vm.runInContext(s,c);}
const start=id=>`startOpening6('cafe',{location:'${id}',design:'starter',options:{kind:'legacy',space:'starter'}});signCoffeeAgreement6('local','${id}','blend-1',{enabled:true,target:25,budget:20000,reserve:1});`;
let passed=0;const valid=r=>{r('validateSave(JSON.parse(JSON.stringify(state)))');assert(r('Math.abs(state.history.at(-1).profit-(state.history.at(-1).revenue-state.history.at(-1).expenses-state.history.at(-1).cogs-state.history.at(-1).interest-state.history.at(-1).spoil+(state.history.at(-1).detail.propertyGain||0)))<=3'));};
for(const id of ['district-0-2','karlin']){const r=game();r(`state=fresh('sandbox','relaxed');${start(id)}`);for(let i=0;i<52;i++){r('nextWeek()');assert(!r('state.over'),id+' bankrupt');if(i%13===12)valid(r);}r('var weeks=state.history.filter(h=>h.week>=7),s=state.stores[0];');assert(r('weeks.filter(h=>h.profit>0).length>=40&&weeks.slice(-13).reduce((n,h)=>n+h.profit,0)/13>8000&&state.cash>500000&&state.debt===0&&state.founderShare===100&&state.roasters.length===0&&state.offices.length===0&&s.daily.shifts.join()==="1,1,1"&&s.crew.employees.length===2&&s.marketing===500'));console.log('PASS: '+id+' real 500k relaxed founder, paid opening, ordinary menu/crew, 52 weeks, no added cash/loans/investors; last-quarter mean '+r('Math.round(weeks.slice(-13).reduce((n,h)=>n+h.profit,0)/13)'));passed++;}
// Real competitors, auctions, rent renewal and paid expansion. Second branch waits for its full budget.
const r=game();r(`state=fresh('sandbox','relaxed');${start('district-0-2')}var secondWeek=null;`);
for(let i=0;i<104;i++){if(r('!secondWeek&&state.week>7&&!owned("karlin")&&!occupant("karlin")&&!state.auctions.some(a=>!a.closed&&a.location==="karlin")&&!state.market3.exclusive.some(a=>a.location==="karlin"&&a.holder!=="player"&&a.until>=state.week)&&state.cash>openingFunding6(openingQuote6("cafe",{location:"karlin",design:"starter",options:{kind:"legacy",space:"starter"}})).required+weeklyFixed()*3'))r(`secondWeek=state.week;${start('karlin')}`);r('nextWeek()');assert(!r('state.over'),'pair bankrupt');if(i%13===12)valid(r);}
assert(r('secondWeek!==null&&state.stores.length===2&&state.debt===0&&state.founderShare===100&&state.history.slice(-26).filter(h=>h.profit>0).length>=24&&state.stores.every(s=>s.last.profit>0)&&state.history.slice(-26).reduce((n,h)=>n+h.profit,0)>300000&&state.stores.every(s=>s.last.stockLost===0)'));console.log('PASS: actual Pankrac + Karlin paid from 500k and earned revenue, second opens T'+r('secondWeek')+', 104 weeks including real competition, no financing');passed++;
const pair=r('JSON.stringify(state)');
r('var before=JSON.stringify(state),plans=coffeeReplenishmentPlans20(),guide=cafeProfitGuide15("karlin");');assert(r('before===JSON.stringify(state)&&plans.size===2&&[...plans.values()].every(q=>q.target===50)&&guide.costs.people>0&&guide.supply.target===50&&guide.breakEven>0'));console.log('PASS: pure combined targets, no double use of stock or forecasts; actual costs and break-even guide');passed++;
r('state=JSON.parse('+JSON.stringify(pair)+');for(const a of state.bootstrap6.suppliers)setCoffeeAgreement6(a.id,{enabled:true,target:50,budget:100000,reserve:1});var plans=coffeeReplenishmentPlans20(),expected=[...plans.values()].reduce((n,p)=>n+(p.need>=5?Math.min(100,p.need):0),0),cash=state.cash,count=state.bootstrap6.orders.length;runCoffeeAgreements6();var orders=state.bootstrap6.orders.slice(count),paid=orders.reduce((n,o)=>n+o.cost,0);');assert(r('expected>0&&orders.length===2&&orders.reduce((n,o)=>n+o.kg,0)===expected&&state.cash===cash-paid&&orders.every(o=>o.received===null&&o.due===state.week+1)&&stock("blend-1","Praha")===plans.values().next().value.stock'));r('count=state.bootstrap6.orders.length;cash=state.cash;runCoffeeAgreements6();');assert(r('state.bootstrap6.orders.length===count&&state.cash===cash'));console.log('PASS: two physical paid shares, exact debit, one-week shipping, incoming counted once and repeated replenishment cannot double buy');passed++;
r('state=JSON.parse('+JSON.stringify(pair)+');for(const a of state.bootstrap6.suppliers)setCoffeeAgreement6(a.id,{enabled:true,target:100,budget:0,reserve:1});var cash=state.cash,count=state.bootstrap6.orders.length;runCoffeeAgreements6();');assert(r('state.cash===cash&&state.bootstrap6.orders.length===count&&state.bootstrap6.suppliers.every(a=>a.last.reason.includes("limit"))'));r('state.cash=1;for(const a of state.bootstrap6.suppliers)setCoffeeAgreement6(a.id,{enabled:true,target:100,budget:100000,reserve:8});runCoffeeAgreements6();');assert(r('state.cash===1&&state.bootstrap6.orders.length===count&&state.bootstrap6.suppliers.every(a=>a.last.reason.includes("rezervu"))'));console.log('PASS: existing budget and protected cash reserve still block orders, no free inventory');passed++;
r('state=JSON.parse('+JSON.stringify(pair)+');state.bootstrap6.orders=[];state.batches=state.batches.slice(0,1);state.batches[0].roastedWeek=state.week-7;var before=JSON.stringify(state),plans=coffeeReplenishmentPlans20();');assert(r('[...plans.values()].every(p=>p.stock===0)&&JSON.stringify(state)===before'));r('state=JSON.parse('+JSON.stringify(pair)+');state.bootstrap6.suppliers.forEach(a=>a.enabled=false);var count=state.bootstrap6.orders.length,cash=state.cash;runCoffeeAgreements6();');assert(r('state.cash===cash&&state.bootstrap6.orders.length===count'));console.log('PASS: soon-expiring coffee does not cover future deliveries, paused suppliers cannot buy');passed++;
// The existing saved company is unchanged on switching; advantages affect only future real sales.
{const f=game();f(`state=fresh('sandbox','normal');${start('karlin')}for(let i=0;i<12;i++)nextWeek();var before={cash:state.cash,rent:JSON.stringify(state.stores[0].lease),crew:JSON.stringify(state.stores[0].crew),history:JSON.stringify(state.history)},forecasts=Object.keys(DIFFICULTIES).map(level=>tnPure7(()=>{state.difficulty=level;return tycoonForecast7("karlin");})),q=difficultyQuote12('relaxed');setDifficulty12('relaxed',q);`);assert(f('before.cash===state.cash&&before.rent===JSON.stringify(state.stores[0].lease)&&before.crew===JSON.stringify(state.stores[0].crew)&&before.history===JSON.stringify(state.history)&&forecasts[0].served>forecasts[1].served&&forecasts[1].served>forecasts[2].served&&DIFFICULTIES.normal.demand===1.18&&CUSTOMER_SERVICE15.normal===1.5&&DIFFICULTIES.expert.demand===.92&&CUSTOMER_SERVICE15.expert===1'));f('state=validateSave(JSON.parse(JSON.stringify(state)));nextWeek()');valid(f);console.log('PASS: existing save/difficulty switch preserves cash, contracts and all closed reports, improves real future service; Standard and Expert settings preserved');passed++;}
// Profit still needs actual coffee and actual people even on the easy level.
r('state=JSON.parse('+JSON.stringify(pair)+');state.batches=[];state.bootstrap6.orders=[];state.bootstrap6.suppliers.forEach(a=>a.enabled=false);nextWeek();');assert(r('state.stores.every(s=>s.last.served===0&&s.last.revenue===0&&s.last.profit<0&&s.last.detail.wages>0)'));valid(r);console.log('PASS: zero coffee still means zero sales and genuinely paid loss; no guaranteed/imaginary profit');passed++;
console.log('PASS: '+passed+' easy-level economy and shared supply scenarios');
