const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');const c=vm.createContext({Intl});for(const f of ['engine','tycoon','empire','operations','reports'])vm.runInContext(fs.readFileSync('dist/'+f+'.js','utf8'),c);const run=s=>vm.runInContext(s,c);let passed=0;function test(name,fn){run('state=fresh()');fn();run('validateSave(JSON.parse(JSON.stringify(state)))');passed++;console.log('PASS:',name)}
test('opening every report is pure and an unplayed company has no invented results',()=>{const before=run('JSON.stringify(state)');for(const kind of run('Object.keys(REPORT_GROUPS5)'))for(const weeks of [1,4,13]){const r=run(`performanceReport5('${kind}',${weeks})`);assert.equal(r.count,0);assert(r.rows.every(row=>row.points.length===0&&row.trend===null));}assert.equal(run('JSON.stringify(state)'),before);});
test('weekly records reconcile cafe sales, manufacturing expenses, harvest costs and corporate results',()=>{run('state.cash=10000000;buyEstate("cerrado");state.estates[0].cycle=11;nextWeek()');assert.equal(run('performanceReport5("stores").rows[0].values.profit'),run('state.stores[0].last.profit'));assert.equal(run('performanceReport5("roasters").rows[0].values.cost'),run('state.history.at(-1).detail.roasters'));assert.equal(run('performanceReport5("estates").rows[0].values.cost'),run('state.history.at(-1).detail.estates'));assert.equal(run('performanceReport5("firms").rows[0].values.profit'),run('state.history.at(-1).profit'));assert.equal(run('performanceReport5("firms").rows[1].values.revenue'),null);assert.equal(run('state.performance5.length'),1);});
test('manual roasting is included in the recorded factory output',()=>{run('state.roasters[0].auto=false;manualRoast("roaster-1","blend-1",20);nextWeek()');assert.equal(run('performanceReport5("roasters").rows[0].values.output'),17);assert.equal(run('performanceReport5("roasters").rows[0].values.used'),20);});
test('four-week totals and trends use genuine previous windows and newly opened stores get no retroactive credit',()=>{run('for(let i=0;i<5;i++)nextWeek();state.cash+=1000000;openStore("letna");nextWeek()');const r=run('performanceReport5("stores",4)');assert.equal(r.count,4);assert.equal(r.rows[0].values.profit,run('state.performance5.slice(-4).reduce((a,s)=>a+s.records.find(r=>r.kind==="stores"&&r.id==="karlin").values.profit,0)'));assert.equal(r.rows[0].previousCount,2);assert.equal(r.rows[1].points.length,1);assert.equal(r.rows[1].trend,null);const before=run('JSON.stringify(state)');run('performanceReport5("firms",13)');assert.equal(run('JSON.stringify(state)'),before);});
test('people keep historical assignments and director actions without changing previous records',()=>{run('state.cash=10000000;buyOffice("studio");setDepartment("hr",1);hireExecutive5("hr","candidate-0");hireCandidate("karlin","candidate-1");setMandate5("hr",{...state.organization.policies.hr,enabled:true,budget:12000});nextWeek()');const pid=run('state.stores[0].manager.pid'),before=run('JSON.stringify(state.performance5)');assert.equal(run('performanceReport5("people").rows.find(r=>r.id==="candidate-0").values.actions'),1);assert.equal(run('performanceReport5("departments").rows[0].values.cost'),run('7500+state.organization.executives.hr.manager.salary*1.35'));run('state.stores[0].manager.tenure=4;promotePerson(state.stores[0].manager.pid,"Praha")');assert.equal(run('JSON.stringify(state.performance5)'),before);assert(run(`performanceReport5('people').rows.find(r=>r.id==='${pid}').points[0].scope.includes('Vedoucí kavárny')`));run('fireExecutive5("hr")');assert.equal(run('performanceReport5("people").rows.find(r=>r.id==="candidate-0").historical'),true);});
test('the archive survives export, trims at 26 weeks and rejects malformed records without touching the live state',()=>{run('for(let i=0;i<30&&!state.over;i++)nextWeek()');assert.equal(run('state.performance5.length'),26);assert.equal(run('state.performance5[0].week'),5);const before=run('JSON.stringify(state)');for(const edit of ['bad.performance5.push(bad.performance5[0])','bad.performance5[0].records[0].values.profit="no"','bad.performance5[0].records.push(bad.performance5[0].records[0])','bad.performance5[0].records[0].kind="constructor"']){run('var bad=JSON.parse(JSON.stringify(state));'+edit);assert.throws(()=>run('validateSave(bad)'));assert.equal(run('JSON.stringify(state)'),before);}});
test('old saves seed only known completed results and never reconstruct employee or department performance',()=>{run('nextWeek();var old=JSON.parse(JSON.stringify(state));delete old.performance5');const before=run('JSON.stringify(state)'),migrated=run('validateSave(old)');assert.equal(migrated.performance5.length,1);assert(!migrated.performance5[0].records.some(r=>['people','departments'].includes(r.kind)));assert.equal(run('JSON.stringify(state)'),before);});
console.log(`All ${passed} performance report scenarios passed.`);
