const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
const c=vm.createContext({Intl,console});for(const f of ['engine','tycoon','empire','operations','reports','supply','crew','craft','studio','business','guests','branding','property','rivals'])vm.runInContext(fs.readFileSync('dist/'+f+'.js','utf8'),c);const r=s=>vm.runInContext(s,c),snap=()=>r('JSON.stringify(state)');let passed=0;
function test(name,fn){r('state=fresh()');fn();r('validateSave(JSON.parse(JSON.stringify(state)))');console.log('PASS:',name);passed++;}
function owned(){r('openStore("letna");hireCandidate("letna","candidate-0")');}
function step(){r('nextWeek()');}
test('founder capital stays 650k with no selected cafe and no invented competitor results',()=>{assert.equal(r('state.cash'),650000);assert.equal(r('state.stores.length'),0);assert(r('state.rivals.every(q=>q.operations5.history.length===0&&q.operations5.branches.every(b=>b.last===null))'));});
test('rival branches pay wages, rent and coffee on served guests only and capacity conserves guests',()=>{owned();step();assert(r('state.rivals.every(r=>r.operations5.history[0].branches.every(q=>q.served<=q.capacity&&q.served+q.lost===q.traffic&&q.cost===q.coffee+q.wages+q.rent+q.overhead&&q.revenue===q.served*q.price))'));});
test('cash moves by real operating result minus actual investments',()=>{owned();r('state.rivals.forEach(q=>q.business.expansionDue=1);var before=state.rivals.map(q=>q.cash)');step();assert(r('state.rivals.every((q,i)=>Math.abs(q.cash-before[i]-q.lastProfit+q.operations5.history[0].investment)<.01)'));});
test('short staffed high demand cafe hires before expansion and keeps its cash reserve',()=>{owned();r('var rival=state.rivals[0],b=rival.operations5.branches[0];b.staff=1;rival.cash=6000000;rival.business.expansionDue=1');step();assert.equal(r('rival.operations5.review.chosen.kind'),'staff');assert(r('rival.cash>=rival.operations5.review.reserve'));assert.equal(r('rival.operations5.history[0].investment'),8000);});
test('maintenance becomes a funded capacity repair, not free quality',()=>{owned();r('var rival=state.rivals[0],b=rival.operations5.branches[0];b.staff=3;b.condition=45;rival.cash=6000000;rival.business.expansionDue=1');step();assert.equal(r('rival.operations5.review.chosen.kind'),'service');assert.equal(r('b.condition'),95);assert.equal(r('rival.operations5.history[0].investment'),18000);});
test('low cash blocks investment while preserving an explanation',()=>{owned();r('var rival=state.rivals[0];rival.cash=0;rival.business.expansionDue=1');step();assert.equal(r('rival.operations5.review.chosen'),null);assert.equal(r('rival.operations5.review.spent'),0);assert(r('rival.operations5.review.alternatives.every(q=>!q.allowed)'));});
test('local price affects pressure in its own city and leaves another city unchanged',()=>{const a=r('rivalLocalPrice5(state.rivals[0],"Brno")');r('state.rivals[0].operations5.branches.find(b=>loc(b.id).city==="Praha").price=1.3');assert.equal(r('rivalLocalPrice5(state.rivals[0],"Brno")'),a);assert.equal(r('rivalLocalPrice5(state.rivals[0],"Praha")'),1.3);});
test('price optimizer uses capacity and profit, and does not apply one price to all branches',()=>{owned();r('var rival=state.rivals[0];rival.cash=6000000;rival.operations5.branches[0].price=.75;rival.business.expansionDue=1');step();assert(r('rival.business.decisions.some(q=>q.text==="Úprava místních cen")'));assert(r('rival.operations5.branches[0].price>.75'));});
test('three losing weeks prioritize funded closure and release only the chosen address',()=>{owned();r('var rival=state.rivals[0],b=rival.operations5.branches[0],id=b.id;b.staff=9;b.quality=1;b.condition=45;b.price=.75;b.lossWeeks=3;rival.cash=6000000;rival.business.expansionDue=1');step();assert.equal(r('rival.operations5.review.chosen.kind'),'close');assert(!r('rival.stores.includes(id)'));assert.equal(r('rival.stores.length'),1);assert(r('rival.operations5.history[0].branches.some(q=>q.id===id)'));});
test('new competitor addresses are funded and unique across the entire market',()=>{owned();r('state.rivals.forEach(q=>{q.cash=6000000;q.business.expansionDue=1;q.operations5.branches.forEach(b=>b.staff=9)})');step();assert(r('new Set([...state.stores.map(s=>s.id),...state.rivals.flatMap(q=>q.stores)]).size===state.stores.length+state.rivals.reduce((n,q)=>n+q.stores.length,0)'));assert(r('state.rivals.every(q=>q.operations5.review.spent===(q.operations5.review.chosen?.cost||0))'));});
test('report gives actual firm revenues and all branch results, read-only',()=>{owned();step();const s=snap();r('performanceReport5("rivalstores",1);performanceReport5("firms",1)');assert.equal(snap(),s);assert.equal(r('performanceReport5("rivalstores",1).rows.filter(q=>q.points.length).length'),4);assert(r('performanceReport5("firms",1).rows.filter(q=>q.id!=="player").every(q=>q.values.revenue!==null)'));});
test('historical branch price and staff survive subsequent changes',()=>{owned();step();r('var old=JSON.stringify(state.rivals[0].operations5.history[0]);state.rivals[0].operations5.branches[0].price=1.3;state.rivals[0].operations5.branches[0].staff=9');step();assert.equal(r('JSON.stringify(state.rivals[0].operations5.history[0])'),r('old'));});
test('old 05.9 save migrates without fabricated results or changed capital',()=>{owned();step();r('var v=JSON.parse(JSON.stringify(state)),cash=v.cash;v.rivals.forEach(q=>delete q.operations5);v.performance5.forEach(h=>h.records=h.records.filter(q=>q.kind!=="rivalstores"));v=validateSave(v)');assert.equal(r('v.cash'),r('cash'));assert(r('v.rivals.every(q=>q.operations5.history.length===0&&q.operations5.branches.every(b=>b.last===null))'));});
test('acquisition inherits actual branch price and staff and leaves historical reports',()=>{owned();step();r('var rival=state.rivals[0],id=rival.stores[0];rival.operations5.branches[0].price=1.22;rival.operations5.branches[0].staff=7;state.cash=10000000;acquireRival(rival.id)');assert.equal(r('state.stores.find(q=>q.id===id).staff'),7);assert.equal(r('state.stores.find(q=>q.id===id).price'),r('round(loc(id).ideal*1.22)'));assert.equal(r('rival.operations5.branches.length'),0);assert(r('performanceReport5("rivalstores",1).rows.some(q=>q.historical)'));});
test('forecast is pure and current rival strategy replays identically to actual weeks',()=>{owned();const s=snap(),f=r('previewProperty5({kind:"lease",location:"letna",lease:"secure"},4)');assert.equal(snap(),s);r('signPropertyLease5("letna","secure");for(let i=0;i<4;i++)nextWeek()');assert(Math.abs(r('state.cash')-f.changed.series.at(-1).cash)<.02);});
test('malformed branch budgets, histories, costs, reservations and duplicate addresses reject',()=>{owned();step();for(const mutation of ['v.rivals[0].operations5.branches[0].staff=0','v.rivals[0].operations5.branches[0].price=5','v.rivals[0].operations5.branches.push({...v.rivals[0].operations5.branches[0]})','v.rivals[0].operations5.history[0].branches[0].served+=1','v.rivals[0].operations5.history[0].cost+=1','v.rivals[0].operations5.history[0].profit="bad"'])assert.throws(()=>r(`var v=JSON.parse(JSON.stringify(state));${mutation};validateSave(v)`));});
test('80 founder weeks and every competitor save survive without injected player money',()=>{owned();for(let i=0;i<80;i++){r('if(state.roasters[0].condition<65&&state.cash>weeklyFixed()*3+18000)maintainRoaster("roaster-1");nextWeek();validateSave(JSON.parse(JSON.stringify(state)))');assert(!r('state.over'));}assert(r('state.rivals.every(q=>q.operations5.history.length<=26)'));assert(r('state.rivals.some(q=>q.operations5.review?.chosen)'));});
test('last week of a partnership is paid and charged once even after contract expiry',()=>{owned();r('state.contracts.push({id:"expiry-test",name:"Partner",blend:"blend-1",kg:1,price:620,remaining:1,fulfilled:0,last:null,buyer:"north"});var opening=state.rivals[2].cash');step();assert.equal(r('state.contracts.length'),0);assert.equal(r('state.rivals[2].operations5.history[0].partnerCost'),620);assert.equal(r('state.rivals[2].cash-opening'),r('state.rivals[2].lastProfit-state.rivals[2].operations5.history[0].investment'));});
test('saving forged chosen-action reserve and cash budgets rejects',()=>{owned();r('state.rivals[0].cash=6000000;state.rivals[0].business.expansionDue=1');step();for(const mutation of ['v.rivals[0].operations5.review.spent+=1','v.rivals[0].operations5.review.chosen.allowed=false','v.rivals[0].operations5.review.reserve=1e10'])assert.throws(()=>r(`var v=JSON.parse(JSON.stringify(state));${mutation};validateSave(v)`));});
test('insolvent competitor releases all addresses but retains the last paid operating history',()=>{owned();r('var rival=state.rivals[0];rival.cash=0;rival.operations5.branches.forEach(b=>{b.staff=9;b.quality=1;b.condition=45;b.price=.75})');step();assert(r('rival.bankrupt'));assert.equal(r('rival.stores.length'),0);assert.equal(r('rival.operations5.branches.length'),0);assert.equal(r('rival.operations5.history.length'),1);});
test('maximum player network and retired rival branch records stay within the report bound',()=>{owned();step();r('state.cash=200000000;for(const rival of state.rivals)if(!rival.bankrupt)acquireRival(rival.id);state.stores=LOCATIONS.map(l=>makeStore(l.id));state.studio5.opening=false;for(const s of state.stores)hire(s.id,0);while(state.roasters.length<8)buyRoaster("artisan","Výroba "+state.roasters.length);for(const q of state.roasters)hire(q.id,0,"roaster");nextWeek()');assert.equal(r('performanceReport5("premises",1).rows.length'),111);assert(r('state.performance5.at(-1).records.length<=600'));assert(r('performanceReport5("rivalstores",4).rows.filter(q=>q.historical).length>=4'));});
test('reserve for hiring includes the added weekly wage before the payment',()=>{owned();r('var rival=state.rivals[0];rival.operations5.branches[0].staff=1;var before=rivalReserve5(rival),choices=rivalChoices5(rival),hiring=choices.find(q=>q.kind==="staff");');assert.equal(r('hiring.reserve-before'),32500);r('rival.cash=before+8001;choices=rivalChoices5(rival)');assert(!r('choices.find(q=>q.kind==="staff").allowed'));});
test('expansion reserve includes five weeks of the new cafe expenses',()=>{owned();r('var rival=state.rivals[0];rival.cash=6000000;var before=rivalReserve5(rival),expansion=rivalChoices5(rival).find(q=>q.kind==="expand")');assert.equal(r('expansion.reserve-before'),r('rivalOperating5(rival,rivalBranch5(rival,expansion.id)).fixed*5'));});
console.log(`${passed} rival scenarios passed.`);
