const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
const c=vm.createContext({Intl,console});for(const f of ['engine','tycoon','empire','operations','reports','supply','crew','craft','studio','business','guests','branding','property','rivals','seasons'])vm.runInContext(fs.readFileSync('dist/'+f+'.js','utf8'),c);const r=s=>vm.runInContext(s,c),snap=()=>r('JSON.stringify(state)'),near=(a,b)=>assert(Math.abs(a-b)<.00001,`${a} != ${b}`);let passed=0;
function test(name,fn){r('state=fresh()');fn();r('validateSave(JSON.parse(JSON.stringify(state)))');passed++;console.log('PASS:',name)}
function own(){r('openStore("letna");hireCandidate("letna","candidate-0")')}
test('founder capital, empty cafe network and historical records stay unchanged',()=>{assert.equal(r('state.cash'),650000);assert.equal(r('state.stores.length'),0);assert.equal(r('state.seasons5.history.length'),0);const s=snap();assert.throws(()=>r('nextWeek()'));assert.equal(snap(),s);});
test('Australia has reversed summer and winter while all eighteen cities have valid local factors',()=>{assert.equal(r('citySeason5("Praha",1).season'),'Zima');assert.equal(r('citySeason5("Sydney",1).season'),'Léto');assert.equal(r('citySeason5("Melbourne",27).season'),'Zima');assert(r('CITIES.every(c=>Object.values(citySeason5(c.name,1).factors).every(n=>n>=.65&&n<=1.35))'));});
test('local calendar is deterministic, announced and does not consume rng or ids',()=>{const s=snap();r('var a=JSON.stringify(seasonCalendar5("Praha",13)),b=JSON.stringify(seasonCalendar5("Praha",13))');assert.equal(r('a'),r('b'));assert.equal(snap(),s);});
test('seasons and event schedules repeat after 52 weeks with a new year',()=>{assert.equal(r('citySeason5("Praha",1).season'),r('citySeason5("Praha",53).season'));assert.equal(r('citySeason5("Praha",53).year'),2);assert.equal(r('JSON.stringify(citySeason5("Brno",20).events)'),r('JSON.stringify(citySeason5("Brno",72).events)'));});
test('a festival belongs to the scheduled city and affects tourist groups more than offices',()=>{assert(r('citySeason5("Praha",17).events.includes("festival")'));assert(!r('citySeason5("Brno",17).events.includes("festival")'));assert(r('citySeason5("Praha",17).factors.tourist>citySeason5("Praha",17).factors.office'));});
test('year-end holidays and summer break reduce office and student demand locally',()=>{assert(r('citySeason5("Praha",52).factors.office<1'));assert(r('citySeason5("Praha",52).factors.student<1'));assert(r('citySeason5("Praha",26).factors.student<citySeason5("Praha",26).factors.community'));});
test('tropical and hot city profiles use their own model temperatures',()=>{assert(r('citySeason5("Singapur",1).temperature>20'));assert(r('citySeason5("Dubaj",27).temperature>30'));});
test('calendar rejected horizons and invalid cities or weeks leave company untouched',()=>{const s=snap();for(const query of ['seasonCalendar5("missing",4)','seasonCalendar5("Praha",5)','citySeason5("Praha",0)','citySeason5("Praha",1.5)','citySeason5("Praha",1000001)'])assert.throws(()=>r(query));assert.equal(snap(),s);});
test('cold brew menu shares increase in warm weather without creating unavailable drinks',()=>{own();r('var s=state.stores[0];s.equipment.coldbrew={condition:100};s.menu.coldbrew.enabled=true;var cold=menuSummary(s).drinks.find(d=>d.id==="coldbrew").weight;state.week=26;var warm=menuSummary(s).drinks.find(d=>d.id==="coldbrew").weight');assert(r('warm>cold'));r('delete s.equipment.coldbrew');assert(!r('menuSummary(s).drinks.some(d=>d.id==="coldbrew")'));});
test('seasonal hot drink gains winter share and mixture recalculates actual dose, costs and preparation',()=>{own();r('var s=state.stores[0];s.menu.seasonal.enabled=true;var winter=menuSummary(s);state.week=26;var summer=menuSummary(s)');assert(r('winter.drinks.find(d=>d.id==="seasonal").weight>summer.drinks.find(d=>d.id==="seasonal").weight'));near(r('summer.dose'),r('summer.drinks.reduce((n,d)=>n+d.dose*d.weight,0)/summer.total'));assert(r('summer.cost>0&&summer.minutes>0'));});
test('seasonal cafe production adjustment leaves wholesale and routes as separate fixed orders',()=>{own();r('var base=SEASON_BASE5.productionNeeds(),actual=productionNeeds(),s=state.stores[0],expected=loc(s.id).traffic*(menuSummary(s).dose||.018)*1.22*(seasonDemandFactor5(s)-1)');near(r('actual["blend-1"]-base["blend-1"]'),r('expected'));r('state.contracts.push({id:"test-trade",name:"Obchod",blend:"blend-1",kg:10,price:600,remaining:12,fulfilled:0,last:null});var later=productionNeeds()');near(r('later["blend-1"]-actual["blend-1"]'),10);});
test('city-specific needs do not include cafes outside its delivery coverage',()=>{own();near(r('productionNeeds("Brno")["blend-1"]||0'),0);});
test('guest season mix changes proportions once and preserves the original total weight',()=>{own();r('state.week=52;var s=state.stores[0],a={demand:1000,menu:menuSummary(s)},b={demand:1000,menu:menuSummary(s)};SEASON_BASE5.guestDemand5(s,a);guestDemand5(s,b)');near(r('a.guests5.groups.reduce((n,g)=>n+g.weight,0)'),r('b.guests5.groups.reduce((n,g)=>n+g.weight,0)'));assert.equal(r('a.demand'),r('b.demand'));assert(r('b.guests5.groups.find(g=>g.id==="office").weight<a.guests5.groups.find(g=>g.id==="office").weight'));});
test('new local calendar replaces the old simultaneous global rain or festival modifier',()=>{own();r('state.week=7;nextWeek()');assert.equal(r('state.event'),null);assert.equal(r('state.seasons5.history.at(-1).week'),7);assert(r('state.history.at(-1).event.includes("Místní")'));});
test('actual history conserves visitors and records consumed coffee instead of estimated sales',()=>{own();r('nextWeek();var row=state.seasons5.history[0].stores[0],s=state.stores[0]');assert.equal(r('row.served'),r('s.last.served'));assert.equal(r('row.used'),r('s.last.used'));assert.equal(r('row.arrivals'),r('row.served+row.lost'));assert.equal(r('state.seasons5.history[0].cities.length'),18);});
test('physical shortage remains a lost sale during a festival and creates no coffee',()=>{own();r('state.week=17;state.green=[];state.batches=[];state.roasters.forEach(q=>q.auto=false);nextWeek()');assert.equal(r('state.seasons5.history[0].stores[0].served'),0);assert.equal(r('state.seasons5.history[0].stores[0].used'),0);assert(r('state.seasons5.history[0].stores[0].lost>0'));});
test('actual four-week forecast is pure and equals running the same company normally',()=>{own();const s=snap(),f=r('seasonForecast5("Praha",4)');assert.equal(snap(),s);r('for(let i=0;i<4;i++)nextWeek()');assert.equal(r('state.history.at(-1).cash'),f.series.at(-1).cash);assert.equal(r('state.seasons5.history.at(-1).stores.reduce((n,s)=>n+s.served,0)'),f.series.at(-1).served);});
test('empty city forecast still shows firm finances and zero city sales',()=>{own();const s=snap(),f=r('seasonForecast5("Sydney",4)');assert.equal(snap(),s);assert(f.series.every(h=>h.served===0&&h.used===0&&Number.isFinite(h.cash)));});
test('forecast requires an opened cafe but calendar remains available before opening',()=>{const s=snap();assert.throws(()=>r('seasonForecast5("Praha",4)'));assert.equal(r('seasonCalendar5("Praha",4).length'),4);assert.equal(snap(),s);});
test('past weather, prices and city visits are immutable after another week and menu change',()=>{own();r('nextWeek();var before=JSON.stringify(state.seasons5.history[0]);updateMenu("letna","espresso",{price:120,enabled:true});nextWeek()');assert.equal(r('JSON.stringify(state.seasons5.history[0])'),r('before'));});
test('old 05.10 save receives an empty calendar without a cash or history rewrite',()=>{own();r('nextWeek();var v=JSON.parse(JSON.stringify(state)),cash=v.cash,history=JSON.stringify(v.history);delete v.seasons5;v=validateSave(v)');assert.equal(r('v.cash'),r('cash'));assert.equal(r('JSON.stringify(v.history)'),r('history'));assert.equal(r('v.seasons5.history.length'),0);});
test('malformed dates, weather, city factors, duplicate addresses and conservation reject',()=>{own();r('nextWeek()');for(const mutation of ['v.seasons5.history[0].week=99','v.seasons5.history[0].cities[0].temperature=99','v.seasons5.history[0].cities[0].factors.office=2','v.seasons5.history[0].stores[0].served+=1','v.seasons5.history[0].stores[0].factor=1.2','v.seasons5.history[0].stores.push({...v.seasons5.history[0].stores[0]})','v.seasons5.history[0].cities[0].events=["fake"]'])assert.throws(()=>r(`var v=JSON.parse(JSON.stringify(state));${mutation};validateSave(v)`));});
test('80 founder weeks survive the entire year with no additional player funding',()=>{own();for(let i=0;i<80;i++){r('if(state.roasters[0].condition<65&&state.cash>weeklyFixed()*3+18000)maintainRoaster("roaster-1");nextWeek();validateSave(JSON.parse(JSON.stringify(state)))');assert(!r('state.over'));}assert.equal(r('state.seasons5.history.length'),26);assert(r('new Set(state.seasons5.history.map(h=>h.cities[0].season)).size>=2'));});
test('maximum funded 111-cafe network records every cafe and keeps valid bounded reporting',()=>{r('state.cash=200000000;state.stores=LOCATIONS.map(l=>makeStore(l.id));state.studio5.opening=false;state.rivals.forEach(q=>{q.bankrupt=true;q.stores=[];syncRivalBranches5(q)});for(const s of state.stores)hire(s.id,0);while(state.roasters.length<8)buyRoaster("artisan","Výroba "+state.roasters.length);for(const q of state.roasters)hire(q.id,0,"roaster");nextWeek()');assert.equal(r('state.seasons5.history[0].stores.length'),111);assert.equal(r('state.seasons5.history[0].cities.length'),18);assert(r('state.performance5.at(-1).records.length<=600'));const s=snap();r('seasonCalendar5("Praha",13)');assert.equal(snap(),s);});
console.log(`${passed} season scenarios passed.`);
