const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');const c=vm.createContext({Intl,console});for(const f of [...fs.readFileSync('dist/index.html','utf8').matchAll(/<script src="([^"]+)"/g)].map(x=>x[1]).filter(x=>x!=='app.js'&&!x.endsWith('-ui.js')))vm.runInContext(fs.readFileSync('dist/'+f,'utf8'),c);const r=s=>vm.runInContext(s,c),snap=()=>r('JSON.stringify(state)'),near=(a,b,t=.02)=>assert(Math.abs(a-b)<t,`${a} != ${b}`);let passed=0;function test(name,fn){r('state=fresh()');fn();r('validateSave(JSON.parse(JSON.stringify(state)))');passed++;console.log('PASS:',name);}function worn(){r('openStore("letna");state.cash=20000000;buyRoaster("artisan","Vlastní pražírna");var b=buyBakery5("atelier","Praha");for(const e of Object.values(state.stores[0].equipment))e.condition=75;state.stores[0].serviceCondition=80;state.roasters[1].condition=60;b.condition=65');}
test('fresh company has a pure empty quote and cannot be charged for healthy equipment',()=>{const s=snap();r('var q=serviceAllQuote6()');assert.equal(snap(),s);assert.equal(r('q.total'),0);assert.equal(r('q.items.length'),0);assert.throws(()=>r('serviceAll6()'));assert.equal(snap(),s);});
test('one payment repairs actual cafe devices, owned roaster and bakery; operating control is not double charged',()=>{worn();r('var q=serviceAllQuote6(),cash=state.cash,pending=state.pendingExpense3||0,receipt=serviceAll6("all",q)');near(r('cash-state.cash'),r('q.total'));near(r('state.pendingExpense3-pending'),r('q.total'));assert(r('Object.values(state.stores[0].equipment).every(e=>e.condition===100)'));assert.equal(r('state.stores[0].serviceCondition'),100);assert.equal(r('state.roasters[1].condition'),100);assert.equal(r('b.condition'),100);assert(!r('q.items.some(x=>x.kind==="premises")'));assert.equal(r('receipt.cashBefore-receipt.cashAfter'),r('q.total'));});
test('service scope keeps unselected factories intact and receipt history is immutable after wear',()=>{worn();r('var q=serviceAllQuote6("cafes");serviceAll6("cafes",q);var receipt=JSON.stringify(state.services6.history[0]);nextWeek()');assert(r('state.roasters[1].condition<100&&b.condition<100'));assert.equal(r('JSON.stringify(state.services6.history[0])'),r('receipt'));});
test('insufficient total cash rejects the entire batch before any device or money changes',()=>{worn();r('state.cash=serviceAllQuote6().total-1');const s=snap();assert.throws(()=>r('serviceAll6()'));assert.equal(snap(),s);});
test('money and physical-state changes invalidate a previously reviewed quote',()=>{worn();r('var q=serviceAllQuote6();state.cash++');const s=snap();assert.throws(()=>r('serviceAll6("all",q)'));assert.equal(snap(),s);r('state.cash--;state.roasters[1].condition--');const t=snap();assert.throws(()=>r('serviceAll6("all",q)'));assert.equal(snap(),t);});
test('unexpected error midway rolls back all repairs, cash and pending expense',()=>{worn();r('var fn=maintainRoaster;maintainRoaster=function(){throw Error("fixture failure")}');const s=snap();assert.throws(()=>r('serviceAll6()'),/fixture failure/);assert.equal(snap(),s);r('maintainRoaster=fn');});
test('contractor handles its own service; cafe-only operating wear gets one explicit control',()=>{r('openStore("letna");state.cash=20000000;for(const e of Object.values(state.stores[0].equipment))e.condition=100;state.stores[0].serviceCondition=80;state.roasters[0].condition=60;var q=serviceAllQuote6()');assert(!r('q.items.some(x=>x.target==="roaster-1")'));assert.equal(r('q.total'),5000);r('serviceAll6("all",q)');assert.equal(r('state.roasters[0].condition'),60);assert.equal(r('state.stores[0].serviceCondition'),100);});
test('franchise partner equipment never gets charged to the player',()=>{r('openStore("letna");state.cash=20000000;state.reputation=90;openStore("karlin","brand-1","blend-1",true);for(const e of Object.values(state.stores[1].equipment))e.condition=50;var q=serviceAllQuote6()');assert(!r('q.items.some(x=>x.target==="karlin")'));});
test('equipment model determines the exact repair price and survives a historical receipt',()=>{worn();r('buyEquipmentModel5("letna","machine","premium");state.stores[0].equipment.machine.condition=70;var q=serviceAllQuote6("cafes"),line=q.items.find(x=>x.key==="machine");serviceAll6("cafes",q)');assert.equal(r('line.model'),'premium');assert.equal(r('line.cost'),14000);assert(r('line.name.includes("Signature")'));});
test('stored receipt totals, cash conservation and actual repair state reject corruption',()=>{worn();r('serviceAll6()');for(const code of ['v.services6.history[0].total++','v.services6.history[0].cashAfter++','v.services6.history[0].items[0].after=90','v.services6.history[0].items[0].key="constructor"']){r('var v=JSON.parse(JSON.stringify(state))');r(code);assert.throws(()=>r('validateSave(v)'));}});
test('repeated healthy service cannot charge twice and legacy migration grants no repairs or cash',()=>{worn();r('serviceAll6();var v=JSON.parse(JSON.stringify(state)),cash=v.cash;delete v.services6;var restored=validateSave(v)');assert.equal(r('restored.cash'),r('cash'));assert.equal(r('restored.services6.history.length'),0);const s=snap();assert.throws(()=>r('serviceAll6()'));assert.equal(snap(),s);});
console.log(passed+' shared service scenarios passed.');
