const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');const scripts=[...fs.readFileSync('dist/index.html','utf8').matchAll(/<script src="([^"]+)"/g)].map(x=>x[1]).filter(x=>x!=='app.js'&&!x.endsWith('-ui.js'));function game(){const c=vm.createContext({Intl,console});for(const file of scripts)vm.runInContext(fs.readFileSync('dist/'+file,'utf8'),c);return s=>vm.runInContext(s,c);}let passed=0;const near=(a,b)=>assert(Math.abs(a-b)<2,`${a} != ${b}`);
// No hidden price increases, staff changes, added cash, loan, investor, grants or imported equipment.
for(const location of ['letna','karlin','dejvice','smichov']){const r=game(),before=r('JSON.stringify(state)');r(`var data={location:'${location}',design:'starter',options:{kind:'legacy',space:'starter'},shifts:[1,1,1]},q=openingQuote6('cafe',data),budget=openingFunding6(q)`);assert.equal(r('JSON.stringify(state)'),before);assert(r('budget.safe'));near(r('budget.required'),r('q.cost+budget.holding+budget.recruitment+budget.coffee+budget.trial+budget.reserve'));assert.equal(r('budget.reserve'),r('3*q.running'));r(`var p=startOpening6('cafe',data);signCoffeeAgreement6('local','${location}','blend-1',{enabled:true,target:25,budget:20000,reserve:1});`);let minimum=r('state.cash');for(let i=0;i<12;i++){r('nextWeek()');assert(!r('state.over'),'Bankrupt '+location+' T'+r('state.week'));minimum=Math.min(minimum,r('state.cash'));r('validateSave(JSON.parse(JSON.stringify(state)))');}assert.equal(r('p.status'),'completed');assert.equal(r('state.stores[0].seats'),16);assert(r('state.totalCups>0&&state.cash>80000&&state.debt===0&&state.founderShare===100'));assert.equal(r('state.roasters.length+state.offices.length+state.warehouses.length'),0);console.log('PASS: '+location+' opens a paid starter cafe from 500k and survives twelve ordinary weeks; minimum cash '+Math.round(minimum)+', no extra funding or price/staff intervention.');passed++;}
// An expensive legacy address really is underfunded, not merely unaffordable at checkout.
{const r=game();r('var q=openingQuote6("cafe",{location:"karlin"}),b=openingFunding6(q)');assert(r('state.cash>q.cost&&!b.safe&&b.shortfall>0'));const before=r('JSON.stringify(state)');assert.throws(()=>r('openingFunding6(q,"unknown")'));assert.equal(r('JSON.stringify(state)'),before);passed++;console.log('PASS: funding covers later wages, recruitment, paid deliveries, trial and reserve; rejects an unknown supplier without mutation.');}
// Reproduce the old bankrupt founder and recover by returning capital, not inventing cash.
{const r=game();r('var p=openStore("karlin");signCoffeeAgreement6("specialty","karlin","blend-1",{enabled:true,target:25,budget:20000,reserve:1});for(let i=0;i<6&&!state.over;i++)nextWeek()');assert(r('state.over&&p.phase===2&&!p.entity'));const before=r('JSON.stringify(state)');r('var oldCapital=p.paidCapital,oldValue=companyValue(),oldCash=state.cash,oldRecruitment=p.recruitment,q=openingStarterRecoveryQuote6(p.id)');assert.equal(r('JSON.stringify(state)'),before);near(r('q.refund+q.writeoff'),r('oldCapital-q.blueprint.cost'));r('var stale={...q,cash:q.cash+1}');assert.throws(()=>r('recoverOpeningStarter6(p.id,stale)'));assert.equal(r('JSON.stringify(state)'),before);r('recoverOpeningStarter6(p.id,q)');near(r('state.cash-oldCash'),r('q.refund'));near(r('oldCapital+oldCash-p.paidCapital-state.cash'),r('q.writeoff'));assert(r('!state.over&&p.hired'));assert.equal(r('p.recruitment'),r('oldRecruitment'));assert.equal(r('p.people.length'),2);r('state=validateSave(JSON.parse(JSON.stringify(state)));p=state.opening6.projects[0]');assert.throws(()=>r('openingStarterRecoveryQuote6(p.id)'));for(let i=0;i<7;i++){r('nextWeek()');assert(!r('state.over'));r('validateSave(JSON.parse(JSON.stringify(state)))');}assert.equal(r('p.status'),'completed');assert.equal(r('p.recruitment'),r('oldRecruitment'));assert.equal(r('state.stores[0].seats'),16);assert.equal(r('state.debt'),0);assert(r('state.history.reduce((n,h)=>n+h.spoil,0)>=q.writeoff'));console.log('PASS: old bankrupt Karlín can return uninstalled capital at an actual loss, preserve hired people and phases, import and open without double hiring, debt or free money.');passed++;}
// Paid manager is released into the market; past salary and recruitment are not refunded.
{const r=game();r('var p=startOpening6("cafe",{location:"karlin",managerPid:state.talents[0].pid}),pid=p.manager.pid,cash=state.cash,q=openingStarterRecoveryQuote6(p.id);recoverOpeningStarter6(p.id,q)');assert.equal(r('p.manager'),null);assert(r('state.talents.some(p=>p.pid===pid)'));near(r('state.cash-cash'),r('q.refund'));r('validateSave(JSON.parse(JSON.stringify(state)))');console.log('PASS: founder takes over future preparation; a released manager and sunk fees remain accounted for.');passed++;}
console.log('PASS:',passed,'startup funding and recovery cases');
