const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');const c=vm.createContext({Intl});for(const f of ['engine','tycoon','empire','operations','reports','supply'])vm.runInContext(fs.readFileSync('dist/'+f+'.js','utf8'),c);const run=s=>vm.runInContext(s,c);let passed=0;function test(name,fn){run('state=fresh()');fn();run('validateSave(JSON.parse(JSON.stringify(state)))');passed++;console.log('PASS:',name)}
const config=(changes='')=>run('setProductionPlan5("roaster-1",{buffer:1.35,limit:500000,reserve:1.2,allowExpress:true'+changes+'})');
test('forecasts are deterministic and pure, and baseline matches actual weeks including stocks and cash',()=>{const before=run('JSON.stringify(state)'),f=run('supplyForecast5(8)');assert.equal(run('JSON.stringify(state)'),before);assert.equal(JSON.stringify(f),JSON.stringify(run('supplyForecast5(8)')));for(const point of f.series){run('nextWeek()');assert.equal(JSON.stringify(run('state.supply5.last')),JSON.stringify(point));}assert.equal(run('state.cash'),f.finalCash);assert.equal(run('supplyTrace5'),null);});
test('green consumption and incoming shipments are measured at actual arrival and roasting time',()=>{run('orderBeans("brazil",25)');const f=run('supplyForecast5(4)');assert.equal(f.series[0].arrivals.brazil,0);assert.equal(f.series[1].arrivals.brazil,25);assert(f.series.every(s=>Object.values(s.greenUsed).every(n=>n>=0)));run('nextWeek()');assert.equal(run('state.supply5.last.arrivals.brazil'),0);run('nextWeek()');assert.equal(run('state.supply5.last.arrivals.brazil'),25);});
test('planned local deliveries expose a city shortage even when global inventory is ample',()=>{run('state.cash=10000000;openStore("letna");state.reputation=65;openStore(LOCATIONS.find(l=>l.city==="Brno"&&!occupant(l.id)).id);state.deliveryPolicy="planned"');const f=run('supplyForecast5(4)');assert.equal(f.firstLoss,1);assert(f.alerts.some(a=>a.kind==='stock'&&a.target==='Brno'));assert(f.series[0].cities.find(c=>c.city==='Brno').lost>0);assert(f.series[0].cities.find(c=>c.city==='Praha').stock>0);});
test('buffer changes actual roasting while zero budget and disabled automation prevent automatic batches',()=>{run('state.batches=[]');config(',buffer:.5');const small=run('nextWeek();state.roasters[0].last.output');run('state=fresh();state.batches=[]');config(',buffer:2');assert(run('nextWeek();state.roasters[0].last.output')>small);run('state=fresh();state.batches=[]');config(',limit:0');run('nextWeek()');assert.equal(run('state.roasters[0].last.output'),0);assert(run('state.supply5.last.roasters[0].holds.includes("limit")'));run('state=fresh();state.roasters[0].auto=false');config();run('nextWeek()');assert.equal(run('state.roasters[0].last.output'),0);});
test('express prohibition prevents emergency buying and reveals the resulting stock failure',()=>{run('state.green=[];state.batches=[]');config(',allowExpress:false');run('nextWeek()');assert.equal(run('state.supply5.last.express.brazil.kg'),0);assert.equal(run('state.roasters[0].last.output'),0);assert(run('state.stores[0].last.stockLost')>0);assert(run('state.supply5.last.roasters[0].holds.includes("expres")'));});
test('variable spending respects the shared weekly budget across multiple recipes',()=>{run('createBlend({name:"Druhá",primary:"brazil",secondary:"colombia",share:75,roast:3,packaging:"classic",price:490});openStore("letna");state.stores[1].blend=state.blends[1].id;state.batches=[]');config(',limit:3000');run('nextWeek()');assert(run('state.roasters[0].last.used*55')<=3000);assert(run('state.roasters[0].last.decisions.some(d=>d.includes("limit"))'));});
test('production plans retain cash reserves and resetting restores original production rules',()=>{run('state.batches=[]');config(',reserve:8');run('state.cash=weeklyFixed()*8+100;nextWeek()');assert.equal(run('state.roasters[0].last.output'),0);assert(run('state.supply5.last.roasters[0].holds.includes("rezerva")'));run('state.cash=1600000;resetProductionPlan5("roaster-1");nextWeek()');assert(run('state.roasters[0].last.output')>0);assert.equal(run('state.supply5.plans.length'),0);});
test('bulk orders are atomic, charge exact prices once, preserve reserve and reject stale quotes',()=>{const before=run('JSON.stringify(state)');assert.throws(()=>run('placeSupplyOrders5([{origin:"brazil",kg:25},{origin:"constructor",kg:10}])'));assert.equal(run('JSON.stringify(state)'),before);const cash=run('state.cash'),quote=run('supplyOrderQuote5([{origin:"brazil",kg:25},{origin:"colombia",kg:10}])');run('var quote=supplyOrderQuote5([{origin:"brazil",kg:25},{origin:"colombia",kg:10}]);placeSupplyOrders5([{origin:"brazil",kg:25},{origin:"colombia",kg:10}],2,quote)');assert.equal(run('state.cash'),cash-quote.total);assert.equal(run('state.shipments.length'),2);const saved=run('JSON.stringify(state)');assert.throws(()=>run('placeSupplyOrders5([{origin:"brazil",kg:25},{origin:"colombia",kg:10}],2,{...quote,week:0})'));assert.equal(run('JSON.stringify(state)'),saved);run('state.cash=weeklyFixed()*2+1');const low=run('JSON.stringify(state)');assert.throws(()=>run('placeSupplyOrders5([{origin:"brazil",kg:25},{origin:"colombia",kg:10}])'));assert.equal(run('JSON.stringify(state)'),low);});
test('purchase previews include lead time, preserve the real company and match applied orders',()=>{run('state.cash=10000000;state.green=[];state.batches=[]');config(',allowExpress:false');const before=run('JSON.stringify(state)'),baseline=run('supplyForecast5(4)'),alternative=run('supplyForecast5(4,1,[{origin:"brazil",kg:100},{origin:"colombia",kg:50}])');assert.equal(run('JSON.stringify(state)'),before);assert.equal(alternative.series[0].cities[0].lost,baseline.series[0].cities[0].lost);assert(alternative.lost<baseline.lost);run('placeSupplyOrders5([{origin:"brazil",kg:100},{origin:"colombia",kg:50}]);for(let i=0;i<4;i++)nextWeek()');assert.equal(run('state.cash'),alternative.finalCash);});
test('forecasts include harvest transit, stale-stock writeoffs and demand variants',()=>{run('state.cash=10000000;buyEstate("cerrado");state.estates[0].cycle=11;state.batches[0].roastedWeek=-7');const before=run('JSON.stringify(state)'),f=run('supplyForecast5(4)');assert(f.series[0].spoil>0);assert(f.series[2].arrivals.brazil>0);assert(f.alerts.some(a=>a.kind==='spoil'));const low=run('supplyForecast5(4,.85)'),high=run('supplyForecast5(4,1.15)');assert(high.series[0].cities[0].need>low.series[0].cities[0].need);assert.equal(run('JSON.stringify(state)'),before);});
test('old saves get default rules and malformed nested plans reject without changing the company',()=>{run('nextWeek();var old=JSON.parse(JSON.stringify(state));delete old.supply5');assert.equal(run('validateSave(old).supply5.plans.length'),0);const before=run('JSON.stringify(state)');for(const edit of ['bad.supply5.plans=[{roaster:"roaster-1",buffer:-1,limit:5,reserve:1,allowExpress:true}]','bad.supply5.last.express.brazil.cost="bad"','bad.supply5.last.cities[0].city="Unknown"']){run('var bad=JSON.parse(JSON.stringify(state));'+edit);assert.throws(()=>run('validateSave(bad)'));assert.equal(run('JSON.stringify(state)'),before);}});
console.log(`All ${passed} supply planning scenarios passed.`);
