const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict'),c=vm.createContext({Intl,console});for(const f of [...fs.readFileSync('dist/index.html','utf8').matchAll(/<script src="([^"]+)"/g)].map(x=>x[1]).filter(x=>x!=='app.js'&&!x.endsWith('-ui.js')&&x!=='game-renderer.js'))vm.runInContext(fs.readFileSync('dist/'+f,'utf8'),c,{filename:f});const r=s=>vm.runInContext(s,c),snap=()=>r('JSON.stringify(state)');
r('state=fresh();openStore("letna");signCoffeeAgreement6("local","letna","blend-1",{enabled:true,target:25,budget:20000,reserve:1});for(let i=0;i<6;i++)nextWeek();state.cash=20000000;buyBakery5("atelier","Praha");buyOffice("studio");buyEstate("cerrado");buyRoaster("artisan","Malá pražírna","Praha");for(let i=0;i<6;i++)nextWeek();');
const initial=snap();for(const kind of ['bakery','hq','estate','roaster']){r('worldAssetSnapshot12('+JSON.stringify(kind)+',worldAsset12('+JSON.stringify(kind)+','+JSON.stringify(r('({bakery:state.bakery5.bakeries,hq:state.offices,estate:state.estates,roaster:state.roasters})['+JSON.stringify(kind)+'][0].id'))+').id)');assert.equal(snap(),initial,'Projection must never mutate production or inventory');}
r('var b12=state.bakery5.bakeries[0];var link12=worldBakeryLinkQuote12("letna",b12.id)');assert.equal(snap(),initial);const cash=r('state.cash'),value=r('companyValue()');r('worldLinkBakery12("letna",b12.id,link12)');assert.equal(r('state.cash'),cash-68000);assert.equal(r('companyValue()'),value,'Paid extension is capital, not free cash or duplicated bakery assets');assert.equal(r('worldCafeSnapshot6("letna",0,0,true).bakery.id'),r('b12.id'));assert.equal(r('worldSnapshot6("Praha").stores[0].bakery'),r('b12.id'));const linked=snap();assert.throws(()=>r('worldLinkBakery12("letna",b12.id,link12)'));assert.equal(snap(),linked);r('validateSave(JSON.parse(JSON.stringify(state)))');
r('var styled12=storeDesign5(state.stores[0]);styled12.appearance={style:"garden",terrace:true};var sq12=worldDesignQuote6("letna",styled12)');assert.equal(r('sq12.cost'),25000+18000+45000);const prior=r('state.cash');r('worldApplyDesign6("letna",styled12,sq12);var custom12=saveDesign5("Zahrada s pekárnou",styled12)');assert.equal(r('state.cash'),prior-88000);r('validateSave(JSON.parse(JSON.stringify(state)))');assert.equal(r('worldCafeSnapshot6("letna",0,0,true).appearance.style'),'garden');
for(const code of ['var bad12=JSON.parse(JSON.stringify(state));bad12.stores[0].appearance.style="missing";validateSave(bad12)','var bad12=JSON.parse(JSON.stringify(state));bad12.bakery5.bakeries[0].extensionCost12=1;validateSave(bad12)','var bad12=JSON.parse(JSON.stringify(state));bad12.bakery5.bakeries[0].city="Brno";validateSave(bad12)','var bad12=JSON.parse(JSON.stringify(state));delete bad12.bakery5.bakeries[0].cafe12;validateSave(bad12)'])assert.throws(()=>r(code));
for(const style of ['nordic','industrial','garden','classic','coastal','night'])for(const suffix of ['','-terrace']){r('designInfo5(cafePreset12('+JSON.stringify('look-'+style+suffix)+'))');}const stable=snap();r('var q12=openingQuote6("cafe",{location:"dejvice",design:"look-coastal-terrace",options:{space:"starter",kind:"legacy"}})');assert.equal(snap(),stable);assert.equal(r('q12.blueprint.design.appearance.style'),'coastal');assert.equal(r('q12.blueprint.design.appearance.terrace'),true);r('state.bakery5.bakeries[0].condition=70');const fee=r('state.bakery5.bakeries[0].cost*.04'),beforeService=r('state.cash');r('serviceBakery5(b12.id)');assert.equal(r('state.cash'),beforeService-fee);assert.equal(r('b12.condition'),100);
if(process.env.WORLD_FIXTURE12){r('setDepartment("hr",1);setDepartment("it",1);state.reputation=90;state.worldDemo12="Testovací firma s předem financovanými investicemi"');fs.writeFileSync('../world-assets-fixture.json',snap());}
console.log('PASS: pure asset projections; paid attached bakery visible in world and interior; exact capital accounting, duplicate rejection and import; paid distinct cafe themes/terrace and saved template; invalid appearance/link rejection; pure first-cafe themed quote and actual bakery service. Fixture campaign is explicitly prefinanced.');
