import * as T from 'three';
import {mergeGeometries} from 'three/addons/utils/BufferGeometryUtils.js';
import {workerRoute,guestRoute,seatPositions} from './game-navigation.mjs';
export {T};
const COLORS={grass:0x83aa79,soil:0xb4bea5,road:0x697581,paving:0xd8dfdc,wall:0xeeeae0,roof:0x293642,glass:0x577786,wood:0x98684d,metal:0x34414c,blue:0x346bda};
function material(color,opts={}){return new T.MeshStandardMaterial({color,roughness:.72,...opts});}
function addBox(group,x,y,z,w,h,d,mat){const m=new T.Mesh(new T.BoxGeometry(w,h,d),mat);m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;group.add(m);return m;}
function addCylinder(group,x,y,z,r,h,mat,r2=r,segments=10){const m=new T.Mesh(new T.CylinderGeometry(r2,r,h,segments),mat);m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;group.add(m);return m;}
function addSphere(group,x,y,z,r,mat){const m=new T.Mesh(new T.IcosahedronGeometry(r,1),mat);m.position.set(x,y,z);m.castShadow=true;group.add(m);return m;}
function palette(){return {grass:material(COLORS.grass),road:material(COLORS.road),paving:material(COLORS.paving),wall:material(COLORS.wall),roof:material(COLORS.roof),glass:material(COLORS.glass,{metalness:.35,roughness:.24,emissive:0xffbf76,emissiveIntensity:0}),wood:material(COLORS.wood),metal:material(COLORS.metal),blue:material(COLORS.blue),line:material(0xe6eae5),leaf:material(0x4e815c),bark:material(0x6d5b4d),white:material(0xf1f3ed)};}
// Preserve per-building selection while batching immutable pieces by material.
function compactMeshes(group){
 group.updateMatrixWorld(true);const inverse=group.matrixWorld.clone().invert(),buckets=new Map();
 group.traverse(o=>{if(!o.isMesh||Array.isArray(o.material))return;for(let p=o.parent;p&&p!==group;p=p.parent)if(p.userData.kind)return;const mat=o.material;if(!buckets.has(mat))buckets.set(mat,[]);buckets.get(mat).push(o);});
 for(const [mat,meshes] of buckets){if(meshes.length<2)continue;const copies=meshes.map(o=>o.geometry.clone().applyMatrix4(inverse.clone().multiply(o.matrixWorld))),geometry=mergeGeometries(copies);copies.forEach(g=>g.dispose());if(!geometry)continue;for(const o of meshes){o.parent.remove(o);o.geometry.dispose();}const mesh=new T.Mesh(geometry,mat);mesh.castShadow=true;mesh.receiveShadow=true;group.add(mesh);}
}
function streetLamp(g,x,z,p,w){addCylinder(g,x,1.5,z,.045,3,p.metal);addBox(g,x,3,z,.55,.12,.35,p.white);const light=new T.PointLight(0xffca88,0,7,2);light.position.set(x,2.85,z);g.add(light);w.lights.push(light);}
export function lotPosition(index){return {x:(index%3-1)*13,z:(Math.floor(index/3)-1)*13};}
export function addressStatus(snapshot,id){const store=snapshot.stores.find(s=>s.id===id),project=snapshot.opening.find(p=>p.location===id&&p.status==='active'),rival=snapshot.rivals.find(r=>r.locations.includes(id));return store?{kind:'owned',store}:project?{kind:'opening',project}:rival?{kind:'rival',rival}:{kind:'free'};}
function cafeBuilding(status,index,p){const g=new T.Group(),floors=index%3===0?2:1,w=6.8,d=5.6,h=2.6*floors,tint=status.kind==='owned'?status.store.color:status.kind==='rival'?'#b36350':status.kind==='opening'?'#d3a23a':'#8e999e',accent=material(tint);addBox(g,0,.12,0,w+1,.24,d+1,p.paving);addBox(g,0,h/2+.25,0,w,h,d,p.wall);for(let floor=0;floor<floors;floor++){for(const x of [-2.5,-.8,.9,2.6]){addBox(g,x,1.3+floor*2.6,d/2+.03,1.3,1.7,.08,p.glass);addBox(g,x,1.3+floor*2.6,d/2+.10,.055,1.7,.07,p.metal);}for(const z of [-1.7,0,1.7])addBox(g,w/2+.03,1.3+floor*2.6,z,.08,1.7,1.1,p.glass);addBox(g,0,.35+floor*2.6,d/2+.13,w+.06,.13,.14,p.metal);}
 addBox(g,0,h+.35,0,w+.35,.35,d+.35,p.roof);addBox(g,-1.6,h+.68,-.8,1.2,.38,.9,p.metal);addBox(g,2,h+.56,-1,1.4,.13,1.2,p.glass);addBox(g,0,2.35,d/2+.38,w,.18,.7,accent);for(const x of [-2.5,2.5])addBox(g,x,1.15,d/2+1.65,.09,2.3,.09,p.metal);addBox(g,0,2.34,d/2+1.05,w,.14,2,accent);addBox(g,-.7,1.0,d/2+.16,.8,1.9,.1,p.metal);addBox(g,-.7,1.0,d/2+.23,.68,1.7,.04,p.glass);
 for(const x of [-2.2,1.8]){addCylinder(g,x,.75,d/2+2.1,.42,.13,p.wood);addCylinder(g,x,.37,d/2+2.1,.065,.66,p.metal);for(const dx of [-.55,.55]){addBox(g,x+dx,.43,d/2+2.1,.32,.12,.34,p.wood);addBox(g,x+dx,.2,d/2+2.1,.07,.4,.07,p.metal);}}
 if(status.kind==='opening'){for(const x of [-3,3])for(const z of [-3,3])addBox(g,x,h/2+.5,z,.09,h+1,.09,p.metal);for(const level of [1,2.6,4])if(level<h+1)addBox(g,0,level,3.04,6,.10,.10,accent);addBox(g,0,.8,4.6,5.6,.5,.16,accent);}
 return g;}
function factory(kind,p){const g=new T.Group();addBox(g,0,.2,0,9,.4,7,p.paving);addBox(g,0,1.9,0,8,3.4,6,p.wall);addBox(g,0,3.7,0,8.3,.25,6.3,p.roof);for(const x of [-2.6,-.7,1.2])addBox(g,x,2.6,3.04,1.45,.7,.1,p.glass);addBox(g,2.8,1.25,3.1,1.45,2.1,.12,p.metal);for(const z of [-1.5,1])addCylinder(g,-3.5,4.5,z,.32,1.7,p.metal);if(kind==='roaster')for(const x of [-2,0,2])addCylinder(g,x,1.1,-3.2,.65,2.1,p.metal);else if(kind==='hq'){addBox(g,0,4.6,0,6,1.9,4.5,p.wall);for(const x of [-2,-.5,1,2.5])addBox(g,x,4.7,2.3,.8,1.1,.1,p.glass);addBox(g,0,5.7,0,6.2,.18,4.7,p.roof);}return g;}
function tree(g,x,z,p,scale=1){addCylinder(g,x,.7*scale,z,.11*scale,1.4*scale,p.bark);for(const [dx,dy,dz,r] of [[0,2,0,.65],[.25,1.65,.15,.55],[-.25,1.75,-.2,.5]])addSphere(g,x+dx*scale,dy*scale,z+dz*scale,r*scale,p.leaf);}
function bench(g,x,z,p,angle=0){const b=new T.Group();b.position.set(x,0,z);b.rotation.y=angle;addBox(b,0,.47,0,1.5,.13,.4,p.wood);addBox(b,0,.82,-.22,1.5,.55,.1,p.wood);for(const dx of [-.55,.55])addBox(b,dx,.23,0,.10,.46,.35,p.metal);g.add(b);}
function car(p,color=0xb1c0c8,van=false){const g=new T.Group();addBox(g,0,.35,0,van?.9:.8,.50,van?1.8:1.5,material(color));addBox(g,0,.71,-.16,van?.87:.67,van?.60:.33,van?1.1:.8,material(color));addBox(g,0,.73,.38,van?.76:.61,.24,.08,p.glass);for(const x of [-.42,.42])for(const z of [-.5,.5]){const wheel=addCylinder(g,x,.2,z,.18,.13,p.metal,.18,10);wheel.rotation.z=Math.PI/2;}addBox(g,0,.4,.78,.6,.07,.025,p.white);return g;}
function sceneBase(){const scene=new T.Scene();scene.background=new T.Color(0xc5d4d7);scene.fog=new T.Fog(0xc5d4d7,75,160);const group=new T.Group();scene.add(group);const p=palette(),hemi=new T.HemisphereLight(0xd9e8ff,0x717c54,2),sun=new T.DirectionalLight(0xfff4df,3.1);sun.position.set(-22,38,18);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);sun.shadow.camera.left=-38;sun.shadow.camera.right=38;sun.shadow.camera.top=38;sun.shadow.camera.bottom=-38;sun.shadow.normalBias=.08;scene.add(hemi,sun);return {scene,group,p,hemi,sun,objects:[],actors:[],lights:[],size:52,mode:'city'};}
export function buildCityScene(snapshot){const w=sceneBase(),{group:g,p}=w;const extraCount=snapshot.roasters.length+snapshot.bakeries.length+snapshot.offices.length+snapshot.warehouses.length,depth=Math.max(64,64+Math.floor(Math.max(0,extraCount-1)/4)*10);addBox(g,0,-.35,(depth-64)/2,58,.7,depth,p.grass);addBox(g,0,-.66,(depth-64)/2,58,.16,depth,material(COLORS.soil));for(const z of [-20,6.5,20]){addBox(g,0,.014,z,57,.06,3.4,p.road);for(let x=-27;x<27;x+=3)addBox(g,x,.055,z,1.4,.025,.085,p.line);addBox(g,0,.018,z+2,57,.07,.55,p.paving);addBox(g,0,.018,z-2,57,.07,.55,p.paving);}for(const x of [-20,-6.5,6.5,20]){addBox(g,x,.025,0,3.3,.07,62,p.road);for(let z=-29;z<29;z+=3)addBox(g,x,.08,z,.085,.025,1.4,p.line);addBox(g,x+1.95,.045,0,.5,.06,62,p.paving);addBox(g,x-1.95,.045,0,.5,.06,62,p.paving);}
 snapshot.locations.forEach((l,i)=>{const pos=lotPosition(i),status=addressStatus(snapshot,l.id),building=cafeBuilding(status,i,p);building.position.set(pos.x,0,pos.z);building.userData={kind:'address',id:l.id,title:l.name,status:status.kind,anchor:new T.Vector3(pos.x,5.4,pos.z)};compactMeshes(building);g.add(building);w.objects.push(building);for(const dx of [-4.6,4.6])tree(g,pos.x+dx,pos.z-2.3,p,.8);bench(g,pos.x+3.8,pos.z+2.5,p,Math.PI/2);});
 for(let i=0;i<10;i++)tree(g,-26+i*5.7,-27,p,1.1);for(let i=0;i<5;i++)tree(g,26,-12+i*6,p,.9);
 const extras=[...snapshot.roasters.map(r=>({kind:'roaster',id:r.id,title:r.name})),...snapshot.bakeries.map(b=>({kind:'bakery',id:b.id,title:b.name})),...snapshot.offices.map(o=>({kind:'hq',id:o.id,title:o.name})),...snapshot.warehouses.map(o=>({kind:'warehouse',id:o.id,title:o.name}))];extras.forEach((o,i)=>{const x=-18+(i%4)*12,z=27+Math.floor(i/4)*10,building=factory(o.kind,p);building.position.set(x,0,z);building.userData={...o,status:'owned',anchor:new T.Vector3(x,5,z)};compactMeshes(building);g.add(building);w.objects.push(building);});w.size=depth;w.centerZ=(depth-64)/2;
 for(const x of [-16,0,16])for(const z of [-22.3,22.3])streetLamp(g,x,z,p,w);compactMeshes(g);
 for(let i=0;i<5;i++){const mesh=car(p,[0xe2e6df,0x4a5866,0x98a8af,0xcab89d,0x314f67][i]);g.add(mesh);w.actors.push({mesh,kind:'traffic',phase:i/5,speed:.024+i*.003});}
 for(const [i,v] of snapshot.vehicles.entries()){const mesh=car(p,v.cold?0xe6f1f4:0xc9e2bd,true);g.add(mesh);const active=v.driver&&v.routeEnabled&&v.lastUnits>0;mesh.userData={kind:'vehicle',id:v.id,title:v.name,status:active?'route':'parked',anchor:new T.Vector3(0,2,0)};w.objects.push(mesh);w.actors.push({mesh,kind:'delivery',phase:i*.12,speed:.02,active,vehicle:v.id,parking:{x:-25+i*1.8,z:26}});}
 const ring=new T.Mesh(new T.RingGeometry(4.6,4.77,64),new T.MeshBasicMaterial({color:COLORS.blue,transparent:true,opacity:.8,side:T.DoubleSide}));ring.rotation.x=-Math.PI/2;ring.position.y=.16;ring.visible=false;g.add(ring);w.selection=ring;return w;}
export function floorPoint(x,y){return {x:(x-3.5)*1.15,z:(y-2.5)*1.15};}
function chair(g,x,z,p,angle=0){const b=new T.Group();b.position.set(x,0,z);b.rotation.y=angle;addBox(b,0,.43,0,.33,.10,.33,p.wood);addBox(b,0,.67,-.16,.33,.4,.08,p.wood);for(const dx of [-.12,.12])for(const dz of [-.12,.12])addBox(b,dx,.2,dz,.04,.4,.04,p.metal);g.add(b);}
function furniture(item,p){const g=new T.Group(),kind=item.kind,table=['table','table2','barseat'].includes(kind);if(table){const width=kind==='table'?1.8:kind==='table2'?.72:.52;addBox(g,kind==='table'?.52:0,.8,0,width,.14,.46,p.wood);for(const x of kind==='table'?[0,1.05]:[0])addCylinder(g,x,.39,0,.055,.72,p.metal);chair(g,0,.4,p);if(kind!=='barseat')chair(g,0,-.4,p,Math.PI);if(kind==='table'){chair(g,1.05,.4,p);chair(g,1.05,-.4,p,Math.PI);}}else if(kind==='counter'||kind==='pickup'){addBox(g,kind==='counter'?.57:0,.52,0,kind==='counter'?2.1:.86,1.04,.8,p.wood);addBox(g,kind==='counter'?.57:0,1.1,0,kind==='counter'?2.2:.94,.13,.91,p.wall);if(kind==='counter')addBox(g,.8,1.25,0,.35,.28,.24,p.metal);}else if(kind==='espresso'){addBox(g,0,.48,0,.92,.96,.84,p.wood);addBox(g,0,1.23,0,.78,.47,.51,p.metal);addBox(g,0,1.12,.26,.64,.05,.1,p.glass);for(const x of [-.22,.22]){addCylinder(g,x,1.15,.31,.07,.13,p.white);addBox(g,x,1.3,.31,.025,.15,.03,p.metal);}}else if(kind==='grinder'){addBox(g,0,.45,0,.8,.9,.8,p.wood);addCylinder(g,0,1.08,0,.16,.36,p.metal);addCylinder(g,0,1.44,0,.20,.30,p.glass,.27);}else if(kind==='sink'){addBox(g,0,.48,0,.8,.96,.75,p.metal);addBox(g,0,.98,0,.55,.035,.45,p.glass);addCylinder(g,0,1.13,-.22,.025,.3,p.metal);}else if(kind==='storage'){addBox(g,0,.85,0,.9,1.7,.8,p.wood);for(const y of [.3,.8,1.3])for(const x of [-.23,.23])addBox(g,x,y,.28,.33,.32,.37,p.wall);}else if(kind==='window'){addBox(g,0,1.1,0,.95,.14,.95,p.wood);addBox(g,0,1.75,-.3,.9,1.15,.09,p.glass);}g.userData={kind:'furniture',id:item.id,title:kind,anchor:new T.Vector3()};return g;}
function person(p,index,staff=false){const g=new T.Group(),shirt=staff?p.wood:(p.shirts??=[0x698aaa,0xa6635b,0x6f8768,0xa48c6b,0x78779a].map(c=>material(c)))[index%5];addCylinder(g,0,.63,0,.17,.47,shirt,.21);addSphere(g,0,1.02,0,.13,(p.skins??=[0xe0b99a,0xad8062,0xd09f7c].map(c=>material(c)))[index%3]);for(const x of [-.08,.08])addBox(g,x,.25,0,.09,.45,.10,p.metal);if(staff)addBox(g,0,.66,.18,.22,.38,.035,p.wall);return g;}
export function buildCafeScene(snapshot,floor){const w=sceneBase(),{group:g,p}=w;w.mode='cafe';w.size=15;addBox(g,0,-.16,0,10,.3,8,p.wood);for(let x=0;x<8;x++)for(let y=0;y<6;y++){const pos=floorPoint(x,y),tile=addBox(g,pos.x,.025,pos.z,1.14,.03,1.14,material((x+y)%2?0xe1ded2:0xe9e5db));tile.userData={kind:'floor',id:x+','+y,x,y};w.objects.push(tile);}addBox(g,0,1.35,-3.6,9.8,2.7,.17,p.wall);addBox(g,-4.8,1.35,0,.17,2.7,7.2,p.wall);for(const x of [-3,-1,1,3]){addBox(g,x,1.5,-3.48,1.5,1.65,.06,p.glass);addBox(g,x,2.4,-3.4,1.7,.1,.2,p.metal);}for(const z of [-2,0,2]){addCylinder(g,-4.1,.5,z,.26,1,p.wall);tree(g,-4.1,z,p,.45);}
 for(const item of floor.items){const pos=floorPoint(item.x,item.y),mesh=furniture(item,p);mesh.position.set(pos.x,.06,pos.z);mesh.userData.anchor.set(pos.x,1.8,pos.z);g.add(mesh);w.objects.push(mesh);}w.floor=floor;w.actorPool=[];setCafeActors(w,snapshot);const selection=new T.Mesh(new T.BoxGeometry(1.18,.035,1.18),new T.MeshBasicMaterial({color:COLORS.blue,transparent:true,opacity:.42}));selection.position.y=.085;selection.visible=false;g.add(selection);w.selection=selection;return w;}
export function setWorldNight(w,night){w.scene.background.set(night?0x131e32:0xc5d4d7);w.scene.fog.color.copy(w.scene.background);w.hemi.intensity=night?.46:2;w.sun.intensity=night?.55:3.1;w.sun.color.set(night?0xa8c5ff:0xfff4df);w.p.glass.emissiveIntensity=night?1.1:0;for(const light of w.lights)light.intensity=night?8:0;}
export function animateWorld(w,time){for(const a of w.actors){const t=(time*a.speed+(a.phase||0))%1;if(a.kind==='traffic'||a.kind==='delivery'&&a.active){const side=Math.floor(t*4),f=(t*4)%1,v=19.25;let x,z,rot;if(side===0){x=-v+f*v*2;z=-v;rot=Math.PI/2;}else if(side===1){x=v;z=-v+f*v*2;rot=0;}else if(side===2){x=v-f*v*2;z=v;rot=-Math.PI/2;}else{x=-v;z=v-f*v*2;rot=Math.PI;}a.mesh.position.set(x,.1,z);a.mesh.rotation.y=rot;}else if(a.kind==='delivery'){a.mesh.position.set(a.parking.x,.1,a.parking.z);}else if(a.seat){const pos=floorPoint(a.seat.x,a.seat.y);a.mesh.position.set(pos.x,.0,pos.z+a.seat.offset);a.mesh.rotation.y=a.seat.angle;}else if(a.path?.length){const step=(time*(a.kind==='worker'?.5:.35)+a.phase*10)%(a.path.length-1||1),i=Math.floor(step),f=step-i,from=floorPoint(a.path[i].x,a.path[i].y),next=a.path[Math.min(i+1,a.path.length-1)],to=floorPoint(next.x,next.y);a.mesh.position.set(from.x+(to.x-from.x)*f,0,from.z+(to.z-from.z)*f);if(to.x!==from.x||to.z!==from.z)a.mesh.rotation.y=Math.atan2(to.x-from.x,to.z-from.z);}}}
export function setCafeActors(w,snapshot){
 if(w.mode!=='cafe')return;const slot=snapshot.slot||{},workerCount=Math.min(7,slot.workers||0),seats=seatPositions(w.floor),seated=Math.min(12,slot.occupied||0,seats.length),guests=Math.min(18,(slot.queue||0)+seated+Math.min(5,slot.served||0));
 const needs=[...Array.from({length:workerCount},(_,i)=>({kind:'worker',index:i,person:snapshot.crew[i],path:workerRoute(w.floor,i)})),...Array.from({length:guests},(_,i)=>({kind:'guest',index:i,seat:i<seated?seats[i]:null,path:guestRoute(w.floor)}))];
 w.actors=[];w.objects=w.objects.filter(o=>o.userData.kind!=='worker');
 for(let i=0;i<Math.max(needs.length,w.actorPool.length);i++){
  const need=needs[i];if(!need){w.actorPool[i].mesh.visible=false;continue;}
  let actor=w.actorPool[i];if(!actor||actor.kind!==need.kind){if(actor){w.group.remove(actor.mesh);actor.mesh.traverse(o=>o.geometry?.dispose());}actor={mesh:person(w.p,need.index,need.kind==='worker')};w.group.add(actor.mesh);w.actorPool[i]=actor;}
  Object.assign(actor,need,{phase:need.index*.14});actor.mesh.visible=true;actor.mesh.userData=need.person?{kind:'worker',id:need.person.id,title:need.person.name}:{};if(need.person)w.objects.push(actor.mesh);w.actors.push(actor);
 }
}

export function sceneStats(w){let meshes=0,vertices=0;w.scene.traverse(o=>{if(o.isMesh){meshes++;vertices+=o.geometry.getAttribute('position')?.count||0;}});return {meshes,vertices,objects:w.objects.map(o=>({...o.userData,anchor:undefined})),mode:w.mode};}
export function disposeWorld(w){const geometries=new Set(),materials=new Set();w.scene.traverse(o=>{if(o.geometry)geometries.add(o.geometry);if(o.material)(Array.isArray(o.material)?o.material:[o.material]).forEach(m=>materials.add(m));});geometries.forEach(g=>g.dispose());materials.forEach(m=>m.dispose());w.scene.clear();}
