import * as T from 'three';
import {mergeGeometries} from 'three/addons/utils/BufferGeometryUtils.js';
import {cityProfile12,cityLotPosition12} from './game-cities.mjs';
import {cityWaterways,footprintOnWater,translatedFootprint,placeOnLand,streetSpans} from './game-geography.mjs';
import {workerRoute,guestRoute,seatPositions} from './game-navigation.mjs';
export {T};
const COLORS={grass:0xaab99e,soil:0xb4bea5,road:0x9a9f9d,paving:0xd8dfdc,wall:0xeeeae0,roof:0x667280,glass:0xa2b3b7,wood:0xbba686,metal:0x34414c,blue:0x535bbb};
function material(color,opts={}){return new T.MeshStandardMaterial({color,roughness:.72,...opts});}
function addBox(group,x,y,z,w,h,d,mat){const m=new T.Mesh(new T.BoxGeometry(w,h,d),mat);m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;group.add(m);return m;}
function addCylinder(group,x,y,z,r,h,mat,r2=r,segments=10){const m=new T.Mesh(new T.CylinderGeometry(r2,r,h,segments),mat);m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;group.add(m);return m;}
function addSphere(group,x,y,z,r,mat){const m=new T.Mesh(new T.IcosahedronGeometry(r,1),mat);m.position.set(x,y,z);m.castShadow=true;group.add(m);return m;}
function palette(){return {grass:material(COLORS.grass),road:material(COLORS.road),paving:material(COLORS.paving),wall:material(COLORS.wall),roof:material(COLORS.roof),glass:material(COLORS.glass,{metalness:.35,roughness:.24,emissive:0xffbf76,emissiveIntensity:0}),wood:material(COLORS.wood),metal:material(COLORS.metal),blue:material(COLORS.blue),line:material(0xe6eae5),leaf:material(0x4e815c),bark:material(0x6d5b4d),white:material(0xf1f3ed)};}
// Preserve per-building selection while batching immutable pieces by material.
function compactMeshes(group){
 group.updateMatrixWorld(true);const inverse=group.matrixWorld.clone().invert(),buckets=new Map();
 group.traverse(o=>{if(!o.isMesh||Array.isArray(o.material))return;for(let p=o.parent;p&&p!==group;p=p.parent)if(p.userData.kind)return;const mat=o.material;if(!buckets.has(mat))buckets.set(mat,new Map());const key=String(!!o.geometry.index)+":"+Object.keys(o.geometry.attributes).sort().join(",");let sets=buckets.get(mat);if(!sets.has(key))sets.set(key,[]);sets.get(key).push(o);});
 for(const [mat,sets] of buckets)for(const meshes of sets.values()){if(meshes.length<2)continue;const copies=meshes.map(o=>o.geometry.clone().applyMatrix4(inverse.clone().multiply(o.matrixWorld))),geometry=mergeGeometries(copies);copies.forEach(g=>g.dispose());if(!geometry)continue;for(const o of meshes){o.parent.remove(o);o.geometry.dispose();}const mesh=new T.Mesh(geometry,mat);mesh.castShadow=true;mesh.receiveShadow=true;group.add(mesh);}
}
function streetLamp(g,x,z,p,w){addCylinder(g,x,1.5,z,.045,3,p.metal);addBox(g,x,3,z,.55,.12,.35,p.white);const light=new T.PointLight(0xffca88,0,7,2);light.position.set(x,2.85,z);g.add(light);w.lights.push(light);}
export function lotPosition(index){return {x:(index%3-1)*13,z:(Math.floor(index/3)-1)*13};}
export function addressStatus(snapshot,id){const store=snapshot.stores.find(s=>s.id===id),project=snapshot.opening.find(p=>p.location===id&&p.status==='active'),rival=snapshot.rivals.find(r=>r.locations.includes(id));return store?{kind:'owned',store}:project?{kind:'opening',project}:rival?{kind:'rival',rival}:{kind:'free'};}
function cafeBuilding(status,index,p,profile){const g=new T.Group(),floors=profile?.architecture==='canal'?3:['skyline','glass'].includes(profile?.architecture)?3+index%3:profile?.architecture==='dense'?2+index%3:index%3===0?2:1,w=6.8,d=5.6,h=2.6*floors,tint=status.kind==='owned'?status.store.color:status.kind==='rival'?'#b36350':status.kind==='opening'?'#d3a23a':'#8e999e',accent=material(tint);addBox(g,0,.12,0,w+1,.24,d+1,p.paving);addBox(g,0,h/2+.25,0,w,h,d,p.wall);for(let floor=0;floor<floors;floor++){for(const x of [-2.5,-.8,.9,2.6]){addBox(g,x,1.3+floor*2.6,d/2+.03,1.3,1.7,.08,p.glass);addBox(g,x,1.3+floor*2.6,d/2+.10,.055,1.7,.07,p.metal);}for(const z of [-1.7,0,1.7])addBox(g,w/2+.03,1.3+floor*2.6,z,.08,1.7,1.1,p.glass);addBox(g,0,.35+floor*2.6,d/2+.13,w+.06,.13,.14,p.metal);}
 addBox(g,0,h+.35,0,w+.35,.35,d+.35,p.roof);if(profile&&['historic','colourful','canal','palace'].includes(profile.architecture)){for(const side of [-1,1]){const roof=addBox(g,side*1.8,h+.85,0,4.1,.14,d+.45,p.roof);roof.rotation.z=side*.28;}}addBox(g,-1.6,h+.68,-.8,1.2,.38,.9,p.metal);addBox(g,2,h+.56,-1,1.4,.13,1.2,p.glass);addBox(g,0,2.35,d/2+.38,w,.18,.7,accent);for(const x of [-2.5,2.5])addBox(g,x,1.15,d/2+1.65,.09,2.3,.09,p.metal);addBox(g,0,2.34,d/2+1.05,w,.14,2,accent);addBox(g,-.7,1.0,d/2+.16,.8,1.9,.1,p.metal);addBox(g,-.7,1.0,d/2+.23,.68,1.7,.04,p.glass);
 for(const x of [-2.2,1.8]){addCylinder(g,x,.75,d/2+2.1,.42,.13,p.wood);addCylinder(g,x,.37,d/2+2.1,.065,.66,p.metal);for(const dx of [-.55,.55]){addBox(g,x+dx,.43,d/2+2.1,.32,.12,.34,p.wood);addBox(g,x+dx,.2,d/2+2.1,.07,.4,.07,p.metal);}}
 if(status.store?.appearance?.terrace){addBox(g,0,.12,6.4,8,.24,3.5,p.wood);for(const x of [-2.5,0,2.5]){addCylinder(g,x,.75,6.4,.45,.12,p.wood);addCylinder(g,x,1.45,6.4,.035,2.7,p.metal);const umbrella=new T.Mesh(new T.ConeGeometry(1.1,.35,8),p.wall);umbrella.position.set(x,2.8,6.4);g.add(umbrella);}}if(status.store?.bakery){const b=factory('bakery',p);b.scale.set(.50,.75,.7);b.position.set(4.9,0,-.6);g.add(b);}if(status.kind==='opening'){for(const x of [-3,3])for(const z of [-3,3])addBox(g,x,h/2+.5,z,.09,h+1,.09,p.metal);for(const level of [1,2.6,4])if(level<h+1)addBox(g,0,level,3.04,6,.10,.10,accent);addBox(g,0,.8,4.6,5.6,.5,.16,accent);}
 if(profile?.architecture==='canal')g.scale.x=.68;if(profile?.architecture==='dense'){addBox(g,3.5,3.5,3.1,.65,3.3,.12,accent);addBox(g,3.55,3.5,3.2,.3,2.5,.06,p.white);}return g;}
function factory(kind,p){const g=new T.Group();addBox(g,0,.2,0,9,.4,7,p.paving);addBox(g,0,1.9,0,8,3.4,6,p.wall);addBox(g,0,3.7,0,8.3,.25,6.3,p.roof);for(const x of [-2.6,-.7,1.2])addBox(g,x,2.6,3.04,1.45,.7,.1,p.glass);addBox(g,2.8,1.25,3.1,1.45,2.1,.12,p.metal);for(const z of [-1.5,1])addCylinder(g,-3.5,4.5,z,.32,1.7,p.metal);if(kind==='roaster')for(const x of [-2,0,2])addCylinder(g,x,1.1,-3.2,.65,2.1,p.metal);else if(kind==='hq'){addBox(g,0,4.6,0,6,1.9,4.5,p.wall);for(const x of [-2,-.5,1,2.5])addBox(g,x,4.7,2.3,.8,1.1,.1,p.glass);addBox(g,0,5.7,0,6.2,.18,4.7,p.roof);}return g;}
function tree(g,x,z,p,scale=1){addCylinder(g,x,.7*scale,z,.11*scale,1.4*scale,p.bark);for(const [dx,dy,dz,r] of [[0,2,0,.65],[.25,1.65,.15,.55],[-.25,1.75,-.2,.5]])addSphere(g,x+dx*scale,dy*scale,z+dz*scale,r*scale,p.leaf);}
function bench(g,x,z,p,angle=0){const b=new T.Group();b.position.set(x,0,z);b.rotation.y=angle;addBox(b,0,.47,0,1.5,.13,.4,p.wood);addBox(b,0,.82,-.22,1.5,.55,.1,p.wood);for(const dx of [-.55,.55])addBox(b,dx,.23,0,.10,.46,.35,p.metal);g.add(b);}
function car(p,color=0xb1c0c8,van=false){const g=new T.Group();addBox(g,0,.35,0,van?.9:.8,.50,van?1.8:1.5,material(color));addBox(g,0,.71,-.16,van?.87:.67,van?.60:.33,van?1.1:.8,material(color));addBox(g,0,.73,.38,van?.76:.61,.24,.08,p.glass);for(const x of [-.42,.42])for(const z of [-.5,.5]){const wheel=addCylinder(g,x,.2,z,.18,.13,p.metal,.18,10);wheel.rotation.z=Math.PI/2;}addBox(g,0,.4,.78,.6,.07,.025,p.white);return g;}
function sceneBase(){const scene=new T.Scene();scene.background=new T.Color(0xbfcbd0);scene.fog=new T.Fog(0xbfcbd0,250,650);const group=new T.Group();scene.add(group);const p=palette(),hemi=new T.HemisphereLight(0xd9e8ff,0x717c54,2),sun=new T.DirectionalLight(0xfff4df,3.1);sun.position.set(-22,38,18);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);sun.shadow.camera.left=-80;sun.shadow.camera.right=80;sun.shadow.camera.top=80;sun.shadow.camera.bottom=-80;sun.shadow.normalBias=.08;scene.add(hemi,sun);return {scene,group,p,hemi,sun,objects:[],actors:[],lights:[],size:52,mode:'city'};}
export function buildCityScene(snapshot){const w=sceneBase(),{group:g,p}=w,profile=cityProfile12(snapshot.city);w.profile=profile;w.size=105;w.centerZ=0;w.waterways=cityWaterways(profile);w.landFootprints=[];w.streets=[];w.landLimits={minX:-51,maxX:51,minZ:-49,maxZ:Math.max(57,53+Math.floor((snapshot.roasters.length+snapshot.bakeries.length+snapshot.offices.length+snapshot.warehouses.length)/5)*11)};p.grass.color.setHex(profile.grass);p.wall.color.setHex(profile.wall);p.roof.color.setHex(profile.roof);cityLandscape12(w,profile);
 snapshot.locations.forEach((l,i)=>{let pos=cityLotPosition12(snapshot.city,l,i);const status=addressStatus(snapshot,l.id),local={...p};if(status.store?.appearance){const a=status.store.appearance,theme=CAFE_PALETTE12[a.style];if(theme){local.wall=material(theme.wall);local.wood=material(theme.wood);}}const building=status.store?.temporary8==='truck'?coffeeTruck8(local):cafeBuilding(status,i,local,profile);pos=placeBuildingOnLand(w,building,pos);building.position.set(pos.x,0,pos.z);building.userData={kind:'address',id:l.id,title:l.name,status:status.kind,anchor:new T.Vector3(pos.x,5.4,pos.z)};compactMeshes(building);g.add(building);w.objects.push(building);if(dryDecoration(w,pos.x-4.2,pos.z-2.3,.7))tree(g,pos.x-4.2,pos.z-2.3,p,.65);if(dryDecoration(w,pos.x+3.8,pos.z+2.5,.9))bench(g,pos.x+3.8,pos.z+2.5,p,Math.PI/2);});
 for(const [i,source] of (snapshot.sources8||[]).entries()){const anchor=w.objects.find(o=>o.userData.id===source.anchor);if(!anchor)continue;const model=citySourceBuilding8(source.kind,p),pos=placeBuildingOnLand(w,model,{x:anchor.position.x+(i%2?-7:7),z:anchor.position.z-7});model.position.set(pos.x,0,pos.z);model.userData={...source,kind:'source8',title:source.name,anchor:new T.Vector3(pos.x,4,pos.z)};g.add(model);w.objects.push(model);}
 const extras=[...snapshot.roasters.map(r=>({kind:'roaster',id:r.id,title:r.name})),...snapshot.bakeries.filter(b=>!b.cafe).map(b=>({kind:'bakery',id:b.id,title:b.name})),...snapshot.offices.map(o=>({kind:'hq',id:o.id,title:o.name})),...snapshot.warehouses.map(o=>({kind:'warehouse',id:o.id,title:o.name}))];extras.forEach((o,i)=>{const x=-36+(i%5)*17,z=47+Math.floor(i/5)*11,building=factory(o.kind,p);const pos=placeBuildingOnLand(w,building,{x,z});building.position.set(pos.x,0,pos.z);building.userData={...o,status:'owned',anchor:new T.Vector3(pos.x,5,pos.z)};compactMeshes(building);g.add(building);w.objects.push(building);});w.size=Math.max(105,105+Math.floor(extras.length/5)*13);w.centerZ=Math.max(0,Math.floor(extras.length/5)*5);
 for(const b of snapshot.bakeries.filter(b=>b.cafe)){const cafe=w.objects.find(o=>o.userData.id===b.cafe);if(!cafe)continue;const sign=addBox(g,cafe.position.x+4.9*cafe.scale.x,3.4,cafe.position.z-.6,2.2,.3,1,p.blue);sign.userData={kind:'bakery',id:b.id,title:b.name,status:'owned',anchor:sign.position.clone().add(new T.Vector3(0,1,0))};w.objects.push(sign);}
 for(const x of [-40,0,40])for(const z of [-38,38])if(dryDecoration(w,x,z,.5))streetLamp(g,x,z,p,w);compactMeshes(g);
 for(let i=0;i<5;i++){const mesh=car(p,[0xe2e6df,0x4a5866,0x98a8af,0xcab89d,0x314f67][i]);g.add(mesh);w.actors.push({mesh,kind:'traffic',phase:i/5,speed:.012+i*.002});}
 for(const [i,v] of snapshot.vehicles.entries()){const mesh=car(p,v.cold?0xe6f1f4:0xc9e2bd,true);g.add(mesh);const active=v.driver&&v.routeEnabled&&v.lastUnits>0;mesh.userData={kind:'vehicle',id:v.id,title:v.name,status:active?'route':'parked',anchor:new T.Vector3(0,2,0)};w.objects.push(mesh);w.actors.push({mesh,kind:'delivery',phase:i*.12,speed:.02,active,vehicle:v.id,parking:{x:-42+i*1.8,z:43}});}
 const ring=new T.Mesh(new T.RingGeometry(4.6,4.77,64),new T.MeshBasicMaterial({color:COLORS.blue,transparent:true,opacity:.8,side:T.DoubleSide}));ring.rotation.x=-Math.PI/2;ring.position.y=.16;ring.visible=false;g.add(ring);w.selection=ring;return w;}
export function floorPoint(x,y){return {x:(x-3.5)*1.15,z:(y-2.5)*1.15};}
function chair(g,x,z,p,angle=0){const b=new T.Group();b.position.set(x,0,z);b.rotation.y=angle;addBox(b,0,.43,0,.33,.10,.33,p.wood);addBox(b,0,.67,-.16,.33,.4,.08,p.wood);for(const dx of [-.12,.12])for(const dz of [-.12,.12])addBox(b,dx,.2,dz,.04,.4,.04,p.metal);g.add(b);}
function furniture(item,p){const g=new T.Group(),kind=item.kind,table=['table','table2','barseat'].includes(kind);if(table){const width=kind==='table'?1.8:kind==='table2'?.72:.52;addBox(g,kind==='table'?.52:0,.8,0,width,.14,.46,p.wood);for(const x of kind==='table'?[0,1.05]:[0])addCylinder(g,x,.39,0,.055,.72,p.metal);chair(g,0,.4,p);if(kind!=='barseat')chair(g,0,-.4,p,Math.PI);if(kind==='table'){chair(g,1.05,.4,p);chair(g,1.05,-.4,p,Math.PI);}}else if(kind==='counter'||kind==='pickup'){addBox(g,kind==='counter'?.57:0,.52,0,kind==='counter'?2.1:.86,1.04,.8,p.wood);addBox(g,kind==='counter'?.57:0,1.1,0,kind==='counter'?2.2:.94,.13,.91,p.wall);if(kind==='counter')addBox(g,.8,1.25,0,.35,.28,.24,p.metal);}else if(kind==='espresso'){addBox(g,0,.48,0,.92,.96,.84,p.wood);addBox(g,0,1.23,0,.78,.47,.51,p.metal);addBox(g,0,1.12,.26,.64,.05,.1,p.glass);for(const x of [-.22,.22]){addCylinder(g,x,1.15,.31,.07,.13,p.white);addBox(g,x,1.3,.31,.025,.15,.03,p.metal);}}else if(kind==='grinder'){addBox(g,0,.45,0,.8,.9,.8,p.wood);addCylinder(g,0,1.08,0,.16,.36,p.metal);addCylinder(g,0,1.44,0,.20,.30,p.glass,.27);}else if(kind==='sink'){addBox(g,0,.48,0,.8,.96,.75,p.metal);addBox(g,0,.98,0,.55,.035,.45,p.glass);addCylinder(g,0,1.13,-.22,.025,.3,p.metal);}else if(kind==='storage'){addBox(g,0,.85,0,.9,1.7,.8,p.wood);for(const y of [.3,.8,1.3])for(const x of [-.23,.23])addBox(g,x,y,.28,.33,.32,.37,p.wall);}else if(kind==='window'){addBox(g,0,1.1,0,.95,.14,.95,p.wood);addBox(g,0,1.75,-.3,.9,1.15,.09,p.glass);}g.userData={kind:'furniture',id:item.id,title:kind,anchor:new T.Vector3()};return g;}
function person(p,index,staff=false){const g=new T.Group(),shirt=staff?p.wood:(p.shirts??=[0x698aaa,0xa6635b,0x6f8768,0xa48c6b,0x78779a].map(c=>material(c)))[index%5];addCylinder(g,0,.63,0,.17,.47,shirt,.21);addSphere(g,0,1.02,0,.13,(p.skins??=[0xe0b99a,0xad8062,0xd09f7c].map(c=>material(c)))[index%3]);for(const x of [-.08,.08])addBox(g,x,.25,0,.09,.45,.10,p.metal);if(staff)addBox(g,0,.66,.18,.22,.38,.035,p.wall);return g;}
export function buildCafeScene(snapshot,floor){const w=sceneBase(),{group:g,p}=w;w.mode='cafe';w.size=snapshot.bakery?24:15;const appearance=snapshot.appearance||{style:'nordic',terrace:false},theme=CAFE_PALETTE12[appearance.style]||CAFE_PALETTE12.nordic;p.wall.color.set(theme.wall);p.wood.color.set(theme.wood);p.blue.color.set(theme.accent);addBox(g,0,-.16,0,10,.3,8,p.wood);for(let x=0;x<8;x++)for(let y=0;y<6;y++){const pos=floorPoint(x,y),tile=addBox(g,pos.x,.025,pos.z,1.14,.03,1.14,material((x+y)%2?0xe1ded2:0xe9e5db));tile.userData={kind:'floor',id:x+','+y,x,y};w.objects.push(tile);}addBox(g,0,1.35,-3.6,9.8,2.7,.17,p.wall);addBox(g,-4.8,1.35,0,.17,2.7,7.2,p.wall);for(const x of [-3,-1,1,3]){addBox(g,x,1.5,-3.48,1.5,1.65,.06,p.glass);addBox(g,x,2.4,-3.4,1.7,.1,.2,p.metal);}for(const z of [-2,0,2]){addCylinder(g,-4.1,.5,z,.26,1,p.wall);tree(g,-4.1,z,p,.45);}
 for(const item of floor.items){const pos=floorPoint(item.x,item.y),mesh=furniture(item,p);mesh.position.set(pos.x,.06,pos.z);mesh.userData.anchor.set(pos.x,1.8,pos.z);g.add(mesh);w.objects.push(mesh);}if(appearance.terrace)terrace12(w);if(snapshot.bakery)bakeryRoom12(w,snapshot.bakery,9,0);w.floor=floor;w.actorPool=[];setCafeActors(w,snapshot);const selection=new T.Mesh(new T.BoxGeometry(1.18,.035,1.18),new T.MeshBasicMaterial({color:COLORS.blue,transparent:true,opacity:.42}));selection.position.y=.085;selection.visible=false;g.add(selection);w.selection=selection;return w;}
export function setWorldNight(w,night){w.scene.background.set(night?0x131e32:0xbfcbd0);w.scene.fog.color.copy(w.scene.background);w.hemi.intensity=night?.46:2;w.sun.intensity=night?.55:3.1;w.sun.color.set(night?0xa8c5ff:0xfff4df);w.p.glass.emissiveIntensity=night?1.1:0;for(const light of w.lights)light.intensity=night?8:0;}
export function animateWorld(w,time){for(const a of w.actors){const t=(time*a.speed+(a.phase||0))%1;if(a.kind==='traffic'||a.kind==='delivery'&&a.active){const side=Math.floor(t*4),f=(t*4)%1,v=19.25;let x,z,rot;if(side===0){x=-v+f*v*2;z=-v;rot=Math.PI/2;}else if(side===1){x=v;z=-v+f*v*2;rot=0;}else if(side===2){x=v-f*v*2;z=v;rot=-Math.PI/2;}else{x=-v;z=v-f*v*2;rot=Math.PI;}if(w.mode==='city'){x=(x+v)/(2*v)*90-43;z=(z+v)/(2*v)*79-37;}if(w.mode==='city'){const wet=!dryDecoration(w,x,z,.5),bridge=w.streets?.some(s=>s.bridge&&x>=Math.min(s.a[0],s.b[0])-s.width/2&&x<=Math.max(s.a[0],s.b[0])+s.width/2&&z>=Math.min(s.a[1],s.b[1])-s.width/2&&z<=Math.max(s.a[1],s.b[1])+s.width/2);a.mesh.visible=!wet||bridge;a.mesh.position.y=bridge?.7:.4;}a.mesh.position.set(x,w.mode==='city'?a.mesh.position.y:.4,z);a.mesh.rotation.y=rot;}else if(a.kind==='delivery'){a.mesh.position.set(a.parking.x,.1,a.parking.z);}else if(a.seat){const pos=floorPoint(a.seat.x,a.seat.y);a.mesh.position.set(pos.x,.0,pos.z+a.seat.offset);a.mesh.rotation.y=a.seat.angle;}else if(a.path?.length){const step=(time*(a.kind==='worker'?.5:.35)+a.phase*10)%(a.path.length-1||1),i=Math.floor(step),f=step-i,from=floorPoint(a.path[i].x,a.path[i].y),next=a.path[Math.min(i+1,a.path.length-1)],to=floorPoint(next.x,next.y);a.mesh.position.set(from.x+(to.x-from.x)*f,0,from.z+(to.z-from.z)*f);if(to.x!==from.x||to.z!==from.z)a.mesh.rotation.y=Math.atan2(to.x-from.x,to.z-from.z);}}}
export function setCafeActors(w,snapshot){
 if(w.mode!=='cafe')return;const slot=snapshot.slot||{},workerCount=Math.min(7,slot.workers||0),seats=seatPositions(w.floor),seated=Math.min(12,slot.occupied||0,seats.length),guests=Math.min(18,(slot.queue||0)+seated+Math.min(5,slot.served||0));
 const needs=[...Array.from({length:workerCount},(_,i)=>({kind:'worker',index:i,person:snapshot.crew[i],path:workerRoute(w.floor,i)})),...Array.from({length:guests},(_,i)=>({kind:'guest',index:i,seat:i<seated?seats[i]:null,path:guestRoute(w.floor)}))];
 w.actors=[];w.objects=w.objects.filter(o=>o.userData.kind!=='worker');
 for(let i=0;i<Math.max(needs.length,w.actorPool.length);i++){
  const need=needs[i];if(!need){w.actorPool[i].mesh.visible=false;continue;}
  let actor=w.actorPool[i];if(!actor||actor.kind!==need.kind){if(actor){w.group.remove(actor.mesh);actor.mesh.traverse(o=>o.geometry?.dispose());}actor={mesh:person(w.p,need.index,need.kind==='worker')};w.group.add(actor.mesh);w.actorPool[i]=actor;}
  Object.assign(actor,need,{phase:need.index*.14});actor.mesh.visible=true;actor.mesh.userData=need.person?{kind:'worker',id:need.person.id,title:need.person.name}:{};if(need.person)w.objects.push(actor.mesh);w.actors.push(actor);
 }
}

export function sceneStats(w){let meshes=0,vertices=0;w.scene.traverse(o=>{if(o.isMesh){meshes++;vertices+=o.geometry.getAttribute('position')?.count||0;}});return {meshes,vertices,objects:w.objects.map(o=>({...o.userData,anchor:undefined})),mode:w.mode};}
export function disposeWorld(w){const geometries=new Set(),materials=new Set();w.scene.traverse(o=>{if(o.geometry)geometries.add(o.geometry);if(o.material)(Array.isArray(o.material)?o.material:[o.material]).forEach(m=>materials.add(m));});geometries.forEach(g=>g.dispose());materials.forEach(m=>m.dispose());w.scene.clear();}

const CAFE_PALETTE12={nordic:{wall:'#eeede7',wood:'#bca989',accent:'#555fc0'},industrial:{wall:'#c1a092',wood:'#866b51',accent:'#3b4a58'},garden:{wall:'#d4dfd0',wood:'#a49c78',accent:'#668266'},classic:{wall:'#eee2ce',wood:'#87684d',accent:'#766055'},coastal:{wall:'#edf2f0',wood:'#c5b798',accent:'#6a99b4'},night:{wall:'#656b78',wood:'#9e775b',accent:'#6e5b97'}};
function roadSegment12(g,a,b,width,mat,y=.035){const dx=b[0]-a[0],dz=b[1]-a[1],length=Math.hypot(dx,dz),m=addBox(g,(a[0]+b[0])/2,y,(a[1]+b[1])/2,width,.06,length,mat);m.rotation.y=Math.atan2(dx,dz);return m;}
function waterCourse12(g,points,width,p){for(let i=1;i<points.length;i++)roadSegment12(g,points[i-1],points[i],width,p,.095);for(const [x,z] of points)addCylinder(g,x,.095,z,width/2,.06,p,width/2,24);}
function dryDecoration(w,x,z,r){return !footprintOnWater({minX:x-r,maxX:x+r,minZ:z-r,maxZ:z+r},w.waterways,.4);}
function placeBuildingOnLand(w,building,origin,record=true){building.updateMatrixWorld(true);const box=new T.Box3().setFromObject(building),bounds={minX:box.min.x,maxX:box.max.x,minZ:box.min.z,maxZ:box.max.z},pos=placeOnLand(origin,bounds,w.waterways,w.landLimits,record?w.landFootprints:[]);if(record)w.landFootprints.push(translatedFootprint(bounds,pos.x,pos.z));return pos;}
function dryStreet(w,a,b,width,mat){for(const span of streetSpans(a,b,width,w.waterways)){const length=Math.hypot(span.b[0]-span.a[0],span.b[1]-span.a[1]);if(length<.01)continue;if(span.wet&&length>26)continue;const mesh=roadSegment12(w.group,span.a,span.b,width,mat,span.wet?.29:.035);w.streets.push({...span,width,bridge:span.wet});if(span.wet){mesh.scale.y=4;const dx=(span.b[0]-span.a[0])/length,dz=(span.b[1]-span.a[1])/length;for(const side of [-1,1])roadSegment12(w.group,[span.a[0]+dz*side*(width/2+.05),span.a[1]-dx*side*(width/2+.05)],[span.b[0]+dz*side*(width/2+.05),span.b[1]-dx*side*(width/2+.05)],.09,w.p.metal,.70);}}}
function palm12(g,x,z,p){addCylinder(g,x,1.7,z,.15,3.4,p.bark);for(let i=0;i<6;i++){const leaf=addBox(g,x,3.5,z,.35,.12,2.4,p.leaf);leaf.rotation.y=i*Math.PI/3;leaf.rotation.z=.12;}}

function landmark12(g,profile,p){const [x,z]=profile.landmarkPosition,l=new T.Group();l.position.set(x,0,z);l.userData.landmark=profile.landmarkName;const k=profile.landmark;
 if(k==='tokyotower'||k==='eiffel'){const height=14;const beam=(a,b,r,mat)=>{const from=new T.Vector3(...a),to=new T.Vector3(...b),v=to.clone().sub(from),m=new T.Mesh(new T.CylinderGeometry(r,r,v.length(),6),mat);m.position.copy(from.add(to).multiplyScalar(.5));m.quaternion.setFromUnitVectors(new T.Vector3(0,1,0),v.normalize());l.add(m);};const red=material(0xb77560);for(let tier=0;tier<5;tier++){const y0=tier*2.4,y1=(tier+1)*2.4,w0=2.2*(1-tier/5)+.15,w1=2.2*(1-(tier+1)/5)+.15,mat=k==='eiffel'?p.metal:tier%2?p.white:red;for(const x of [-1,1])for(const z of [-1,1])beam([x*w0,y0,z*w0],[x*w1,y1,z*w1],.09,mat);for(const side of [-1,1]){beam([-w0,y0,side*w0],[w1,y1,side*w1],.055,mat);beam([w0,y0,side*w0],[-w1,y1,side*w1],.055,mat);beam([side*w0,y0,-w0],[side*w1,y1,w1],.055,mat);beam([side*w0,y0,w0],[side*w1,y1,-w1],.055,mat);}if(tier===1||tier===3)addBox(l,0,y1,0,w1*2+.5,.22,w1*2+.5,p.wall);}addCylinder(l,0,height-.8,0,.065,3.1,p.metal);}
 else if(['needle','burj','empire'].includes(k)){const tall=k==='burj'?20:k==='empire'?15:12;for(let i=0;i<5;i++){const width=(5-i)*.45+.6;addBox(l,0,tall*(i+.5)/5,0,width,tall/5,width,k==='tokyotower'?material(i%2?0xe0ddd4:0xb67a66):p.roof);}addCylinder(l,0,tall+.8,0,.055,2,p.metal);if(k==='needle')addCylinder(l,0,10,0,1.5,.65,p.wall);}
 else if(k==='sails'){addBox(l,0,.3,0,8,.6,5,p.paving);for(const [i,x] of [-2,0,2].entries()){const sail=new T.Mesh(new T.ConeGeometry(1.8,3.4,4),p.white);sail.rotation.z=.3;sail.position.set(x,2,0);l.add(sail);}}
 else if(k==='canalhouse'){for(let i=0;i<4;i++){const x=-3.6+i*2.4,h=3.4+i%2*.8,face=material([0xc3a08a,0xa6b4ac,0xbba772,0xbb9081][i]);addBox(l,x,h/2,0,2.1,h,2.6,face);const roof=new T.Mesh(new T.ConeGeometry(1.6,1.2,4),p.roof);roof.rotation.y=Math.PI/4;roof.scale.z=.9;roof.position.set(x,h+.6,0);l.add(roof);for(const y of [1,2.5])addBox(l,x,y,1.32,.65,.8,.03,p.glass);}}
 else if(k==='plaza'){addBox(l,0,.05,0,10,.1,8,p.paving);for(const x of [-4.5,4.5])addBox(l,x,1.4,0,1.5,2.8,8,p.wall);addBox(l,0,1.4,-3.5,9,2.8,1.3,p.wall);addCylinder(l,0,.25,0,.9,.35,p.glass);}
 else if(k==='marina'){for(const x of [-3,0,3])addBox(l,x,4,0,1.6,8,2,p.glass);addBox(l,0,8.2,0,9,.45,2.5,p.wall);}
 else if(k==='gate'){for(const x of [-2.5,-1.5,-.5,.5,1.5,2.5])addCylinder(l,x,1.6,0,.22,3.2,p.wall);addBox(l,0,3.35,0,6.6,.5,2,p.wall);}
 else if(k==='clock'||k==='cathedral'){addBox(l,0,2,0,4,4,3,p.wall);for(const x of [-1.5,1.5]){addBox(l,x,3.4,0,.9,6.8,1,p.wall);const spire=new T.Mesh(new T.ConeGeometry(.8,2,4),p.roof);spire.position.set(x,7.7,0);l.add(spire);}if(k==='clock')addSphere(l,1.5,5,0.55,.35,p.white);}
 else if(k==='tram'){addBox(l,0,.8,0,6,1.6,1.6,material(0xceac6a));for(const x of [-2,-.7,.7,2])addBox(l,x,1.1,.82,.8,.7,.03,p.glass);}
 else {addBox(l,0,1.5,0,8,3,4,p.wall);for(const x of [-3,3])addBox(l,x,2.6,0,1.4,5.2,2,p.wall);if(k==='dome')addSphere(l,0,4.1,0,1.3,p.roof);if(k==='station'||k==='castle')addBox(l,0,3.2,0,8.2,.4,4.2,p.roof);}
 return l;
}
function cityLandscape12(w,profile){const {group:g,p}=w;const depth=w.landLimits.maxZ+50,cz=(w.landLimits.maxZ-50)/2;addBox(g,0,-.32,cz,105,.6,depth,p.grass);addBox(g,0,-.69,cz,105,.16,depth,material(0xb2b8ae));const water=material(0x91aebb,{roughness:.40,metalness:.12});
 if(profile.hills){for(const [x,z] of [[-35,-35],[31,-37]]){if(!dryDecoration(w,x,z,9))continue;const hill=addSphere(g,x,-1,z,9,p.grass);hill.scale.y=.22;}}
 for(const x of [-43,-25,-7,11,29,47]){dryStreet(w,[x,-43],[x,48],2.2,p.road);dryStreet(w,[x+1.7,-43],[x+1.7,48],.5,p.paving);}for(const z of [-37,-10,17,42])dryStreet(w,[-48,z],[48,z],2.2,p.road);
 for(const course of w.waterways)waterCourse12(g,course.points,course.width,water);
 if(profile.ring&&dryDecoration(w,0,0,15)){const ring=new T.Mesh(new T.RingGeometry(13,15,64),p.paving);ring.rotation.x=-Math.PI/2;ring.position.y=.17;g.add(ring);}if(profile.park){const px=profile.landmark==='plaza'?34:-18,pz=profile.landmark==='plaza'?10:-14;if(!footprintOnWater({minX:px-7.5,maxX:px+7.5,minZ:pz-10,maxZ:pz+10},w.waterways))addBox(g,px,-.005,pz,15,.08,20,material(0x97ad8b));for(let i=0;i<8;i++){const x=px-6+i%2*9,z=pz-8+Math.floor(i/2)*5;if(dryDecoration(w,x,z,1))tree(g,x,z,p,.8);}}
 for(let i=0;i<20;i++){const x=-46+i%10*9.8,z=i<10?-43:40;if(!dryDecoration(w,x,z,1))continue;tree(g,x,z,p,.65+(.1*(i%3)));}if(profile.palms)for(const x of [-36,-18,18,36])if(dryDecoration(w,x,38,2.5))palm12(g,x,38,p);if(profile.laneways)for(const x of [-33,-15,3,21])dryStreet(w,[x,-30],[x,28],.9,p.paving);const landmark=landmark12(g,profile,p),landmarkPos=placeBuildingOnLand(w,landmark,{x:0,z:0},false);landmark.position.x+=landmarkPos.x;landmark.position.z+=landmarkPos.z;g.add(landmark);
 // Background blocks communicate a local architectural family, never extra assets.
 const shades=profile.architecture==='colourful'?[0xc99c80,0xb8b990,0xc7b275,0xa1b5b1]:[profile.wall,0xc3c5b8,0xd6cab8];
 for(let i=0;i<16;i++){const x=-42+i%8*11.8,z=-34+Math.floor(i/8)*64,height=['skyline','glass','dense'].includes(profile.architecture)?5+(i%4)*3.2:2.8+(i%3)*.7,b=new T.Group();b.position.set(x,0,z);const face=material(shades[i%shades.length]);addBox(b,0,height/2,0,4,height,3.7,face);addBox(b,0,height+.15,0,4.3,.3,4,p.roof);for(let level=0;level<Math.floor(height/1.4);level++)for(const dx of [-1,1])addBox(b,dx,.9+level*1.4,1.88,.55,.65,.04,p.glass);if(['historic','colourful','canal'].includes(profile.architecture)){const roof=new T.Mesh(new T.ConeGeometry(3.2,1.4,4),p.roof);roof.rotation.y=Math.PI/4;roof.scale.z=.8;roof.position.set(0,height+.8,0);b.add(roof);}if(dryDecoration(w,x,z,3.3)){g.add(b);compactMeshes(b);}else {b.traverse(o=>o.geometry?.dispose());face.dispose();}}
}
function terrace12(w){const {group:g,p}=w;addBox(g,0,-.1,6,10,.25,4,p.wood);for(const x of [-3,0,3]){addCylinder(g,x,.75,6,.45,.12,p.wood);for(const dz of [-.65,.65])chair(g,x,6+dz,p,dz<0?Math.PI:0);addCylinder(g,x,1.4,6,.035,2.8,p.metal);const umbrella=new T.Mesh(new T.ConeGeometry(1.35,.45,8),p.wall);umbrella.position.set(x,2.8,6);g.add(umbrella);}for(const x of [-4.6,4.6])tree(g,x,6,p,.7);}
function workRoom12(w,width=12,depth=9){const {group:g,p}=w;addBox(g,0,-.16,0,width,.3,depth,p.paving);addBox(g,0,1.5,-depth/2,width,3,.18,p.wall);addBox(g,-width/2,1.5,0,.18,3,depth,p.wall);for(const x of [-3,0,3])addBox(g,x,1.8,-depth/2+.12,1.6,1.3,.04,p.glass);w.size=Math.max(width,depth)*1.8;}
function assetStation12(w,id,title,x,z,kind='desk',data={}){const {group:g,p}=w,b=new T.Group();b.position.set(x,0,z);if(kind==='oven'){addBox(b,0,.9,0,1.4,1.8,1.2,p.metal);for(const y of [.6,1.1])addBox(b,0,y,.62,1.05,.30,.04,p.glass);addCylinder(b,.4,2,0,.1,.5,p.metal);}else if(kind==='mixer'){addBox(b,0,.65,0,1.4,1.3,1,p.wall);addCylinder(b,0,1.4,.3,.35,.3,p.metal);addBox(b,0,1.8,0,.65,.35,.45,p.metal);}else if(kind==='shelf'){addBox(b,0,.9,0,1.8,1.8,.8,p.wood);for(const y of [.4,.9,1.4])for(const x of [-.55,0,.55])addBox(b,x,y,.42,.35,.28,.35,p.wall);}else if(kind==='roast'){const drum=addCylinder(b,0,1.05,0,.65,1.3,p.metal);drum.rotation.x=Math.PI/2;addBox(b,0,.4,0,1.6,.8,1.8,p.blue);addCylinder(b,0,2.1,-.5,.26,1.2,p.metal);}else if(kind==='plot'){addBox(b,0,.04,0,4,.08,3,p.grass);for(let row=0;row<3;row++)for(let col=0;col<4;col++){const x=-1.5+col,z=-1+row;addSphere(b,x,.35,z,.38,p.leaf);addSphere(b,x+.2,.45,z+.1,.07,material(data.ripe?0xb7735f:0x8f9b76));}}else{addBox(b,0,.84,0,2.4,.14,1.15,p.wood);for(const x of [-.9,.9])addBox(b,x,.4,0,.08,.8,.6,p.metal);if(kind==='desk'){addBox(b,0,1.2,-.22,.7,.5,.06,p.metal);addBox(b,0,1.2,-.18,.6,.4,.02,p.glass);chair(b,0,.8,p);}if(kind==='board')for(const x of [-.8,.8])for(const z of [-.7,.7])chair(b,x,z,p,z<0?Math.PI:0);}
 b.userData={kind:'asset-station',id,title,...data,anchor:new T.Vector3(x,2.5,z)};g.add(b);w.objects.push(b);return b;}
function bakeryRoom12(w,snapshot,offsetX=0,offsetZ=0){const group=w.group;const room=new T.Group();room.position.set(offsetX,0,offsetZ);group.add(room);const old=w.group;w.group=room;addBox(room,0,-.16,0,7.5,.3,8,w.p.paving);addBox(room,0,1.4,-4,7.5,2.8,.17,w.p.wall);assetStation12(w,'oven','Pec',-2,-2,'oven',{assetKind:'bakery',assetId:snapshot.id});assetStation12(w,'mixer','Hnětač',0,-2,'mixer',{assetKind:'bakery',assetId:snapshot.id});assetStation12(w,'raw','Suroviny',2,-2,'shelf',{assetKind:'bakery',assetId:snapshot.id});assetStation12(w,'bench','Výroba a receptury',0,1,'bench',{assetKind:'bakery',assetId:snapshot.id});assetStation12(w,'dispatch','Expedice',2,2.5,'shelf',{assetKind:'bakery',assetId:snapshot.id});for(let i=0;i<Math.min(4,snapshot.staff);i++){const worker=person(w.p,i,true);worker.position.set(-2+i*1.4,0,.15);room.add(worker);}for(const o of room.children)if(o.userData.anchor)o.userData.anchor.add(new T.Vector3(offsetX,0,offsetZ));w.group=old;}
export function buildAssetScene12(snapshot){const w=sceneBase();w.mode=snapshot.kind;w.snapshot=snapshot;const {group:g,p}=w;
 if(snapshot.kind==='bakery'){bakeryRoom12(w,snapshot);w.size=16;}
 else if(snapshot.kind==='hq'){workRoom12(w,14,11);assetStation12(w,'board','Board a strategie',3,2,'board',{assetKind:'hq'});for(const [i,[id,n]] of Object.entries(snapshot.departments).entries()){const x=-3+(i%3)*3.2,z=-2+Math.floor(i/3)*3.4;assetStation12(w,id,{hr:'HR a tým',finance:'Finance',sales:'Obchod',product:'Produkt',it:'IT a projekty'}[id],x,z,'desk',{assetKind:'hq',count:n});for(let personIndex=0;personIndex<Math.min(2,n);personIndex++){const worker=person(p,i+personIndex);worker.position.set(x+.5+personIndex*.4,0,z+.7);g.add(worker);}}addBox(g,3,1.7,-5.34,4,1.9,.06,p.blue);tree(g,-5,-3.7,p,.55);}
 else if(snapshot.kind==='estate'){w.size=24;addBox(g,0,-.25,0,22,.5,19,p.grass);const ripe=snapshot.cycle/snapshot.period>.75;for(let i=0;i<4;i++)assetStation12(w,'plot-'+i,'Kávovníky · záhon '+(i+1),i%2?3:-3,Math.floor(i/2)*5-4,'plot',{assetKind:'estate',ripe});roadSegment12(g,[-9,0],[9,0],1.15,p.wood);roadSegment12(g,[0,-8],[0,8],1.15,p.wood);assetStation12(w,'drying','Sušení a zpracování',-6,6,'bench',{assetKind:'estate'});assetStation12(w,'stock','Sklad a sklizeň',6,6,'shelf',{assetKind:'estate'});if(snapshot.irrigation){for(const x of [-6,6])addCylinder(g,x,.35,-7,.1,.7,p.blue);}for(const x of [-9,9])tree(g,x,-7,p,1.1);}
 else {workRoom12(w);assetStation12(w,snapshot.kind==='roaster'?'drum':'stock',snapshot.kind==='roaster'?'Pražicí buben':'Kávové zásoby',-3,-2,snapshot.kind==='roaster'?'roast':'shelf',{assetKind:snapshot.kind});assetStation12(w,'quality','Kontrola a plán',1,-2,'desk',{assetKind:snapshot.kind});assetStation12(w,'dispatch','Expedice a rozvoz',3,2,'shelf',{assetKind:snapshot.kind});}
 for(const o of w.objects)o.userData.assetId??=snapshot.id;const ring=new T.Mesh(new T.RingGeometry(.9,1.04,40),new T.MeshBasicMaterial({color:COLORS.blue,transparent:true,opacity:.65,side:T.DoubleSide}));ring.rotation.x=-Math.PI/2;ring.position.y=.14;ring.visible=false;g.add(ring);w.selection=ring;return w;}

function coffeeTruck8(p){const g=car(p,0x315747,true);g.scale.set(3,2.2,3);addBox(g,0,.75,.94,.9,.12,.7,p.wall);addBox(g,0,1.2,.57,.85,.12,.5,p.wood);return g;}
function citySourceBuilding8(kind,p){const g=new T.Group();if(kind==='stop'){addBox(g,0,.08,0,3.8,.16,2.4,p.paving);addBox(g,0,2,0,3.8,.16,2.4,p.blue);for(const x of [-1.6,1.6])addBox(g,x,1,0,.12,2,.12,p.metal);addBox(g,0,.8,-.9,3.2,1.6,.08,p.glass);}else{const h=kind==='office'?5:2.4;addBox(g,0,h/2,0,4,h,3,p.wall);addBox(g,0,h+.1,0,4.2,.2,3.2,kind==='school'?p.blue:p.roof);for(let y=1;y<h;y+=1.3)for(const x of [-1,1])addBox(g,x,y,1.52,.65,.6,.06,p.glass);}return g;}
